// Generated by CoffeeScript 1.9.3
(function() {
  var ChatClient;

  ChatClient = React.createClass({
    getInitialState: function() {
      return {
        room_key: "0",
        state: "init",
        chat_history: [],
        value: "Enter..."
      };
    },
    componentDidMount: function() {
      var conn;
      if (window["WebSocket"] != null) {
        conn = new WebSocket("ws://127.0.0.1:7788/ws");
        conn.onclose = (function(_this) {
          return function(evt) {
            return _this.setState({
              state: "connect_close"
            });
          };
        })(this);
        conn.onmessage = (function(_this) {
          return function(evt) {
            return _this.addMsg(evt.data);
          };
        })(this);
        this.setState({
          conn: conn
        });
      } else {
        this.setState({
          state: "NoWebSocket"
        });
      }
    },
    addMsg: function(msg) {
      var his;
      his = this.state.chat_history;
      his.push({
        sender: "fy",
        text: msg
      });
      return this.setState({
        chat_history: his
      });
    },
    mkHistoryItem: function(msg) {
      return React.createElement("div", {
        "id": "msg"
      }, React.createElement("p", null, " ", React.createElement("strong", null, " ", msg.sender, " "), "  ", msg.text, " "));
    },
    getHistory: function() {
      return this.state.chat_history.map(this.mkHistoryItem);
    },
    sendMsg: function() {
      var msg;
      console.log(this.refs.msg_input.getValue());
      msg = this.refs.msg_input.getValue();
      return this.state.conn.send(msg);
    },
    render: function() {
      return React.createElement("div", null, React.createElement("p", {
        "id": "history",
        "ref": "history"
      }, this.getHistory()), React.createElement("div", null, React.createElement("div", {
        "id": "sender"
      }, React.createElement(Input, {
        "type": 'text',
        "ref": 'msg_input'
      }), React.createElement(Button, {
        "bsStyle": 'primary',
        "onClick": this.sendMsg
      }, "Send"), React.createElement(Button, {
        "bsStyle": 'primary',
        "onClick": this.sendMsg
      }, "Clean"))));
    }
  });

  React.render(React.createElement(ChatClient, null), document.getElementById('chater'));

}).call(this);
