// Code generated by protoc-gen-go.
// source: ProtobufGen_fbreward.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FBREWARD struct {
	// * 运营类型ID
	ActivityID       *uint32              `protobuf:"varint,1,req,def=0" json:"ActivityID,omitempty"`
	Loot_Table       []*FBREWARD_LootRule `protobuf:"bytes,4,rep" json:"Loot_Table,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *FBREWARD) Reset()         { *m = FBREWARD{} }
func (m *FBREWARD) String() string { return proto.CompactTextString(m) }
func (*FBREWARD) ProtoMessage()    {}

const Default_FBREWARD_ActivityID uint32 = 0

func (m *FBREWARD) GetActivityID() uint32 {
	if m != nil && m.ActivityID != nil {
		return *m.ActivityID
	}
	return Default_FBREWARD_ActivityID
}

func (m *FBREWARD) GetLoot_Table() []*FBREWARD_LootRule {
	if m != nil {
		return m.Loot_Table
	}
	return nil
}

type FBREWARD_LootRule struct {
	// * 掉落组ID
	LootTemplateID *string `protobuf:"bytes,1,opt,def=" json:"LootTemplateID,omitempty"`
	// * 抽取次数
	LootTime         *uint32 `protobuf:"varint,2,opt,def=0" json:"LootTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FBREWARD_LootRule) Reset()         { *m = FBREWARD_LootRule{} }
func (m *FBREWARD_LootRule) String() string { return proto.CompactTextString(m) }
func (*FBREWARD_LootRule) ProtoMessage()    {}

const Default_FBREWARD_LootRule_LootTime uint32 = 0

func (m *FBREWARD_LootRule) GetLootTemplateID() string {
	if m != nil && m.LootTemplateID != nil {
		return *m.LootTemplateID
	}
	return ""
}

func (m *FBREWARD_LootRule) GetLootTime() uint32 {
	if m != nil && m.LootTime != nil {
		return *m.LootTime
	}
	return Default_FBREWARD_LootRule_LootTime
}

type FBREWARD_ARRAY struct {
	Items            []*FBREWARD `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FBREWARD_ARRAY) Reset()         { *m = FBREWARD_ARRAY{} }
func (m *FBREWARD_ARRAY) String() string { return proto.CompactTextString(m) }
func (*FBREWARD_ARRAY) ProtoMessage()    {}

func (m *FBREWARD_ARRAY) GetItems() []*FBREWARD {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
