// Code generated by protoc-gen-go.
// source: ProtobufGen_hotactivitydetail.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HOTACTIVITYDETAIL struct {
	// * 活动ID
	ActivityID *uint32 `protobuf:"varint,1,opt,def=0" json:"ActivityID,omitempty"`
	// * 活动子ID
	ActivitySubID *uint32 `protobuf:"varint,2,opt,def=0" json:"ActivitySubID,omitempty"`
	// * 完成条件类型
	FCType *uint32 `protobuf:"varint,3,opt,def=0" json:"FCType,omitempty"`
	// * 完成条件数值参数1
	FCValue1 *uint32 `protobuf:"varint,4,opt,def=0" json:"FCValue1,omitempty"`
	// * 完成条件数值参数2
	FCValue2 *uint32 `protobuf:"varint,5,opt,def=0" json:"FCValue2,omitempty"`
	// * 完成条件数值参数1
	SFCValue1 *string `protobuf:"bytes,7,opt,def=" json:"SFCValue1,omitempty"`
	// * 完成条件数值参数2
	SFCValue2        *string                            `protobuf:"bytes,8,opt,def=" json:"SFCValue2,omitempty"`
	Item_Table       []*HOTACTIVITYDETAIL_ItemCondition `protobuf:"bytes,6,rep" json:"Item_Table,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *HOTACTIVITYDETAIL) Reset()         { *m = HOTACTIVITYDETAIL{} }
func (m *HOTACTIVITYDETAIL) String() string { return proto.CompactTextString(m) }
func (*HOTACTIVITYDETAIL) ProtoMessage()    {}

const Default_HOTACTIVITYDETAIL_ActivityID uint32 = 0
const Default_HOTACTIVITYDETAIL_ActivitySubID uint32 = 0
const Default_HOTACTIVITYDETAIL_FCType uint32 = 0
const Default_HOTACTIVITYDETAIL_FCValue1 uint32 = 0
const Default_HOTACTIVITYDETAIL_FCValue2 uint32 = 0

func (m *HOTACTIVITYDETAIL) GetActivityID() uint32 {
	if m != nil && m.ActivityID != nil {
		return *m.ActivityID
	}
	return Default_HOTACTIVITYDETAIL_ActivityID
}

func (m *HOTACTIVITYDETAIL) GetActivitySubID() uint32 {
	if m != nil && m.ActivitySubID != nil {
		return *m.ActivitySubID
	}
	return Default_HOTACTIVITYDETAIL_ActivitySubID
}

func (m *HOTACTIVITYDETAIL) GetFCType() uint32 {
	if m != nil && m.FCType != nil {
		return *m.FCType
	}
	return Default_HOTACTIVITYDETAIL_FCType
}

func (m *HOTACTIVITYDETAIL) GetFCValue1() uint32 {
	if m != nil && m.FCValue1 != nil {
		return *m.FCValue1
	}
	return Default_HOTACTIVITYDETAIL_FCValue1
}

func (m *HOTACTIVITYDETAIL) GetFCValue2() uint32 {
	if m != nil && m.FCValue2 != nil {
		return *m.FCValue2
	}
	return Default_HOTACTIVITYDETAIL_FCValue2
}

func (m *HOTACTIVITYDETAIL) GetSFCValue1() string {
	if m != nil && m.SFCValue1 != nil {
		return *m.SFCValue1
	}
	return ""
}

func (m *HOTACTIVITYDETAIL) GetSFCValue2() string {
	if m != nil && m.SFCValue2 != nil {
		return *m.SFCValue2
	}
	return ""
}

func (m *HOTACTIVITYDETAIL) GetItem_Table() []*HOTACTIVITYDETAIL_ItemCondition {
	if m != nil {
		return m.Item_Table
	}
	return nil
}

type HOTACTIVITYDETAIL_ItemCondition struct {
	// * 奖励物品ID
	ItemID *string `protobuf:"bytes,1,opt,def=" json:"ItemID,omitempty"`
	// * 奖励物品数量
	ItemCount        *uint32 `protobuf:"varint,2,opt,def=0" json:"ItemCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HOTACTIVITYDETAIL_ItemCondition) Reset()         { *m = HOTACTIVITYDETAIL_ItemCondition{} }
func (m *HOTACTIVITYDETAIL_ItemCondition) String() string { return proto.CompactTextString(m) }
func (*HOTACTIVITYDETAIL_ItemCondition) ProtoMessage()    {}

const Default_HOTACTIVITYDETAIL_ItemCondition_ItemCount uint32 = 0

func (m *HOTACTIVITYDETAIL_ItemCondition) GetItemID() string {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return ""
}

func (m *HOTACTIVITYDETAIL_ItemCondition) GetItemCount() uint32 {
	if m != nil && m.ItemCount != nil {
		return *m.ItemCount
	}
	return Default_HOTACTIVITYDETAIL_ItemCondition_ItemCount
}

type HOTACTIVITYDETAIL_ARRAY struct {
	Items            []*HOTACTIVITYDETAIL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *HOTACTIVITYDETAIL_ARRAY) Reset()         { *m = HOTACTIVITYDETAIL_ARRAY{} }
func (m *HOTACTIVITYDETAIL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*HOTACTIVITYDETAIL_ARRAY) ProtoMessage()    {}

func (m *HOTACTIVITYDETAIL_ARRAY) GetItems() []*HOTACTIVITYDETAIL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
