// Code generated by protoc-gen-go.
// source: ProtobufGen_jadeconditon.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type JADECONDITON struct {
	// * 对应部位枚举
	ItemCondition    *uint32                 `protobuf:"varint,1,opt,def=0" json:"ItemCondition,omitempty"`
	Positon_Table    []*JADECONDITON_Positon `protobuf:"bytes,2,rep" json:"Positon_Table,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *JADECONDITON) Reset()         { *m = JADECONDITON{} }
func (m *JADECONDITON) String() string { return proto.CompactTextString(m) }
func (*JADECONDITON) ProtoMessage()    {}

const Default_JADECONDITON_ItemCondition uint32 = 0

func (m *JADECONDITON) GetItemCondition() uint32 {
	if m != nil && m.ItemCondition != nil {
		return *m.ItemCondition
	}
	return Default_JADECONDITON_ItemCondition
}

func (m *JADECONDITON) GetPositon_Table() []*JADECONDITON_Positon {
	if m != nil {
		return m.Positon_Table
	}
	return nil
}

type JADECONDITON_Positon struct {
	// * 孔解锁等级
	PositonLevel *uint32 `protobuf:"varint,1,opt,def=0" json:"PositonLevel,omitempty"`
	// * 可镶嵌的宝石类型
	JadeType         *string `protobuf:"bytes,2,opt,def=" json:"JadeType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JADECONDITON_Positon) Reset()         { *m = JADECONDITON_Positon{} }
func (m *JADECONDITON_Positon) String() string { return proto.CompactTextString(m) }
func (*JADECONDITON_Positon) ProtoMessage()    {}

const Default_JADECONDITON_Positon_PositonLevel uint32 = 0

func (m *JADECONDITON_Positon) GetPositonLevel() uint32 {
	if m != nil && m.PositonLevel != nil {
		return *m.PositonLevel
	}
	return Default_JADECONDITON_Positon_PositonLevel
}

func (m *JADECONDITON_Positon) GetJadeType() string {
	if m != nil && m.JadeType != nil {
		return *m.JadeType
	}
	return ""
}

type JADECONDITON_ARRAY struct {
	Items            []*JADECONDITON `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *JADECONDITON_ARRAY) Reset()         { *m = JADECONDITON_ARRAY{} }
func (m *JADECONDITON_ARRAY) String() string { return proto.CompactTextString(m) }
func (*JADECONDITON_ARRAY) ProtoMessage()    {}

func (m *JADECONDITON_ARRAY) GetItems() []*JADECONDITON {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
