// Code generated by protoc-gen-go.
// source: ProtobufGen_equipupgrade.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type EQUIPUPGRADE struct {
	// * 强化等级
	UpgradeLevel *uint32 `protobuf:"varint,1,req,def=0" json:"UpgradeLevel,omitempty"`
	// * 累计精铁消耗
	FineIronCost *uint32 `protobuf:"varint,2,opt,def=0" json:"FineIronCost,omitempty"`
	// * 累计SC消耗
	SC *uint32 `protobuf:"varint,3,opt,def=0" json:"SC,omitempty"`
	// * 武器攻击力
	Weapon_ATT *float32 `protobuf:"fixed32,4,opt,def=0" json:"Weapon_ATT,omitempty"`
	// * 武器防御力
	Weapon_DEF *float32 `protobuf:"fixed32,5,opt,def=0" json:"Weapon_DEF,omitempty"`
	// * 武器生命值
	Weapon_HP *float32 `protobuf:"fixed32,6,opt,def=0" json:"Weapon_HP,omitempty"`
	// * 外衣攻击力
	Chest_ATT *float32 `protobuf:"fixed32,7,opt,def=0" json:"Chest_ATT,omitempty"`
	// * 外衣防御力
	Chest_DEF *float32 `protobuf:"fixed32,8,opt,def=0" json:"Chest_DEF,omitempty"`
	// * 外衣生命值
	Chest_HP *float32 `protobuf:"fixed32,9,opt,def=0" json:"Chest_HP,omitempty"`
	// * 腰带攻击力
	Belt_ATT *float32 `protobuf:"fixed32,10,opt,def=0" json:"Belt_ATT,omitempty"`
	// * 腰带防御力
	Belt_DEF *float32 `protobuf:"fixed32,11,opt,def=0" json:"Belt_DEF,omitempty"`
	// * 腰带生命值
	Belt_HP *float32 `protobuf:"fixed32,12,opt,def=0" json:"Belt_HP,omitempty"`
	// * 腿甲攻击力
	Leggings_ATT *float32 `protobuf:"fixed32,13,opt,def=0" json:"Leggings_ATT,omitempty"`
	// * 腿甲防御力
	Leggings_DEF *float32 `protobuf:"fixed32,14,opt,def=0" json:"Leggings_DEF,omitempty"`
	// * 腿甲生命值
	Leggings_HP *float32 `protobuf:"fixed32,15,opt,def=0" json:"Leggings_HP,omitempty"`
	// * 护腕攻击力
	Bracers_ATT *float32 `protobuf:"fixed32,16,opt,def=0" json:"Bracers_ATT,omitempty"`
	// * 护腕防御力
	Bracers_DEF *float32 `protobuf:"fixed32,17,opt,def=0" json:"Bracers_DEF,omitempty"`
	// * 护腕生命值
	Bracers_HP *float32 `protobuf:"fixed32,18,opt,def=0" json:"Bracers_HP,omitempty"`
	// * 项链攻击力
	Necklace_ATT *float32 `protobuf:"fixed32,19,opt,def=0" json:"Necklace_ATT,omitempty"`
	// * 项链防御力
	Necklace_DEF *float32 `protobuf:"fixed32,20,opt,def=0" json:"Necklace_DEF,omitempty"`
	// * 项链生命值
	Necklace_HP *float32 `protobuf:"fixed32,21,opt,def=0" json:"Necklace_HP,omitempty"`
	// * 戒指攻击力
	Ring_ATT *float32 `protobuf:"fixed32,22,opt,def=0" json:"Ring_ATT,omitempty"`
	// * 戒指防御力
	Ring_DEF *float32 `protobuf:"fixed32,23,opt,def=0" json:"Ring_DEF,omitempty"`
	// * 戒指生命值
	Ring_HP          *float32 `protobuf:"fixed32,24,opt,def=0" json:"Ring_HP,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *EQUIPUPGRADE) Reset()         { *m = EQUIPUPGRADE{} }
func (m *EQUIPUPGRADE) String() string { return proto.CompactTextString(m) }
func (*EQUIPUPGRADE) ProtoMessage()    {}

const Default_EQUIPUPGRADE_UpgradeLevel uint32 = 0
const Default_EQUIPUPGRADE_FineIronCost uint32 = 0
const Default_EQUIPUPGRADE_SC uint32 = 0
const Default_EQUIPUPGRADE_Weapon_ATT float32 = 0
const Default_EQUIPUPGRADE_Weapon_DEF float32 = 0
const Default_EQUIPUPGRADE_Weapon_HP float32 = 0
const Default_EQUIPUPGRADE_Chest_ATT float32 = 0
const Default_EQUIPUPGRADE_Chest_DEF float32 = 0
const Default_EQUIPUPGRADE_Chest_HP float32 = 0
const Default_EQUIPUPGRADE_Belt_ATT float32 = 0
const Default_EQUIPUPGRADE_Belt_DEF float32 = 0
const Default_EQUIPUPGRADE_Belt_HP float32 = 0
const Default_EQUIPUPGRADE_Leggings_ATT float32 = 0
const Default_EQUIPUPGRADE_Leggings_DEF float32 = 0
const Default_EQUIPUPGRADE_Leggings_HP float32 = 0
const Default_EQUIPUPGRADE_Bracers_ATT float32 = 0
const Default_EQUIPUPGRADE_Bracers_DEF float32 = 0
const Default_EQUIPUPGRADE_Bracers_HP float32 = 0
const Default_EQUIPUPGRADE_Necklace_ATT float32 = 0
const Default_EQUIPUPGRADE_Necklace_DEF float32 = 0
const Default_EQUIPUPGRADE_Necklace_HP float32 = 0
const Default_EQUIPUPGRADE_Ring_ATT float32 = 0
const Default_EQUIPUPGRADE_Ring_DEF float32 = 0
const Default_EQUIPUPGRADE_Ring_HP float32 = 0

func (m *EQUIPUPGRADE) GetUpgradeLevel() uint32 {
	if m != nil && m.UpgradeLevel != nil {
		return *m.UpgradeLevel
	}
	return Default_EQUIPUPGRADE_UpgradeLevel
}

func (m *EQUIPUPGRADE) GetFineIronCost() uint32 {
	if m != nil && m.FineIronCost != nil {
		return *m.FineIronCost
	}
	return Default_EQUIPUPGRADE_FineIronCost
}

func (m *EQUIPUPGRADE) GetSC() uint32 {
	if m != nil && m.SC != nil {
		return *m.SC
	}
	return Default_EQUIPUPGRADE_SC
}

func (m *EQUIPUPGRADE) GetWeapon_ATT() float32 {
	if m != nil && m.Weapon_ATT != nil {
		return *m.Weapon_ATT
	}
	return Default_EQUIPUPGRADE_Weapon_ATT
}

func (m *EQUIPUPGRADE) GetWeapon_DEF() float32 {
	if m != nil && m.Weapon_DEF != nil {
		return *m.Weapon_DEF
	}
	return Default_EQUIPUPGRADE_Weapon_DEF
}

func (m *EQUIPUPGRADE) GetWeapon_HP() float32 {
	if m != nil && m.Weapon_HP != nil {
		return *m.Weapon_HP
	}
	return Default_EQUIPUPGRADE_Weapon_HP
}

func (m *EQUIPUPGRADE) GetChest_ATT() float32 {
	if m != nil && m.Chest_ATT != nil {
		return *m.Chest_ATT
	}
	return Default_EQUIPUPGRADE_Chest_ATT
}

func (m *EQUIPUPGRADE) GetChest_DEF() float32 {
	if m != nil && m.Chest_DEF != nil {
		return *m.Chest_DEF
	}
	return Default_EQUIPUPGRADE_Chest_DEF
}

func (m *EQUIPUPGRADE) GetChest_HP() float32 {
	if m != nil && m.Chest_HP != nil {
		return *m.Chest_HP
	}
	return Default_EQUIPUPGRADE_Chest_HP
}

func (m *EQUIPUPGRADE) GetBelt_ATT() float32 {
	if m != nil && m.Belt_ATT != nil {
		return *m.Belt_ATT
	}
	return Default_EQUIPUPGRADE_Belt_ATT
}

func (m *EQUIPUPGRADE) GetBelt_DEF() float32 {
	if m != nil && m.Belt_DEF != nil {
		return *m.Belt_DEF
	}
	return Default_EQUIPUPGRADE_Belt_DEF
}

func (m *EQUIPUPGRADE) GetBelt_HP() float32 {
	if m != nil && m.Belt_HP != nil {
		return *m.Belt_HP
	}
	return Default_EQUIPUPGRADE_Belt_HP
}

func (m *EQUIPUPGRADE) GetLeggings_ATT() float32 {
	if m != nil && m.Leggings_ATT != nil {
		return *m.Leggings_ATT
	}
	return Default_EQUIPUPGRADE_Leggings_ATT
}

func (m *EQUIPUPGRADE) GetLeggings_DEF() float32 {
	if m != nil && m.Leggings_DEF != nil {
		return *m.Leggings_DEF
	}
	return Default_EQUIPUPGRADE_Leggings_DEF
}

func (m *EQUIPUPGRADE) GetLeggings_HP() float32 {
	if m != nil && m.Leggings_HP != nil {
		return *m.Leggings_HP
	}
	return Default_EQUIPUPGRADE_Leggings_HP
}

func (m *EQUIPUPGRADE) GetBracers_ATT() float32 {
	if m != nil && m.Bracers_ATT != nil {
		return *m.Bracers_ATT
	}
	return Default_EQUIPUPGRADE_Bracers_ATT
}

func (m *EQUIPUPGRADE) GetBracers_DEF() float32 {
	if m != nil && m.Bracers_DEF != nil {
		return *m.Bracers_DEF
	}
	return Default_EQUIPUPGRADE_Bracers_DEF
}

func (m *EQUIPUPGRADE) GetBracers_HP() float32 {
	if m != nil && m.Bracers_HP != nil {
		return *m.Bracers_HP
	}
	return Default_EQUIPUPGRADE_Bracers_HP
}

func (m *EQUIPUPGRADE) GetNecklace_ATT() float32 {
	if m != nil && m.Necklace_ATT != nil {
		return *m.Necklace_ATT
	}
	return Default_EQUIPUPGRADE_Necklace_ATT
}

func (m *EQUIPUPGRADE) GetNecklace_DEF() float32 {
	if m != nil && m.Necklace_DEF != nil {
		return *m.Necklace_DEF
	}
	return Default_EQUIPUPGRADE_Necklace_DEF
}

func (m *EQUIPUPGRADE) GetNecklace_HP() float32 {
	if m != nil && m.Necklace_HP != nil {
		return *m.Necklace_HP
	}
	return Default_EQUIPUPGRADE_Necklace_HP
}

func (m *EQUIPUPGRADE) GetRing_ATT() float32 {
	if m != nil && m.Ring_ATT != nil {
		return *m.Ring_ATT
	}
	return Default_EQUIPUPGRADE_Ring_ATT
}

func (m *EQUIPUPGRADE) GetRing_DEF() float32 {
	if m != nil && m.Ring_DEF != nil {
		return *m.Ring_DEF
	}
	return Default_EQUIPUPGRADE_Ring_DEF
}

func (m *EQUIPUPGRADE) GetRing_HP() float32 {
	if m != nil && m.Ring_HP != nil {
		return *m.Ring_HP
	}
	return Default_EQUIPUPGRADE_Ring_HP
}

type EQUIPUPGRADE_ARRAY struct {
	Items            []*EQUIPUPGRADE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *EQUIPUPGRADE_ARRAY) Reset()         { *m = EQUIPUPGRADE_ARRAY{} }
func (m *EQUIPUPGRADE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*EQUIPUPGRADE_ARRAY) ProtoMessage()    {}

func (m *EQUIPUPGRADE_ARRAY) GetItems() []*EQUIPUPGRADE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
