// Code generated by protoc-gen-go.
// source: ProtobufGen_cdtgiftvalue.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CDTGIFTVALUE struct {
	// * 表索引
	Index *uint32 `protobuf:"varint,1,req,def=0" json:"Index,omitempty"`
	// * 活动ID
	ActivityID *uint32 `protobuf:"varint,2,req,def=0" json:"ActivityID,omitempty"`
	// * 完成条件类型
	FCType *uint32 `protobuf:"varint,3,opt,def=0" json:"FCType,omitempty"`
	// * 完成条件数值参数
	FCValue *uint32 `protobuf:"varint,4,opt,def=1" json:"FCValue,omitempty"`
	// * 条目描述
	Desc               *string                   `protobuf:"bytes,5,opt,def=" json:"Desc,omitempty"`
	GoalAward_Template []*CDTGIFTVALUE_GoalAward `protobuf:"bytes,6,rep" json:"GoalAward_Template,omitempty"`
	XXX_unrecognized   []byte                    `json:"-"`
}

func (m *CDTGIFTVALUE) Reset()         { *m = CDTGIFTVALUE{} }
func (m *CDTGIFTVALUE) String() string { return proto.CompactTextString(m) }
func (*CDTGIFTVALUE) ProtoMessage()    {}

const Default_CDTGIFTVALUE_Index uint32 = 0
const Default_CDTGIFTVALUE_ActivityID uint32 = 0
const Default_CDTGIFTVALUE_FCType uint32 = 0
const Default_CDTGIFTVALUE_FCValue uint32 = 1

func (m *CDTGIFTVALUE) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_CDTGIFTVALUE_Index
}

func (m *CDTGIFTVALUE) GetActivityID() uint32 {
	if m != nil && m.ActivityID != nil {
		return *m.ActivityID
	}
	return Default_CDTGIFTVALUE_ActivityID
}

func (m *CDTGIFTVALUE) GetFCType() uint32 {
	if m != nil && m.FCType != nil {
		return *m.FCType
	}
	return Default_CDTGIFTVALUE_FCType
}

func (m *CDTGIFTVALUE) GetFCValue() uint32 {
	if m != nil && m.FCValue != nil {
		return *m.FCValue
	}
	return Default_CDTGIFTVALUE_FCValue
}

func (m *CDTGIFTVALUE) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *CDTGIFTVALUE) GetGoalAward_Template() []*CDTGIFTVALUE_GoalAward {
	if m != nil {
		return m.GoalAward_Template
	}
	return nil
}

type CDTGIFTVALUE_GoalAward struct {
	// * 奖励ID
	Reward *string `protobuf:"bytes,1,opt,def=" json:"Reward,omitempty"`
	// * 奖励数目
	Count            *uint32 `protobuf:"varint,2,opt,def=0" json:"Count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDTGIFTVALUE_GoalAward) Reset()         { *m = CDTGIFTVALUE_GoalAward{} }
func (m *CDTGIFTVALUE_GoalAward) String() string { return proto.CompactTextString(m) }
func (*CDTGIFTVALUE_GoalAward) ProtoMessage()    {}

const Default_CDTGIFTVALUE_GoalAward_Count uint32 = 0

func (m *CDTGIFTVALUE_GoalAward) GetReward() string {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return ""
}

func (m *CDTGIFTVALUE_GoalAward) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_CDTGIFTVALUE_GoalAward_Count
}

type CDTGIFTVALUE_ARRAY struct {
	Items            []*CDTGIFTVALUE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CDTGIFTVALUE_ARRAY) Reset()         { *m = CDTGIFTVALUE_ARRAY{} }
func (m *CDTGIFTVALUE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*CDTGIFTVALUE_ARRAY) ProtoMessage()    {}

func (m *CDTGIFTVALUE_ARRAY) GetItems() []*CDTGIFTVALUE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
