// Code generated by protoc-gen-go.
// source: ProtobufGen_ngqrefreshtime.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type NGQREFRESHTIME struct {
	// * 刷新时间
	RefreshTime      *string `protobuf:"bytes,1,req,def=" json:"RefreshTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NGQREFRESHTIME) Reset()         { *m = NGQREFRESHTIME{} }
func (m *NGQREFRESHTIME) String() string { return proto.CompactTextString(m) }
func (*NGQREFRESHTIME) ProtoMessage()    {}

func (m *NGQREFRESHTIME) GetRefreshTime() string {
	if m != nil && m.RefreshTime != nil {
		return *m.RefreshTime
	}
	return ""
}

type NGQREFRESHTIME_ARRAY struct {
	Items            []*NGQREFRESHTIME `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NGQREFRESHTIME_ARRAY) Reset()         { *m = NGQREFRESHTIME_ARRAY{} }
func (m *NGQREFRESHTIME_ARRAY) String() string { return proto.CompactTextString(m) }
func (*NGQREFRESHTIME_ARRAY) ProtoMessage()    {}

func (m *NGQREFRESHTIME_ARRAY) GetItems() []*NGQREFRESHTIME {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
