// Code generated by protoc-gen-go.
// source: ProtobufGen_cropsgift.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CROPSGIFT struct {
	// * 粮车品质ID
	CropsID *uint32 `protobuf:"varint,1,req,def=0" json:"CropsID,omitempty"`
	// * 押运奖励1（ID）
	CropsGift1ID *uint32 `protobuf:"varint,2,opt,def=0" json:"CropsGift1ID,omitempty"`
	// * 押运奖励1（数量）
	CropsGift1Amount *uint32 `protobuf:"varint,3,opt,def=0" json:"CropsGift1Amount,omitempty"`
	// * 押运奖励2（ID）
	CropsGift2ID *uint32 `protobuf:"varint,4,opt,def=0" json:"CropsGift2ID,omitempty"`
	// * 押运奖励2（数量）
	CropsGift2Amount *uint32 `protobuf:"varint,5,opt,def=0" json:"CropsGift2Amount,omitempty"`
	// * 掠夺奖励1（ID）
	RobsGift1ID *uint32 `protobuf:"varint,6,opt,def=0" json:"RobsGift1ID,omitempty"`
	// * 掠夺奖励1（数量）
	RobGift1Amount *uint32 `protobuf:"varint,7,opt,def=0" json:"RobGift1Amount,omitempty"`
	// * 掠夺奖励2（ID）
	RobsGift2ID *uint32 `protobuf:"varint,8,opt,def=0" json:"RobsGift2ID,omitempty"`
	// * 掠夺奖励2（数量）
	RobGift2Amount *uint32 `protobuf:"varint,9,opt,def=0" json:"RobGift2Amount,omitempty"`
	// * 护送奖励1（ID）
	EscortGift1ID *uint32 `protobuf:"varint,10,opt,def=0" json:"EscortGift1ID,omitempty"`
	// * 护送奖励1（数量）
	EscortGift1Amount *uint32 `protobuf:"varint,11,opt,def=0" json:"EscortGift1Amount,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *CROPSGIFT) Reset()         { *m = CROPSGIFT{} }
func (m *CROPSGIFT) String() string { return proto.CompactTextString(m) }
func (*CROPSGIFT) ProtoMessage()    {}

const Default_CROPSGIFT_CropsID uint32 = 0
const Default_CROPSGIFT_CropsGift1ID uint32 = 0
const Default_CROPSGIFT_CropsGift1Amount uint32 = 0
const Default_CROPSGIFT_CropsGift2ID uint32 = 0
const Default_CROPSGIFT_CropsGift2Amount uint32 = 0
const Default_CROPSGIFT_RobsGift1ID uint32 = 0
const Default_CROPSGIFT_RobGift1Amount uint32 = 0
const Default_CROPSGIFT_RobsGift2ID uint32 = 0
const Default_CROPSGIFT_RobGift2Amount uint32 = 0
const Default_CROPSGIFT_EscortGift1ID uint32 = 0
const Default_CROPSGIFT_EscortGift1Amount uint32 = 0

func (m *CROPSGIFT) GetCropsID() uint32 {
	if m != nil && m.CropsID != nil {
		return *m.CropsID
	}
	return Default_CROPSGIFT_CropsID
}

func (m *CROPSGIFT) GetCropsGift1ID() uint32 {
	if m != nil && m.CropsGift1ID != nil {
		return *m.CropsGift1ID
	}
	return Default_CROPSGIFT_CropsGift1ID
}

func (m *CROPSGIFT) GetCropsGift1Amount() uint32 {
	if m != nil && m.CropsGift1Amount != nil {
		return *m.CropsGift1Amount
	}
	return Default_CROPSGIFT_CropsGift1Amount
}

func (m *CROPSGIFT) GetCropsGift2ID() uint32 {
	if m != nil && m.CropsGift2ID != nil {
		return *m.CropsGift2ID
	}
	return Default_CROPSGIFT_CropsGift2ID
}

func (m *CROPSGIFT) GetCropsGift2Amount() uint32 {
	if m != nil && m.CropsGift2Amount != nil {
		return *m.CropsGift2Amount
	}
	return Default_CROPSGIFT_CropsGift2Amount
}

func (m *CROPSGIFT) GetRobsGift1ID() uint32 {
	if m != nil && m.RobsGift1ID != nil {
		return *m.RobsGift1ID
	}
	return Default_CROPSGIFT_RobsGift1ID
}

func (m *CROPSGIFT) GetRobGift1Amount() uint32 {
	if m != nil && m.RobGift1Amount != nil {
		return *m.RobGift1Amount
	}
	return Default_CROPSGIFT_RobGift1Amount
}

func (m *CROPSGIFT) GetRobsGift2ID() uint32 {
	if m != nil && m.RobsGift2ID != nil {
		return *m.RobsGift2ID
	}
	return Default_CROPSGIFT_RobsGift2ID
}

func (m *CROPSGIFT) GetRobGift2Amount() uint32 {
	if m != nil && m.RobGift2Amount != nil {
		return *m.RobGift2Amount
	}
	return Default_CROPSGIFT_RobGift2Amount
}

func (m *CROPSGIFT) GetEscortGift1ID() uint32 {
	if m != nil && m.EscortGift1ID != nil {
		return *m.EscortGift1ID
	}
	return Default_CROPSGIFT_EscortGift1ID
}

func (m *CROPSGIFT) GetEscortGift1Amount() uint32 {
	if m != nil && m.EscortGift1Amount != nil {
		return *m.EscortGift1Amount
	}
	return Default_CROPSGIFT_EscortGift1Amount
}

type CROPSGIFT_ARRAY struct {
	Items            []*CROPSGIFT `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CROPSGIFT_ARRAY) Reset()         { *m = CROPSGIFT_ARRAY{} }
func (m *CROPSGIFT_ARRAY) String() string { return proto.CompactTextString(m) }
func (*CROPSGIFT_ARRAY) ProtoMessage()    {}

func (m *CROPSGIFT_ARRAY) GetItems() []*CROPSGIFT {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
