// Code generated by protoc-gen-go.
// source: ProtobufGen_mailmain.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MAILMAIN struct {
	// * 邮件类别
	MailType *uint32 `protobuf:"varint,1,req,def=0" json:"MailType,omitempty"`
	// * 标题IDS
	TitleIDS *string `protobuf:"bytes,2,req,def=" json:"TitleIDS,omitempty"`
	// * 正文IDS
	ContentIDS       *string `protobuf:"bytes,3,req,def=" json:"ContentIDS,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MAILMAIN) Reset()         { *m = MAILMAIN{} }
func (m *MAILMAIN) String() string { return proto.CompactTextString(m) }
func (*MAILMAIN) ProtoMessage()    {}

const Default_MAILMAIN_MailType uint32 = 0

func (m *MAILMAIN) GetMailType() uint32 {
	if m != nil && m.MailType != nil {
		return *m.MailType
	}
	return Default_MAILMAIN_MailType
}

func (m *MAILMAIN) GetTitleIDS() string {
	if m != nil && m.TitleIDS != nil {
		return *m.TitleIDS
	}
	return ""
}

func (m *MAILMAIN) GetContentIDS() string {
	if m != nil && m.ContentIDS != nil {
		return *m.ContentIDS
	}
	return ""
}

type MAILMAIN_ARRAY struct {
	Items            []*MAILMAIN `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *MAILMAIN_ARRAY) Reset()         { *m = MAILMAIN_ARRAY{} }
func (m *MAILMAIN_ARRAY) String() string { return proto.CompactTextString(m) }
func (*MAILMAIN_ARRAY) ProtoMessage()    {}

func (m *MAILMAIN_ARRAY) GetItems() []*MAILMAIN {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
