// Code generated by protoc-gen-go.
// source: ProtobufGen_herosoullevel.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HEROSOULLEVEL struct {
	// * 武魂等级
	HeroSoulLevel *uint32 `protobuf:"varint,1,req,def=0" json:"HeroSoulLevel,omitempty"`
	// * 到这一级所需的武将战力值
	HeroSoulValue *uint32 `protobuf:"varint,2,opt,def=0" json:"HeroSoulValue,omitempty"`
	// * 攻击
	ATK *float32 `protobuf:"fixed32,3,opt,def=0" json:"ATK,omitempty"`
	// * 防御
	DEF *float32 `protobuf:"fixed32,4,opt,def=0" json:"DEF,omitempty"`
	// * 生命
	HP               *float32 `protobuf:"fixed32,5,opt,def=0" json:"HP,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HEROSOULLEVEL) Reset()         { *m = HEROSOULLEVEL{} }
func (m *HEROSOULLEVEL) String() string { return proto.CompactTextString(m) }
func (*HEROSOULLEVEL) ProtoMessage()    {}

const Default_HEROSOULLEVEL_HeroSoulLevel uint32 = 0
const Default_HEROSOULLEVEL_HeroSoulValue uint32 = 0
const Default_HEROSOULLEVEL_ATK float32 = 0
const Default_HEROSOULLEVEL_DEF float32 = 0
const Default_HEROSOULLEVEL_HP float32 = 0

func (m *HEROSOULLEVEL) GetHeroSoulLevel() uint32 {
	if m != nil && m.HeroSoulLevel != nil {
		return *m.HeroSoulLevel
	}
	return Default_HEROSOULLEVEL_HeroSoulLevel
}

func (m *HEROSOULLEVEL) GetHeroSoulValue() uint32 {
	if m != nil && m.HeroSoulValue != nil {
		return *m.HeroSoulValue
	}
	return Default_HEROSOULLEVEL_HeroSoulValue
}

func (m *HEROSOULLEVEL) GetATK() float32 {
	if m != nil && m.ATK != nil {
		return *m.ATK
	}
	return Default_HEROSOULLEVEL_ATK
}

func (m *HEROSOULLEVEL) GetDEF() float32 {
	if m != nil && m.DEF != nil {
		return *m.DEF
	}
	return Default_HEROSOULLEVEL_DEF
}

func (m *HEROSOULLEVEL) GetHP() float32 {
	if m != nil && m.HP != nil {
		return *m.HP
	}
	return Default_HEROSOULLEVEL_HP
}

type HEROSOULLEVEL_ARRAY struct {
	Items            []*HEROSOULLEVEL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *HEROSOULLEVEL_ARRAY) Reset()         { *m = HEROSOULLEVEL_ARRAY{} }
func (m *HEROSOULLEVEL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*HEROSOULLEVEL_ARRAY) ProtoMessage()    {}

func (m *HEROSOULLEVEL_ARRAY) GetItems() []*HEROSOULLEVEL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
