// Code generated by protoc-gen-go.
// source: ProtobufGen_refreshcrops.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type REFRESHCROPS struct {
	// * 刷车次数
	RefreshTimes *uint32 `protobuf:"varint,1,req,def=0" json:"RefreshTimes,omitempty"`
	// * 刷新耗钻
	RefreshCost      *uint32              `protobuf:"varint,3,opt,def=0" json:"RefreshCost,omitempty"`
	Fixed_Loot       []*REFRESHCROPS_Loot `protobuf:"bytes,4,rep" json:"Fixed_Loot,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *REFRESHCROPS) Reset()         { *m = REFRESHCROPS{} }
func (m *REFRESHCROPS) String() string { return proto.CompactTextString(m) }
func (*REFRESHCROPS) ProtoMessage()    {}

const Default_REFRESHCROPS_RefreshTimes uint32 = 0
const Default_REFRESHCROPS_RefreshCost uint32 = 0

func (m *REFRESHCROPS) GetRefreshTimes() uint32 {
	if m != nil && m.RefreshTimes != nil {
		return *m.RefreshTimes
	}
	return Default_REFRESHCROPS_RefreshTimes
}

func (m *REFRESHCROPS) GetRefreshCost() uint32 {
	if m != nil && m.RefreshCost != nil {
		return *m.RefreshCost
	}
	return Default_REFRESHCROPS_RefreshCost
}

func (m *REFRESHCROPS) GetFixed_Loot() []*REFRESHCROPS_Loot {
	if m != nil {
		return m.Fixed_Loot
	}
	return nil
}

type REFRESHCROPS_Loot struct {
	// * 刷新的品质
	RefreshQuality *uint32 `protobuf:"varint,1,opt,def=0" json:"RefreshQuality,omitempty"`
	// * 刷新到该品质的概率
	RefreshProbability *float32 `protobuf:"fixed32,2,opt,def=0" json:"RefreshProbability,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *REFRESHCROPS_Loot) Reset()         { *m = REFRESHCROPS_Loot{} }
func (m *REFRESHCROPS_Loot) String() string { return proto.CompactTextString(m) }
func (*REFRESHCROPS_Loot) ProtoMessage()    {}

const Default_REFRESHCROPS_Loot_RefreshQuality uint32 = 0
const Default_REFRESHCROPS_Loot_RefreshProbability float32 = 0

func (m *REFRESHCROPS_Loot) GetRefreshQuality() uint32 {
	if m != nil && m.RefreshQuality != nil {
		return *m.RefreshQuality
	}
	return Default_REFRESHCROPS_Loot_RefreshQuality
}

func (m *REFRESHCROPS_Loot) GetRefreshProbability() float32 {
	if m != nil && m.RefreshProbability != nil {
		return *m.RefreshProbability
	}
	return Default_REFRESHCROPS_Loot_RefreshProbability
}

type REFRESHCROPS_ARRAY struct {
	Items            []*REFRESHCROPS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *REFRESHCROPS_ARRAY) Reset()         { *m = REFRESHCROPS_ARRAY{} }
func (m *REFRESHCROPS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*REFRESHCROPS_ARRAY) ProtoMessage()    {}

func (m *REFRESHCROPS_ARRAY) GetItems() []*REFRESHCROPS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
