// Code generated by protoc-gen-go.
// source: ProtobufGen_tbossenemy.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TBOSSENEMY struct {
	// * 敌兵的ID
	WBossID *string `protobuf:"bytes,1,req,def=" json:"WBossID,omitempty"`
	// * 在副本信息显示的boss介绍
	PanelShowPic *string `protobuf:"bytes,2,opt,def=" json:"PanelShowPic,omitempty"`
	// * boss的类型
	CharacterID *string `protobuf:"bytes,3,opt,def=" json:"CharacterID,omitempty"`
	// * 敌兵的类型
	Type *string `protobuf:"bytes,4,opt,def=" json:"Type,omitempty"`
	// * 克制ID
	Idid *string `protobuf:"bytes,5,opt,def=" json:"Idid,omitempty"`
	// * 敌兵的名字
	NameIDs *string `protobuf:"bytes,6,opt,def=" json:"NameIDs,omitempty"`
	// *
	StageIDs *string `protobuf:"bytes,7,opt,def=" json:"StageIDs,omitempty"`
	// *
	Faction *string `protobuf:"bytes,8,opt,def=" json:"Faction,omitempty"`
	// *
	IsPlayer *uint32 `protobuf:"varint,9,opt,def=0" json:"IsPlayer,omitempty"`
	// *
	Speed *uint32 `protobuf:"varint,10,opt,def=0" json:"Speed,omitempty"`
	// *
	AngleSpeed *uint32 `protobuf:"varint,11,opt,def=0" json:"AngleSpeed,omitempty"`
	// * 生命系数
	HitPointCoefficient *float32 `protobuf:"fixed32,12,opt,def=0" json:"HitPointCoefficient,omitempty"`
	// * 血条数
	HPSectionNum *uint32 `protobuf:"varint,13,opt,def=1" json:"HPSectionNum,omitempty"`
	// * 护甲下限
	ThresholdMin *uint32 `protobuf:"varint,14,opt,def=0" json:"ThresholdMin,omitempty"`
	// * 护甲上限
	ThresholdMax *uint32 `protobuf:"varint,15,opt,def=0" json:"ThresholdMax,omitempty"`
	// * 护盾系数
	ThresholdRatio *uint32 `protobuf:"varint,16,opt,def=0" json:"ThresholdRatio,omitempty"`
	// *
	Guard *uint32 `protobuf:"varint,17,opt,def=0" json:"Guard,omitempty"`
	// * 护盾吸收率
	ShieldAbsorbRate *float32 `protobuf:"fixed32,18,opt,def=0.8" json:"ShieldAbsorbRate,omitempty"`
	// * 攻击系数
	PhysicalDamageCoefficient *float32 `protobuf:"fixed32,19,opt,def=0" json:"PhysicalDamageCoefficient,omitempty"`
	// * 防御系数
	PhysicalResistCoefficient *float32 `protobuf:"fixed32,20,opt,def=0" json:"PhysicalResistCoefficient,omitempty"`
	// *
	CritRate *float32 `protobuf:"fixed32,21,opt,def=0" json:"CritRate,omitempty"`
	// *
	CritDamage *float32 `protobuf:"fixed32,22,opt,def=0" json:"CritDamage,omitempty"`
	// * 闪避率
	DodgeRate *float32 `protobuf:"fixed32,23,opt,def=0" json:"DodgeRate,omitempty"`
	// * 命中率
	HitRate *float32 `protobuf:"fixed32,24,opt,def=0" json:"HitRate,omitempty"`
	// * 无法被黑洞牵引
	CantbeBlackHole *uint32 `protobuf:"varint,25,opt,def=0" json:"CantbeBlackHole,omitempty"`
	// * 无法被击飞、挑起等特殊效果作用
	CantbeSpecialHit *uint32 `protobuf:"varint,26,opt,def=0" json:"CantbeSpecialHit,omitempty"`
	// * 无法被冰冻效果作用
	CantbeFrozen *uint32                `protobuf:"varint,27,opt,def=0" json:"CantbeFrozen,omitempty"`
	Loots        []*TBOSSENEMY_LootRule `protobuf:"bytes,28,rep" json:"Loots,omitempty"`
	// *
	Equip1 *string `protobuf:"bytes,29,opt,def=" json:"Equip1,omitempty"`
	// *
	Equip2 *string `protobuf:"bytes,30,opt,def=" json:"Equip2,omitempty"`
	// * 光环BuffIDs
	Aura             *string `protobuf:"bytes,31,opt,def=" json:"Aura,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TBOSSENEMY) Reset()         { *m = TBOSSENEMY{} }
func (m *TBOSSENEMY) String() string { return proto.CompactTextString(m) }
func (*TBOSSENEMY) ProtoMessage()    {}

const Default_TBOSSENEMY_IsPlayer uint32 = 0
const Default_TBOSSENEMY_Speed uint32 = 0
const Default_TBOSSENEMY_AngleSpeed uint32 = 0
const Default_TBOSSENEMY_HitPointCoefficient float32 = 0
const Default_TBOSSENEMY_HPSectionNum uint32 = 1
const Default_TBOSSENEMY_ThresholdMin uint32 = 0
const Default_TBOSSENEMY_ThresholdMax uint32 = 0
const Default_TBOSSENEMY_ThresholdRatio uint32 = 0
const Default_TBOSSENEMY_Guard uint32 = 0
const Default_TBOSSENEMY_ShieldAbsorbRate float32 = 0.8
const Default_TBOSSENEMY_PhysicalDamageCoefficient float32 = 0
const Default_TBOSSENEMY_PhysicalResistCoefficient float32 = 0
const Default_TBOSSENEMY_CritRate float32 = 0
const Default_TBOSSENEMY_CritDamage float32 = 0
const Default_TBOSSENEMY_DodgeRate float32 = 0
const Default_TBOSSENEMY_HitRate float32 = 0
const Default_TBOSSENEMY_CantbeBlackHole uint32 = 0
const Default_TBOSSENEMY_CantbeSpecialHit uint32 = 0
const Default_TBOSSENEMY_CantbeFrozen uint32 = 0

func (m *TBOSSENEMY) GetWBossID() string {
	if m != nil && m.WBossID != nil {
		return *m.WBossID
	}
	return ""
}

func (m *TBOSSENEMY) GetPanelShowPic() string {
	if m != nil && m.PanelShowPic != nil {
		return *m.PanelShowPic
	}
	return ""
}

func (m *TBOSSENEMY) GetCharacterID() string {
	if m != nil && m.CharacterID != nil {
		return *m.CharacterID
	}
	return ""
}

func (m *TBOSSENEMY) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *TBOSSENEMY) GetIdid() string {
	if m != nil && m.Idid != nil {
		return *m.Idid
	}
	return ""
}

func (m *TBOSSENEMY) GetNameIDs() string {
	if m != nil && m.NameIDs != nil {
		return *m.NameIDs
	}
	return ""
}

func (m *TBOSSENEMY) GetStageIDs() string {
	if m != nil && m.StageIDs != nil {
		return *m.StageIDs
	}
	return ""
}

func (m *TBOSSENEMY) GetFaction() string {
	if m != nil && m.Faction != nil {
		return *m.Faction
	}
	return ""
}

func (m *TBOSSENEMY) GetIsPlayer() uint32 {
	if m != nil && m.IsPlayer != nil {
		return *m.IsPlayer
	}
	return Default_TBOSSENEMY_IsPlayer
}

func (m *TBOSSENEMY) GetSpeed() uint32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return Default_TBOSSENEMY_Speed
}

func (m *TBOSSENEMY) GetAngleSpeed() uint32 {
	if m != nil && m.AngleSpeed != nil {
		return *m.AngleSpeed
	}
	return Default_TBOSSENEMY_AngleSpeed
}

func (m *TBOSSENEMY) GetHitPointCoefficient() float32 {
	if m != nil && m.HitPointCoefficient != nil {
		return *m.HitPointCoefficient
	}
	return Default_TBOSSENEMY_HitPointCoefficient
}

func (m *TBOSSENEMY) GetHPSectionNum() uint32 {
	if m != nil && m.HPSectionNum != nil {
		return *m.HPSectionNum
	}
	return Default_TBOSSENEMY_HPSectionNum
}

func (m *TBOSSENEMY) GetThresholdMin() uint32 {
	if m != nil && m.ThresholdMin != nil {
		return *m.ThresholdMin
	}
	return Default_TBOSSENEMY_ThresholdMin
}

func (m *TBOSSENEMY) GetThresholdMax() uint32 {
	if m != nil && m.ThresholdMax != nil {
		return *m.ThresholdMax
	}
	return Default_TBOSSENEMY_ThresholdMax
}

func (m *TBOSSENEMY) GetThresholdRatio() uint32 {
	if m != nil && m.ThresholdRatio != nil {
		return *m.ThresholdRatio
	}
	return Default_TBOSSENEMY_ThresholdRatio
}

func (m *TBOSSENEMY) GetGuard() uint32 {
	if m != nil && m.Guard != nil {
		return *m.Guard
	}
	return Default_TBOSSENEMY_Guard
}

func (m *TBOSSENEMY) GetShieldAbsorbRate() float32 {
	if m != nil && m.ShieldAbsorbRate != nil {
		return *m.ShieldAbsorbRate
	}
	return Default_TBOSSENEMY_ShieldAbsorbRate
}

func (m *TBOSSENEMY) GetPhysicalDamageCoefficient() float32 {
	if m != nil && m.PhysicalDamageCoefficient != nil {
		return *m.PhysicalDamageCoefficient
	}
	return Default_TBOSSENEMY_PhysicalDamageCoefficient
}

func (m *TBOSSENEMY) GetPhysicalResistCoefficient() float32 {
	if m != nil && m.PhysicalResistCoefficient != nil {
		return *m.PhysicalResistCoefficient
	}
	return Default_TBOSSENEMY_PhysicalResistCoefficient
}

func (m *TBOSSENEMY) GetCritRate() float32 {
	if m != nil && m.CritRate != nil {
		return *m.CritRate
	}
	return Default_TBOSSENEMY_CritRate
}

func (m *TBOSSENEMY) GetCritDamage() float32 {
	if m != nil && m.CritDamage != nil {
		return *m.CritDamage
	}
	return Default_TBOSSENEMY_CritDamage
}

func (m *TBOSSENEMY) GetDodgeRate() float32 {
	if m != nil && m.DodgeRate != nil {
		return *m.DodgeRate
	}
	return Default_TBOSSENEMY_DodgeRate
}

func (m *TBOSSENEMY) GetHitRate() float32 {
	if m != nil && m.HitRate != nil {
		return *m.HitRate
	}
	return Default_TBOSSENEMY_HitRate
}

func (m *TBOSSENEMY) GetCantbeBlackHole() uint32 {
	if m != nil && m.CantbeBlackHole != nil {
		return *m.CantbeBlackHole
	}
	return Default_TBOSSENEMY_CantbeBlackHole
}

func (m *TBOSSENEMY) GetCantbeSpecialHit() uint32 {
	if m != nil && m.CantbeSpecialHit != nil {
		return *m.CantbeSpecialHit
	}
	return Default_TBOSSENEMY_CantbeSpecialHit
}

func (m *TBOSSENEMY) GetCantbeFrozen() uint32 {
	if m != nil && m.CantbeFrozen != nil {
		return *m.CantbeFrozen
	}
	return Default_TBOSSENEMY_CantbeFrozen
}

func (m *TBOSSENEMY) GetLoots() []*TBOSSENEMY_LootRule {
	if m != nil {
		return m.Loots
	}
	return nil
}

func (m *TBOSSENEMY) GetEquip1() string {
	if m != nil && m.Equip1 != nil {
		return *m.Equip1
	}
	return ""
}

func (m *TBOSSENEMY) GetEquip2() string {
	if m != nil && m.Equip2 != nil {
		return *m.Equip2
	}
	return ""
}

func (m *TBOSSENEMY) GetAura() string {
	if m != nil && m.Aura != nil {
		return *m.Aura
	}
	return ""
}

type TBOSSENEMY_LootRule struct {
	// *
	LootTemplate *string `protobuf:"bytes,1,opt,def=" json:"LootTemplate,omitempty"`
	// *
	LootTimes        *uint32 `protobuf:"varint,2,opt,def=0" json:"LootTimes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TBOSSENEMY_LootRule) Reset()         { *m = TBOSSENEMY_LootRule{} }
func (m *TBOSSENEMY_LootRule) String() string { return proto.CompactTextString(m) }
func (*TBOSSENEMY_LootRule) ProtoMessage()    {}

const Default_TBOSSENEMY_LootRule_LootTimes uint32 = 0

func (m *TBOSSENEMY_LootRule) GetLootTemplate() string {
	if m != nil && m.LootTemplate != nil {
		return *m.LootTemplate
	}
	return ""
}

func (m *TBOSSENEMY_LootRule) GetLootTimes() uint32 {
	if m != nil && m.LootTimes != nil {
		return *m.LootTimes
	}
	return Default_TBOSSENEMY_LootRule_LootTimes
}

type TBOSSENEMY_ARRAY struct {
	Items            []*TBOSSENEMY `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *TBOSSENEMY_ARRAY) Reset()         { *m = TBOSSENEMY_ARRAY{} }
func (m *TBOSSENEMY_ARRAY) String() string { return proto.CompactTextString(m) }
func (*TBOSSENEMY_ARRAY) ProtoMessage()    {}

func (m *TBOSSENEMY_ARRAY) GetItems() []*TBOSSENEMY {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
