// Code generated by protoc-gen-go.
// source: ProtobufGen_bossfightpoints.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BOSSFIGHTPOINTS struct {
	// * BOSS对应的ID
	BOSSID *string `protobuf:"bytes,1,req,def=" json:"BOSSID,omitempty"`
	// * BOSS的品质
	Class *uint32 `protobuf:"varint,2,opt,def=1" json:"Class,omitempty"`
	// * BOSS的难度
	Degre *uint32 `protobuf:"varint,3,opt,def=0" json:"Degre,omitempty"`
	// * 积分
	Points *uint32 `protobuf:"varint,4,opt,def=0" json:"Points,omitempty"`
	// * 击杀奖励额外积分
	Killpoints *uint32 `protobuf:"varint,5,opt,def=0" json:"Killpoints,omitempty"`
	// * 权重
	Weight *uint32 `protobuf:"varint,6,opt,def=0" json:"Weight,omitempty"`
	// * BOSS出现的持续时间，单位：秒
	Duration *uint32 `protobuf:"varint,7,opt,def=0" json:"Duration,omitempty"`
	// * 推荐打BOSS的战力
	BOSSGS           *uint32 `protobuf:"varint,8,opt,def=0" json:"BOSSGS,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BOSSFIGHTPOINTS) Reset()         { *m = BOSSFIGHTPOINTS{} }
func (m *BOSSFIGHTPOINTS) String() string { return proto.CompactTextString(m) }
func (*BOSSFIGHTPOINTS) ProtoMessage()    {}

const Default_BOSSFIGHTPOINTS_Class uint32 = 1
const Default_BOSSFIGHTPOINTS_Degre uint32 = 0
const Default_BOSSFIGHTPOINTS_Points uint32 = 0
const Default_BOSSFIGHTPOINTS_Killpoints uint32 = 0
const Default_BOSSFIGHTPOINTS_Weight uint32 = 0
const Default_BOSSFIGHTPOINTS_Duration uint32 = 0
const Default_BOSSFIGHTPOINTS_BOSSGS uint32 = 0

func (m *BOSSFIGHTPOINTS) GetBOSSID() string {
	if m != nil && m.BOSSID != nil {
		return *m.BOSSID
	}
	return ""
}

func (m *BOSSFIGHTPOINTS) GetClass() uint32 {
	if m != nil && m.Class != nil {
		return *m.Class
	}
	return Default_BOSSFIGHTPOINTS_Class
}

func (m *BOSSFIGHTPOINTS) GetDegre() uint32 {
	if m != nil && m.Degre != nil {
		return *m.Degre
	}
	return Default_BOSSFIGHTPOINTS_Degre
}

func (m *BOSSFIGHTPOINTS) GetPoints() uint32 {
	if m != nil && m.Points != nil {
		return *m.Points
	}
	return Default_BOSSFIGHTPOINTS_Points
}

func (m *BOSSFIGHTPOINTS) GetKillpoints() uint32 {
	if m != nil && m.Killpoints != nil {
		return *m.Killpoints
	}
	return Default_BOSSFIGHTPOINTS_Killpoints
}

func (m *BOSSFIGHTPOINTS) GetWeight() uint32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return Default_BOSSFIGHTPOINTS_Weight
}

func (m *BOSSFIGHTPOINTS) GetDuration() uint32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return Default_BOSSFIGHTPOINTS_Duration
}

func (m *BOSSFIGHTPOINTS) GetBOSSGS() uint32 {
	if m != nil && m.BOSSGS != nil {
		return *m.BOSSGS
	}
	return Default_BOSSFIGHTPOINTS_BOSSGS
}

type BOSSFIGHTPOINTS_ARRAY struct {
	Items            []*BOSSFIGHTPOINTS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *BOSSFIGHTPOINTS_ARRAY) Reset()         { *m = BOSSFIGHTPOINTS_ARRAY{} }
func (m *BOSSFIGHTPOINTS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*BOSSFIGHTPOINTS_ARRAY) ProtoMessage()    {}

func (m *BOSSFIGHTPOINTS_ARRAY) GetItems() []*BOSSFIGHTPOINTS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
