// Code generated by protoc-gen-go.
// source: ProtobufGen_guildworshipreward.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GUILDWORSHIPREWARD struct {
	// * 0=下签 1=中签 2=上签
	WorshipDrawID    *uint32                        `protobuf:"varint,1,req,def=0" json:"WorshipDrawID,omitempty"`
	Loot_Table       []*GUILDWORSHIPREWARD_LootRule `protobuf:"bytes,2,rep" json:"Loot_Table,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *GUILDWORSHIPREWARD) Reset()         { *m = GUILDWORSHIPREWARD{} }
func (m *GUILDWORSHIPREWARD) String() string { return proto.CompactTextString(m) }
func (*GUILDWORSHIPREWARD) ProtoMessage()    {}

const Default_GUILDWORSHIPREWARD_WorshipDrawID uint32 = 0

func (m *GUILDWORSHIPREWARD) GetWorshipDrawID() uint32 {
	if m != nil && m.WorshipDrawID != nil {
		return *m.WorshipDrawID
	}
	return Default_GUILDWORSHIPREWARD_WorshipDrawID
}

func (m *GUILDWORSHIPREWARD) GetLoot_Table() []*GUILDWORSHIPREWARD_LootRule {
	if m != nil {
		return m.Loot_Table
	}
	return nil
}

type GUILDWORSHIPREWARD_LootRule struct {
	// * 宝箱奖励
	WorshipBaseReward *string `protobuf:"bytes,1,opt,def=" json:"WorshipBaseReward,omitempty"`
	// * 宝箱奖励数量
	BaseRewardNum    *uint32 `protobuf:"varint,2,opt,def=0" json:"BaseRewardNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GUILDWORSHIPREWARD_LootRule) Reset()         { *m = GUILDWORSHIPREWARD_LootRule{} }
func (m *GUILDWORSHIPREWARD_LootRule) String() string { return proto.CompactTextString(m) }
func (*GUILDWORSHIPREWARD_LootRule) ProtoMessage()    {}

const Default_GUILDWORSHIPREWARD_LootRule_BaseRewardNum uint32 = 0

func (m *GUILDWORSHIPREWARD_LootRule) GetWorshipBaseReward() string {
	if m != nil && m.WorshipBaseReward != nil {
		return *m.WorshipBaseReward
	}
	return ""
}

func (m *GUILDWORSHIPREWARD_LootRule) GetBaseRewardNum() uint32 {
	if m != nil && m.BaseRewardNum != nil {
		return *m.BaseRewardNum
	}
	return Default_GUILDWORSHIPREWARD_LootRule_BaseRewardNum
}

type GUILDWORSHIPREWARD_ARRAY struct {
	Items            []*GUILDWORSHIPREWARD `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GUILDWORSHIPREWARD_ARRAY) Reset()         { *m = GUILDWORSHIPREWARD_ARRAY{} }
func (m *GUILDWORSHIPREWARD_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GUILDWORSHIPREWARD_ARRAY) ProtoMessage()    {}

func (m *GUILDWORSHIPREWARD_ARRAY) GetItems() []*GUILDWORSHIPREWARD {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
