// Code generated by protoc-gen-go.
// source: ProtobufGen_gqrefreshtime.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GQREFRESHTIME struct {
	// * 刷新时间索引
	GQTimeIndex *uint32 `protobuf:"varint,1,req,def=0" json:"GQTimeIndex,omitempty"`
	// * 副将任务刷新时间1
	GQRefreshTime    *string `protobuf:"bytes,2,req,def=" json:"GQRefreshTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GQREFRESHTIME) Reset()         { *m = GQREFRESHTIME{} }
func (m *GQREFRESHTIME) String() string { return proto.CompactTextString(m) }
func (*GQREFRESHTIME) ProtoMessage()    {}

const Default_GQREFRESHTIME_GQTimeIndex uint32 = 0

func (m *GQREFRESHTIME) GetGQTimeIndex() uint32 {
	if m != nil && m.GQTimeIndex != nil {
		return *m.GQTimeIndex
	}
	return Default_GQREFRESHTIME_GQTimeIndex
}

func (m *GQREFRESHTIME) GetGQRefreshTime() string {
	if m != nil && m.GQRefreshTime != nil {
		return *m.GQRefreshTime
	}
	return ""
}

type GQREFRESHTIME_ARRAY struct {
	Items            []*GQREFRESHTIME `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GQREFRESHTIME_ARRAY) Reset()         { *m = GQREFRESHTIME_ARRAY{} }
func (m *GQREFRESHTIME_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GQREFRESHTIME_ARRAY) ProtoMessage()    {}

func (m *GQREFRESHTIME_ARRAY) GetItems() []*GQREFRESHTIME {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
