// Code generated by protoc-gen-go.
// source: ProtobufGen_destinygeneralskill.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DESTINYGENERALSKILL struct {
	// * 神将技能
	GeneralSkill *string `protobuf:"bytes,1,req,def=" json:"GeneralSkill,omitempty"`
	// * 技能名字
	SkillName *string `protobuf:"bytes,2,opt,def=" json:"SkillName,omitempty"`
	// * 技能描述
	SkillDes *string `protobuf:"bytes,3,opt,def=" json:"SkillDes,omitempty"`
	// * 技能图标
	SkillIcon *string `protobuf:"bytes,4,opt,def=" json:"SkillIcon,omitempty"`
	// * 子弹ID
	MissileID *string `protobuf:"bytes,5,opt,def=" json:"MissileID,omitempty"`
	// * 子弹2的ID
	MissileID2 *string `protobuf:"bytes,6,opt,def=" json:"MissileID2,omitempty"`
	// * BUFF效果的ID
	BUFFID *string `protobuf:"bytes,7,opt,def=" json:"BUFFID,omitempty"`
	// * 给buff的延迟时间
	BuffTime *float32 `protobuf:"fixed32,8,opt,def=0" json:"BuffTime,omitempty"`
	// * 技能冷却时间，单位秒
	CDTime *float32 `protobuf:"fixed32,9,opt,def=0" json:"CDTime,omitempty"`
	// * 技能伤害倍率
	DamageScale      *float32 `protobuf:"fixed32,10,opt,def=0" json:"DamageScale,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DESTINYGENERALSKILL) Reset()         { *m = DESTINYGENERALSKILL{} }
func (m *DESTINYGENERALSKILL) String() string { return proto.CompactTextString(m) }
func (*DESTINYGENERALSKILL) ProtoMessage()    {}

const Default_DESTINYGENERALSKILL_BuffTime float32 = 0
const Default_DESTINYGENERALSKILL_CDTime float32 = 0
const Default_DESTINYGENERALSKILL_DamageScale float32 = 0

func (m *DESTINYGENERALSKILL) GetGeneralSkill() string {
	if m != nil && m.GeneralSkill != nil {
		return *m.GeneralSkill
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetSkillName() string {
	if m != nil && m.SkillName != nil {
		return *m.SkillName
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetSkillDes() string {
	if m != nil && m.SkillDes != nil {
		return *m.SkillDes
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetSkillIcon() string {
	if m != nil && m.SkillIcon != nil {
		return *m.SkillIcon
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetMissileID() string {
	if m != nil && m.MissileID != nil {
		return *m.MissileID
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetMissileID2() string {
	if m != nil && m.MissileID2 != nil {
		return *m.MissileID2
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetBUFFID() string {
	if m != nil && m.BUFFID != nil {
		return *m.BUFFID
	}
	return ""
}

func (m *DESTINYGENERALSKILL) GetBuffTime() float32 {
	if m != nil && m.BuffTime != nil {
		return *m.BuffTime
	}
	return Default_DESTINYGENERALSKILL_BuffTime
}

func (m *DESTINYGENERALSKILL) GetCDTime() float32 {
	if m != nil && m.CDTime != nil {
		return *m.CDTime
	}
	return Default_DESTINYGENERALSKILL_CDTime
}

func (m *DESTINYGENERALSKILL) GetDamageScale() float32 {
	if m != nil && m.DamageScale != nil {
		return *m.DamageScale
	}
	return Default_DESTINYGENERALSKILL_DamageScale
}

type DESTINYGENERALSKILL_ARRAY struct {
	Items            []*DESTINYGENERALSKILL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *DESTINYGENERALSKILL_ARRAY) Reset()         { *m = DESTINYGENERALSKILL_ARRAY{} }
func (m *DESTINYGENERALSKILL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*DESTINYGENERALSKILL_ARRAY) ProtoMessage()    {}

func (m *DESTINYGENERALSKILL_ARRAY) GetItems() []*DESTINYGENERALSKILL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
