// Code generated by protoc-gen-go.
// source: ProtobufGen_gveenemygroup.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GVEENEMYGROUP struct {
	// * 玩家等级下限
	LevelMin *uint32 `protobuf:"varint,1,req,def=0" json:"LevelMin,omitempty"`
	// * 玩家等级上限
	LevelMax *uint32 `protobuf:"varint,2,opt,def=0" json:"LevelMax,omitempty"`
	// * 关卡ID
	EGLevelID *string `protobuf:"bytes,3,opt,def=" json:"EGLevelID,omitempty"`
	// * 随机BOSS1
	Boss1 *uint32 `protobuf:"varint,4,opt,def=0" json:"Boss1,omitempty"`
	// * 随机BOSS2
	Boss2 *uint32 `protobuf:"varint,5,opt,def=0" json:"Boss2,omitempty"`
	// * 随机BOSS3
	Boss3 *uint32 `protobuf:"varint,6,opt,def=0" json:"Boss3,omitempty"`
	// * 困难boss1
	HardBoss1 *uint32 `protobuf:"varint,7,opt,def=0" json:"HardBoss1,omitempty"`
	// * 困难boss2
	HardBoss2 *uint32 `protobuf:"varint,8,opt,def=0" json:"HardBoss2,omitempty"`
	// * 困难boss3
	HardBoss3        *uint32 `protobuf:"varint,9,opt,def=0" json:"HardBoss3,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GVEENEMYGROUP) Reset()         { *m = GVEENEMYGROUP{} }
func (m *GVEENEMYGROUP) String() string { return proto.CompactTextString(m) }
func (*GVEENEMYGROUP) ProtoMessage()    {}

const Default_GVEENEMYGROUP_LevelMin uint32 = 0
const Default_GVEENEMYGROUP_LevelMax uint32 = 0
const Default_GVEENEMYGROUP_Boss1 uint32 = 0
const Default_GVEENEMYGROUP_Boss2 uint32 = 0
const Default_GVEENEMYGROUP_Boss3 uint32 = 0
const Default_GVEENEMYGROUP_HardBoss1 uint32 = 0
const Default_GVEENEMYGROUP_HardBoss2 uint32 = 0
const Default_GVEENEMYGROUP_HardBoss3 uint32 = 0

func (m *GVEENEMYGROUP) GetLevelMin() uint32 {
	if m != nil && m.LevelMin != nil {
		return *m.LevelMin
	}
	return Default_GVEENEMYGROUP_LevelMin
}

func (m *GVEENEMYGROUP) GetLevelMax() uint32 {
	if m != nil && m.LevelMax != nil {
		return *m.LevelMax
	}
	return Default_GVEENEMYGROUP_LevelMax
}

func (m *GVEENEMYGROUP) GetEGLevelID() string {
	if m != nil && m.EGLevelID != nil {
		return *m.EGLevelID
	}
	return ""
}

func (m *GVEENEMYGROUP) GetBoss1() uint32 {
	if m != nil && m.Boss1 != nil {
		return *m.Boss1
	}
	return Default_GVEENEMYGROUP_Boss1
}

func (m *GVEENEMYGROUP) GetBoss2() uint32 {
	if m != nil && m.Boss2 != nil {
		return *m.Boss2
	}
	return Default_GVEENEMYGROUP_Boss2
}

func (m *GVEENEMYGROUP) GetBoss3() uint32 {
	if m != nil && m.Boss3 != nil {
		return *m.Boss3
	}
	return Default_GVEENEMYGROUP_Boss3
}

func (m *GVEENEMYGROUP) GetHardBoss1() uint32 {
	if m != nil && m.HardBoss1 != nil {
		return *m.HardBoss1
	}
	return Default_GVEENEMYGROUP_HardBoss1
}

func (m *GVEENEMYGROUP) GetHardBoss2() uint32 {
	if m != nil && m.HardBoss2 != nil {
		return *m.HardBoss2
	}
	return Default_GVEENEMYGROUP_HardBoss2
}

func (m *GVEENEMYGROUP) GetHardBoss3() uint32 {
	if m != nil && m.HardBoss3 != nil {
		return *m.HardBoss3
	}
	return Default_GVEENEMYGROUP_HardBoss3
}

type GVEENEMYGROUP_ARRAY struct {
	Items            []*GVEENEMYGROUP `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GVEENEMYGROUP_ARRAY) Reset()         { *m = GVEENEMYGROUP_ARRAY{} }
func (m *GVEENEMYGROUP_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GVEENEMYGROUP_ARRAY) ProtoMessage()    {}

func (m *GVEENEMYGROUP_ARRAY) GetItems() []*GVEENEMYGROUP {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
