// Code generated by protoc-gen-go.
// source: ProtobufGen_dialogue_trigger.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DIALOGUE_TRIGGER struct {
	// * 触发事件ID
	ID *string `protobuf:"bytes,1,req,def=" json:"ID,omitempty"`
	// * 事件类型
	Type *string `protobuf:"bytes,2,opt,def=" json:"Type,omitempty"`
	// * 触发对话ID
	DialogueID *string `protobuf:"bytes,3,opt,name=dialogueID,def=" json:"dialogueID,omitempty"`
	// * 事件完成之后触发的事件
	AfterTrigger *string `protobuf:"bytes,4,opt,def=" json:"AfterTrigger,omitempty"`
	// * 默认字符串参数1
	ParamSP1 *string `protobuf:"bytes,5,opt,name=paramSP1,def=" json:"paramSP1,omitempty"`
	// * 默认数值参数1
	ParamIP1 *uint32 `protobuf:"varint,6,opt,name=paramIP1,def=0" json:"paramIP1,omitempty"`
	// * 默认字符串参数2
	ParamSP2 *string `protobuf:"bytes,7,opt,name=paramSP2,def=" json:"paramSP2,omitempty"`
	// * 默认数值参数2
	ParamIP2         *uint32 `protobuf:"varint,8,opt,name=paramIP2,def=0" json:"paramIP2,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DIALOGUE_TRIGGER) Reset()         { *m = DIALOGUE_TRIGGER{} }
func (m *DIALOGUE_TRIGGER) String() string { return proto.CompactTextString(m) }
func (*DIALOGUE_TRIGGER) ProtoMessage()    {}

const Default_DIALOGUE_TRIGGER_ParamIP1 uint32 = 0
const Default_DIALOGUE_TRIGGER_ParamIP2 uint32 = 0

func (m *DIALOGUE_TRIGGER) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *DIALOGUE_TRIGGER) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *DIALOGUE_TRIGGER) GetDialogueID() string {
	if m != nil && m.DialogueID != nil {
		return *m.DialogueID
	}
	return ""
}

func (m *DIALOGUE_TRIGGER) GetAfterTrigger() string {
	if m != nil && m.AfterTrigger != nil {
		return *m.AfterTrigger
	}
	return ""
}

func (m *DIALOGUE_TRIGGER) GetParamSP1() string {
	if m != nil && m.ParamSP1 != nil {
		return *m.ParamSP1
	}
	return ""
}

func (m *DIALOGUE_TRIGGER) GetParamIP1() uint32 {
	if m != nil && m.ParamIP1 != nil {
		return *m.ParamIP1
	}
	return Default_DIALOGUE_TRIGGER_ParamIP1
}

func (m *DIALOGUE_TRIGGER) GetParamSP2() string {
	if m != nil && m.ParamSP2 != nil {
		return *m.ParamSP2
	}
	return ""
}

func (m *DIALOGUE_TRIGGER) GetParamIP2() uint32 {
	if m != nil && m.ParamIP2 != nil {
		return *m.ParamIP2
	}
	return Default_DIALOGUE_TRIGGER_ParamIP2
}

type DIALOGUE_TRIGGER_ARRAY struct {
	Items            []*DIALOGUE_TRIGGER `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *DIALOGUE_TRIGGER_ARRAY) Reset()         { *m = DIALOGUE_TRIGGER_ARRAY{} }
func (m *DIALOGUE_TRIGGER_ARRAY) String() string { return proto.CompactTextString(m) }
func (*DIALOGUE_TRIGGER_ARRAY) ProtoMessage()    {}

func (m *DIALOGUE_TRIGGER_ARRAY) GetItems() []*DIALOGUE_TRIGGER {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
