// Code generated by protoc-gen-go.
// source: ProtobufGen_wheelsettings.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type WHEELSETTINGS struct {
	// * 活动ID
	ActivityID *uint32 `protobuf:"varint,1,opt,def=0" json:"ActivityID,omitempty"`
	// * 消耗代币道具ID
	GachaCoin *string `protobuf:"bytes,2,opt,def=" json:"GachaCoin,omitempty"`
	// * 充值基数（钻石）
	HCBase *uint32 `protobuf:"varint,4,opt,def=0" json:"HCBase,omitempty"`
	// * 赠送积分币数量
	GetCoinItem *uint32 `protobuf:"varint,5,opt,def=0" json:"GetCoinItem,omitempty"`
	// * 可获得积分币上限
	GetCoinItemMax *uint32 `protobuf:"varint,6,opt,def=0" json:"GetCoinItemMax,omitempty"`
	// * 常规组ID
	ItemGroupID *uint32 `protobuf:"varint,9,opt,def=0" json:"ItemGroupID,omitempty"`
	// * 碎片品质（此品质之上的走跑马灯）
	MsgQuality *uint32 `protobuf:"varint,11,req,def=0" json:"MsgQuality,omitempty"`
	// * 跑马灯IDS
	MsgIDS           *uint32 `protobuf:"varint,12,opt,def=0" json:"MsgIDS,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WHEELSETTINGS) Reset()         { *m = WHEELSETTINGS{} }
func (m *WHEELSETTINGS) String() string { return proto.CompactTextString(m) }
func (*WHEELSETTINGS) ProtoMessage()    {}

const Default_WHEELSETTINGS_ActivityID uint32 = 0
const Default_WHEELSETTINGS_HCBase uint32 = 0
const Default_WHEELSETTINGS_GetCoinItem uint32 = 0
const Default_WHEELSETTINGS_GetCoinItemMax uint32 = 0
const Default_WHEELSETTINGS_ItemGroupID uint32 = 0
const Default_WHEELSETTINGS_MsgQuality uint32 = 0
const Default_WHEELSETTINGS_MsgIDS uint32 = 0

func (m *WHEELSETTINGS) GetActivityID() uint32 {
	if m != nil && m.ActivityID != nil {
		return *m.ActivityID
	}
	return Default_WHEELSETTINGS_ActivityID
}

func (m *WHEELSETTINGS) GetGachaCoin() string {
	if m != nil && m.GachaCoin != nil {
		return *m.GachaCoin
	}
	return ""
}

func (m *WHEELSETTINGS) GetHCBase() uint32 {
	if m != nil && m.HCBase != nil {
		return *m.HCBase
	}
	return Default_WHEELSETTINGS_HCBase
}

func (m *WHEELSETTINGS) GetGetCoinItem() uint32 {
	if m != nil && m.GetCoinItem != nil {
		return *m.GetCoinItem
	}
	return Default_WHEELSETTINGS_GetCoinItem
}

func (m *WHEELSETTINGS) GetGetCoinItemMax() uint32 {
	if m != nil && m.GetCoinItemMax != nil {
		return *m.GetCoinItemMax
	}
	return Default_WHEELSETTINGS_GetCoinItemMax
}

func (m *WHEELSETTINGS) GetItemGroupID() uint32 {
	if m != nil && m.ItemGroupID != nil {
		return *m.ItemGroupID
	}
	return Default_WHEELSETTINGS_ItemGroupID
}

func (m *WHEELSETTINGS) GetMsgQuality() uint32 {
	if m != nil && m.MsgQuality != nil {
		return *m.MsgQuality
	}
	return Default_WHEELSETTINGS_MsgQuality
}

func (m *WHEELSETTINGS) GetMsgIDS() uint32 {
	if m != nil && m.MsgIDS != nil {
		return *m.MsgIDS
	}
	return Default_WHEELSETTINGS_MsgIDS
}

type WHEELSETTINGS_ARRAY struct {
	Items            []*WHEELSETTINGS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *WHEELSETTINGS_ARRAY) Reset()         { *m = WHEELSETTINGS_ARRAY{} }
func (m *WHEELSETTINGS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*WHEELSETTINGS_ARRAY) ProtoMessage()    {}

func (m *WHEELSETTINGS_ARRAY) GetItems() []*WHEELSETTINGS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
