// Code generated by protoc-gen-go.
// source: ProtobufGen_fbmodel.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FBMODEL struct {
	// * 玩家等级
	PlayLevel *uint32 `protobuf:"varint,1,req,def=0" json:"PlayLevel,omitempty"`
	// * 标准生命值
	HitPoint *uint32 `protobuf:"varint,2,opt,def=0" json:"HitPoint,omitempty"`
	// * 标准伤害
	PhysicalDamage *uint32 `protobuf:"varint,3,opt,def=0" json:"PhysicalDamage,omitempty"`
	// * 标准防御
	PhysicalResist   *uint32 `protobuf:"varint,4,opt,def=0" json:"PhysicalResist,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FBMODEL) Reset()         { *m = FBMODEL{} }
func (m *FBMODEL) String() string { return proto.CompactTextString(m) }
func (*FBMODEL) ProtoMessage()    {}

const Default_FBMODEL_PlayLevel uint32 = 0
const Default_FBMODEL_HitPoint uint32 = 0
const Default_FBMODEL_PhysicalDamage uint32 = 0
const Default_FBMODEL_PhysicalResist uint32 = 0

func (m *FBMODEL) GetPlayLevel() uint32 {
	if m != nil && m.PlayLevel != nil {
		return *m.PlayLevel
	}
	return Default_FBMODEL_PlayLevel
}

func (m *FBMODEL) GetHitPoint() uint32 {
	if m != nil && m.HitPoint != nil {
		return *m.HitPoint
	}
	return Default_FBMODEL_HitPoint
}

func (m *FBMODEL) GetPhysicalDamage() uint32 {
	if m != nil && m.PhysicalDamage != nil {
		return *m.PhysicalDamage
	}
	return Default_FBMODEL_PhysicalDamage
}

func (m *FBMODEL) GetPhysicalResist() uint32 {
	if m != nil && m.PhysicalResist != nil {
		return *m.PhysicalResist
	}
	return Default_FBMODEL_PhysicalResist
}

type FBMODEL_ARRAY struct {
	Items            []*FBMODEL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *FBMODEL_ARRAY) Reset()         { *m = FBMODEL_ARRAY{} }
func (m *FBMODEL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*FBMODEL_ARRAY) ProtoMessage()    {}

func (m *FBMODEL_ARRAY) GetItems() []*FBMODEL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
