// Code generated by protoc-gen-go.
// source: ProtobufGen_iapconfig.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type IAPCONFIG struct {
	// * 返还现金钻石比
	CTDrate *uint32 `protobuf:"varint,1,req,def=10" json:"CTDrate,omitempty"`
	// * 返还现金福利
	CTDbonus         *float32 `protobuf:"fixed32,2,req,def=0.1" json:"CTDbonus,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IAPCONFIG) Reset()         { *m = IAPCONFIG{} }
func (m *IAPCONFIG) String() string { return proto.CompactTextString(m) }
func (*IAPCONFIG) ProtoMessage()    {}

const Default_IAPCONFIG_CTDrate uint32 = 10
const Default_IAPCONFIG_CTDbonus float32 = 0.1

func (m *IAPCONFIG) GetCTDrate() uint32 {
	if m != nil && m.CTDrate != nil {
		return *m.CTDrate
	}
	return Default_IAPCONFIG_CTDrate
}

func (m *IAPCONFIG) GetCTDbonus() float32 {
	if m != nil && m.CTDbonus != nil {
		return *m.CTDbonus
	}
	return Default_IAPCONFIG_CTDbonus
}

type IAPCONFIG_ARRAY struct {
	Items            []*IAPCONFIG `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *IAPCONFIG_ARRAY) Reset()         { *m = IAPCONFIG_ARRAY{} }
func (m *IAPCONFIG_ARRAY) String() string { return proto.CompactTextString(m) }
func (*IAPCONFIG_ARRAY) ProtoMessage()    {}

func (m *IAPCONFIG_ARRAY) GetItems() []*IAPCONFIG {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
