// Code generated by protoc-gen-go.
// source: ProtobufGen_attributesgs.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ATTRIBUTESGS struct {
	// * 生命值
	HPRadio *float32 `protobuf:"fixed32,1,req,def=0" json:"HPRadio,omitempty"`
	// * 攻击力
	ATKRadio *float32 `protobuf:"fixed32,2,req,def=0" json:"ATKRadio,omitempty"`
	// * 防御力
	DEFRadio *float32 `protobuf:"fixed32,3,req,def=0" json:"DEFRadio,omitempty"`
	// * 暴击率
	CritRateRadio *float32 `protobuf:"fixed32,4,req,def=0" json:"CritRateRadio,omitempty"`
	// * 免暴率
	ResilienceRateRadio *float32 `protobuf:"fixed32,5,req,def=0" json:"ResilienceRateRadio,omitempty"`
	// * 暴击伤害
	CritValueRadio *float32 `protobuf:"fixed32,6,req,def=0" json:"CritValueRadio,omitempty"`
	// * 免暴伤害
	ResilienceValueRadio *float32 `protobuf:"fixed32,7,req,def=0" json:"ResilienceValueRadio,omitempty"`
	// * 闪避率
	DodgeRateRadio *float32 `protobuf:"fixed32,24,req,def=0" json:"DodgeRateRadio,omitempty"`
	// * 命中率
	HitRateRadio *float32 `protobuf:"fixed32,25,req,def=0" json:"HitRateRadio,omitempty"`
	// * 冰系攻击力
	IceDamageRadio *float32 `protobuf:"fixed32,8,req,def=0" json:"IceDamageRadio,omitempty"`
	// * 冰系防御力
	IceDefenseRadio *float32 `protobuf:"fixed32,9,req,def=0" json:"IceDefenseRadio,omitempty"`
	// * 冰系伤害加成
	IceBonusRadio *float32 `protobuf:"fixed32,10,req,def=0" json:"IceBonusRadio,omitempty"`
	// * 冰系抗性
	IceResistRadio *float32 `protobuf:"fixed32,11,req,def=0" json:"IceResistRadio,omitempty"`
	// * 火系攻击力
	FireDamageRadio *float32 `protobuf:"fixed32,12,req,def=0" json:"FireDamageRadio,omitempty"`
	// * 火系防御力
	FireDefenseRadio *float32 `protobuf:"fixed32,13,req,def=0" json:"FireDefenseRadio,omitempty"`
	// * 火系伤害加成
	FireBonusRadio *float32 `protobuf:"fixed32,14,req,def=0" json:"FireBonusRadio,omitempty"`
	// * 火系抗性
	FireResistRadio *float32 `protobuf:"fixed32,15,req,def=0" json:"FireResistRadio,omitempty"`
	// * 雷系攻击力
	LightingDamageRadio *float32 `protobuf:"fixed32,16,req,def=0" json:"LightingDamageRadio,omitempty"`
	// * 雷系防御力
	LightingDefenseRadio *float32 `protobuf:"fixed32,17,req,def=0" json:"LightingDefenseRadio,omitempty"`
	// * 雷系伤害加成
	LightingBonusRadio *float32 `protobuf:"fixed32,18,req,def=0" json:"LightingBonusRadio,omitempty"`
	// * 雷系抗性
	LightingResistRadio *float32 `protobuf:"fixed32,19,req,def=0" json:"LightingResistRadio,omitempty"`
	// * 毒系攻击力
	PoisonDamageRadio *float32 `protobuf:"fixed32,20,req,def=0" json:"PoisonDamageRadio,omitempty"`
	// * 毒系防御力
	PoisonDefenseRadio *float32 `protobuf:"fixed32,21,req,def=0" json:"PoisonDefenseRadio,omitempty"`
	// * 毒系伤害加成
	PoisonBonusRadio *float32 `protobuf:"fixed32,22,req,def=0" json:"PoisonBonusRadio,omitempty"`
	// * 毒系抗性
	PoisonResistRadio *float32 `protobuf:"fixed32,23,req,def=0" json:"PoisonResistRadio,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *ATTRIBUTESGS) Reset()         { *m = ATTRIBUTESGS{} }
func (m *ATTRIBUTESGS) String() string { return proto.CompactTextString(m) }
func (*ATTRIBUTESGS) ProtoMessage()    {}

const Default_ATTRIBUTESGS_HPRadio float32 = 0
const Default_ATTRIBUTESGS_ATKRadio float32 = 0
const Default_ATTRIBUTESGS_DEFRadio float32 = 0
const Default_ATTRIBUTESGS_CritRateRadio float32 = 0
const Default_ATTRIBUTESGS_ResilienceRateRadio float32 = 0
const Default_ATTRIBUTESGS_CritValueRadio float32 = 0
const Default_ATTRIBUTESGS_ResilienceValueRadio float32 = 0
const Default_ATTRIBUTESGS_DodgeRateRadio float32 = 0
const Default_ATTRIBUTESGS_HitRateRadio float32 = 0
const Default_ATTRIBUTESGS_IceDamageRadio float32 = 0
const Default_ATTRIBUTESGS_IceDefenseRadio float32 = 0
const Default_ATTRIBUTESGS_IceBonusRadio float32 = 0
const Default_ATTRIBUTESGS_IceResistRadio float32 = 0
const Default_ATTRIBUTESGS_FireDamageRadio float32 = 0
const Default_ATTRIBUTESGS_FireDefenseRadio float32 = 0
const Default_ATTRIBUTESGS_FireBonusRadio float32 = 0
const Default_ATTRIBUTESGS_FireResistRadio float32 = 0
const Default_ATTRIBUTESGS_LightingDamageRadio float32 = 0
const Default_ATTRIBUTESGS_LightingDefenseRadio float32 = 0
const Default_ATTRIBUTESGS_LightingBonusRadio float32 = 0
const Default_ATTRIBUTESGS_LightingResistRadio float32 = 0
const Default_ATTRIBUTESGS_PoisonDamageRadio float32 = 0
const Default_ATTRIBUTESGS_PoisonDefenseRadio float32 = 0
const Default_ATTRIBUTESGS_PoisonBonusRadio float32 = 0
const Default_ATTRIBUTESGS_PoisonResistRadio float32 = 0

func (m *ATTRIBUTESGS) GetHPRadio() float32 {
	if m != nil && m.HPRadio != nil {
		return *m.HPRadio
	}
	return Default_ATTRIBUTESGS_HPRadio
}

func (m *ATTRIBUTESGS) GetATKRadio() float32 {
	if m != nil && m.ATKRadio != nil {
		return *m.ATKRadio
	}
	return Default_ATTRIBUTESGS_ATKRadio
}

func (m *ATTRIBUTESGS) GetDEFRadio() float32 {
	if m != nil && m.DEFRadio != nil {
		return *m.DEFRadio
	}
	return Default_ATTRIBUTESGS_DEFRadio
}

func (m *ATTRIBUTESGS) GetCritRateRadio() float32 {
	if m != nil && m.CritRateRadio != nil {
		return *m.CritRateRadio
	}
	return Default_ATTRIBUTESGS_CritRateRadio
}

func (m *ATTRIBUTESGS) GetResilienceRateRadio() float32 {
	if m != nil && m.ResilienceRateRadio != nil {
		return *m.ResilienceRateRadio
	}
	return Default_ATTRIBUTESGS_ResilienceRateRadio
}

func (m *ATTRIBUTESGS) GetCritValueRadio() float32 {
	if m != nil && m.CritValueRadio != nil {
		return *m.CritValueRadio
	}
	return Default_ATTRIBUTESGS_CritValueRadio
}

func (m *ATTRIBUTESGS) GetResilienceValueRadio() float32 {
	if m != nil && m.ResilienceValueRadio != nil {
		return *m.ResilienceValueRadio
	}
	return Default_ATTRIBUTESGS_ResilienceValueRadio
}

func (m *ATTRIBUTESGS) GetDodgeRateRadio() float32 {
	if m != nil && m.DodgeRateRadio != nil {
		return *m.DodgeRateRadio
	}
	return Default_ATTRIBUTESGS_DodgeRateRadio
}

func (m *ATTRIBUTESGS) GetHitRateRadio() float32 {
	if m != nil && m.HitRateRadio != nil {
		return *m.HitRateRadio
	}
	return Default_ATTRIBUTESGS_HitRateRadio
}

func (m *ATTRIBUTESGS) GetIceDamageRadio() float32 {
	if m != nil && m.IceDamageRadio != nil {
		return *m.IceDamageRadio
	}
	return Default_ATTRIBUTESGS_IceDamageRadio
}

func (m *ATTRIBUTESGS) GetIceDefenseRadio() float32 {
	if m != nil && m.IceDefenseRadio != nil {
		return *m.IceDefenseRadio
	}
	return Default_ATTRIBUTESGS_IceDefenseRadio
}

func (m *ATTRIBUTESGS) GetIceBonusRadio() float32 {
	if m != nil && m.IceBonusRadio != nil {
		return *m.IceBonusRadio
	}
	return Default_ATTRIBUTESGS_IceBonusRadio
}

func (m *ATTRIBUTESGS) GetIceResistRadio() float32 {
	if m != nil && m.IceResistRadio != nil {
		return *m.IceResistRadio
	}
	return Default_ATTRIBUTESGS_IceResistRadio
}

func (m *ATTRIBUTESGS) GetFireDamageRadio() float32 {
	if m != nil && m.FireDamageRadio != nil {
		return *m.FireDamageRadio
	}
	return Default_ATTRIBUTESGS_FireDamageRadio
}

func (m *ATTRIBUTESGS) GetFireDefenseRadio() float32 {
	if m != nil && m.FireDefenseRadio != nil {
		return *m.FireDefenseRadio
	}
	return Default_ATTRIBUTESGS_FireDefenseRadio
}

func (m *ATTRIBUTESGS) GetFireBonusRadio() float32 {
	if m != nil && m.FireBonusRadio != nil {
		return *m.FireBonusRadio
	}
	return Default_ATTRIBUTESGS_FireBonusRadio
}

func (m *ATTRIBUTESGS) GetFireResistRadio() float32 {
	if m != nil && m.FireResistRadio != nil {
		return *m.FireResistRadio
	}
	return Default_ATTRIBUTESGS_FireResistRadio
}

func (m *ATTRIBUTESGS) GetLightingDamageRadio() float32 {
	if m != nil && m.LightingDamageRadio != nil {
		return *m.LightingDamageRadio
	}
	return Default_ATTRIBUTESGS_LightingDamageRadio
}

func (m *ATTRIBUTESGS) GetLightingDefenseRadio() float32 {
	if m != nil && m.LightingDefenseRadio != nil {
		return *m.LightingDefenseRadio
	}
	return Default_ATTRIBUTESGS_LightingDefenseRadio
}

func (m *ATTRIBUTESGS) GetLightingBonusRadio() float32 {
	if m != nil && m.LightingBonusRadio != nil {
		return *m.LightingBonusRadio
	}
	return Default_ATTRIBUTESGS_LightingBonusRadio
}

func (m *ATTRIBUTESGS) GetLightingResistRadio() float32 {
	if m != nil && m.LightingResistRadio != nil {
		return *m.LightingResistRadio
	}
	return Default_ATTRIBUTESGS_LightingResistRadio
}

func (m *ATTRIBUTESGS) GetPoisonDamageRadio() float32 {
	if m != nil && m.PoisonDamageRadio != nil {
		return *m.PoisonDamageRadio
	}
	return Default_ATTRIBUTESGS_PoisonDamageRadio
}

func (m *ATTRIBUTESGS) GetPoisonDefenseRadio() float32 {
	if m != nil && m.PoisonDefenseRadio != nil {
		return *m.PoisonDefenseRadio
	}
	return Default_ATTRIBUTESGS_PoisonDefenseRadio
}

func (m *ATTRIBUTESGS) GetPoisonBonusRadio() float32 {
	if m != nil && m.PoisonBonusRadio != nil {
		return *m.PoisonBonusRadio
	}
	return Default_ATTRIBUTESGS_PoisonBonusRadio
}

func (m *ATTRIBUTESGS) GetPoisonResistRadio() float32 {
	if m != nil && m.PoisonResistRadio != nil {
		return *m.PoisonResistRadio
	}
	return Default_ATTRIBUTESGS_PoisonResistRadio
}

type ATTRIBUTESGS_ARRAY struct {
	Items            []*ATTRIBUTESGS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ATTRIBUTESGS_ARRAY) Reset()         { *m = ATTRIBUTESGS_ARRAY{} }
func (m *ATTRIBUTESGS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*ATTRIBUTESGS_ARRAY) ProtoMessage()    {}

func (m *ATTRIBUTESGS_ARRAY) GetItems() []*ATTRIBUTESGS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
