// Code generated by protoc-gen-go.
// source: ProtobufGen_sprintpurchase.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SPRINTPURCHASE struct {
	// * 精力购买次数
	SprintPurchaseTime *uint32 `protobuf:"varint,1,req,def=0" json:"SprintPurchaseTime,omitempty"`
	// * HC消耗
	SprintEnergyPrice *uint32 `protobuf:"varint,2,req,def=0" json:"SprintEnergyPrice,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *SPRINTPURCHASE) Reset()         { *m = SPRINTPURCHASE{} }
func (m *SPRINTPURCHASE) String() string { return proto.CompactTextString(m) }
func (*SPRINTPURCHASE) ProtoMessage()    {}

const Default_SPRINTPURCHASE_SprintPurchaseTime uint32 = 0
const Default_SPRINTPURCHASE_SprintEnergyPrice uint32 = 0

func (m *SPRINTPURCHASE) GetSprintPurchaseTime() uint32 {
	if m != nil && m.SprintPurchaseTime != nil {
		return *m.SprintPurchaseTime
	}
	return Default_SPRINTPURCHASE_SprintPurchaseTime
}

func (m *SPRINTPURCHASE) GetSprintEnergyPrice() uint32 {
	if m != nil && m.SprintEnergyPrice != nil {
		return *m.SprintEnergyPrice
	}
	return Default_SPRINTPURCHASE_SprintEnergyPrice
}

type SPRINTPURCHASE_ARRAY struct {
	Items            []*SPRINTPURCHASE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *SPRINTPURCHASE_ARRAY) Reset()         { *m = SPRINTPURCHASE_ARRAY{} }
func (m *SPRINTPURCHASE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*SPRINTPURCHASE_ARRAY) ProtoMessage()    {}

func (m *SPRINTPURCHASE_ARRAY) GetItems() []*SPRINTPURCHASE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
