// Code generated by protoc-gen-go.
// source: ProtobufGen_herowinglist.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HEROWINGLIST struct {
	// * 主将ID
	HeroID           *uint32                `protobuf:"varint,1,req,def=0" json:"HeroID,omitempty"`
	HWList_Template  []*HEROWINGLIST_HWList `protobuf:"bytes,2,rep" json:"HWList_Template,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *HEROWINGLIST) Reset()         { *m = HEROWINGLIST{} }
func (m *HEROWINGLIST) String() string { return proto.CompactTextString(m) }
func (*HEROWINGLIST) ProtoMessage()    {}

const Default_HEROWINGLIST_HeroID uint32 = 0

func (m *HEROWINGLIST) GetHeroID() uint32 {
	if m != nil && m.HeroID != nil {
		return *m.HeroID
	}
	return Default_HEROWINGLIST_HeroID
}

func (m *HEROWINGLIST) GetHWList_Template() []*HEROWINGLIST_HWList {
	if m != nil {
		return m.HWList_Template
	}
	return nil
}

type HEROWINGLIST_HWList struct {
	// * 翅膀ID
	HWID             *uint32 `protobuf:"varint,1,opt,def=0" json:"HWID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HEROWINGLIST_HWList) Reset()         { *m = HEROWINGLIST_HWList{} }
func (m *HEROWINGLIST_HWList) String() string { return proto.CompactTextString(m) }
func (*HEROWINGLIST_HWList) ProtoMessage()    {}

const Default_HEROWINGLIST_HWList_HWID uint32 = 0

func (m *HEROWINGLIST_HWList) GetHWID() uint32 {
	if m != nil && m.HWID != nil {
		return *m.HWID
	}
	return Default_HEROWINGLIST_HWList_HWID
}

type HEROWINGLIST_ARRAY struct {
	Items            []*HEROWINGLIST `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *HEROWINGLIST_ARRAY) Reset()         { *m = HEROWINGLIST_ARRAY{} }
func (m *HEROWINGLIST_ARRAY) String() string { return proto.CompactTextString(m) }
func (*HEROWINGLIST_ARRAY) ProtoMessage()    {}

func (m *HEROWINGLIST_ARRAY) GetItems() []*HEROWINGLIST {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
