// Code generated by protoc-gen-go.
// source: ProtobufGen_bscpvpstaticbot.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BSCPVPSTATICBOT struct {
	// * 机器人ID
	StaticBotID *uint32 `protobuf:"varint,1,req,def=0" json:"StaticBotID,omitempty"`
	// * 角色id
	AID *uint32 `protobuf:"varint,2,req,def=0" json:"AID,omitempty"`
	// * 战队等级
	CLv *uint32 `protobuf:"varint,3,req,def=0" json:"CLv,omitempty"`
	// * 等级分
	RankingScore *uint32 `protobuf:"varint,4,req,def=0" json:"RankingScore,omitempty"`
	// * 攻击
	ATK *uint32 `protobuf:"varint,5,req,def=0" json:"ATK,omitempty"`
	// * 防御
	DEF *uint32 `protobuf:"varint,6,req,def=0" json:"DEF,omitempty"`
	// * 生命
	HP               *uint32 `protobuf:"varint,7,req,def=0" json:"HP,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BSCPVPSTATICBOT) Reset()         { *m = BSCPVPSTATICBOT{} }
func (m *BSCPVPSTATICBOT) String() string { return proto.CompactTextString(m) }
func (*BSCPVPSTATICBOT) ProtoMessage()    {}

const Default_BSCPVPSTATICBOT_StaticBotID uint32 = 0
const Default_BSCPVPSTATICBOT_AID uint32 = 0
const Default_BSCPVPSTATICBOT_CLv uint32 = 0
const Default_BSCPVPSTATICBOT_RankingScore uint32 = 0
const Default_BSCPVPSTATICBOT_ATK uint32 = 0
const Default_BSCPVPSTATICBOT_DEF uint32 = 0
const Default_BSCPVPSTATICBOT_HP uint32 = 0

func (m *BSCPVPSTATICBOT) GetStaticBotID() uint32 {
	if m != nil && m.StaticBotID != nil {
		return *m.StaticBotID
	}
	return Default_BSCPVPSTATICBOT_StaticBotID
}

func (m *BSCPVPSTATICBOT) GetAID() uint32 {
	if m != nil && m.AID != nil {
		return *m.AID
	}
	return Default_BSCPVPSTATICBOT_AID
}

func (m *BSCPVPSTATICBOT) GetCLv() uint32 {
	if m != nil && m.CLv != nil {
		return *m.CLv
	}
	return Default_BSCPVPSTATICBOT_CLv
}

func (m *BSCPVPSTATICBOT) GetRankingScore() uint32 {
	if m != nil && m.RankingScore != nil {
		return *m.RankingScore
	}
	return Default_BSCPVPSTATICBOT_RankingScore
}

func (m *BSCPVPSTATICBOT) GetATK() uint32 {
	if m != nil && m.ATK != nil {
		return *m.ATK
	}
	return Default_BSCPVPSTATICBOT_ATK
}

func (m *BSCPVPSTATICBOT) GetDEF() uint32 {
	if m != nil && m.DEF != nil {
		return *m.DEF
	}
	return Default_BSCPVPSTATICBOT_DEF
}

func (m *BSCPVPSTATICBOT) GetHP() uint32 {
	if m != nil && m.HP != nil {
		return *m.HP
	}
	return Default_BSCPVPSTATICBOT_HP
}

type BSCPVPSTATICBOT_ARRAY struct {
	Items            []*BSCPVPSTATICBOT `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *BSCPVPSTATICBOT_ARRAY) Reset()         { *m = BSCPVPSTATICBOT_ARRAY{} }
func (m *BSCPVPSTATICBOT_ARRAY) String() string { return proto.CompactTextString(m) }
func (*BSCPVPSTATICBOT_ARRAY) ProtoMessage()    {}

func (m *BSCPVPSTATICBOT_ARRAY) GetItems() []*BSCPVPSTATICBOT {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
