// Code generated by protoc-gen-go.
// source: ProtobufGen_gvgpointgift.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GVGPOINTGIFT struct {
	// * id
	ID *uint32 `protobuf:"varint,1,req,def=0" json:"ID,omitempty"`
	// * 积分下
	GVGPoint1 *uint32 `protobuf:"varint,2,opt,def=0" json:"GVGPoint1,omitempty"`
	// * 积分上
	GVGPoint2        *uint32                  `protobuf:"varint,3,opt,def=0" json:"GVGPoint2,omitempty"`
	Loot_Table       []*GVGPOINTGIFT_LootRule `protobuf:"bytes,4,rep" json:"Loot_Table,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *GVGPOINTGIFT) Reset()         { *m = GVGPOINTGIFT{} }
func (m *GVGPOINTGIFT) String() string { return proto.CompactTextString(m) }
func (*GVGPOINTGIFT) ProtoMessage()    {}

const Default_GVGPOINTGIFT_ID uint32 = 0
const Default_GVGPOINTGIFT_GVGPoint1 uint32 = 0
const Default_GVGPOINTGIFT_GVGPoint2 uint32 = 0

func (m *GVGPOINTGIFT) GetID() uint32 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return Default_GVGPOINTGIFT_ID
}

func (m *GVGPOINTGIFT) GetGVGPoint1() uint32 {
	if m != nil && m.GVGPoint1 != nil {
		return *m.GVGPoint1
	}
	return Default_GVGPOINTGIFT_GVGPoint1
}

func (m *GVGPOINTGIFT) GetGVGPoint2() uint32 {
	if m != nil && m.GVGPoint2 != nil {
		return *m.GVGPoint2
	}
	return Default_GVGPOINTGIFT_GVGPoint2
}

func (m *GVGPOINTGIFT) GetLoot_Table() []*GVGPOINTGIFT_LootRule {
	if m != nil {
		return m.Loot_Table
	}
	return nil
}

type GVGPOINTGIFT_LootRule struct {
	// * 奖励1
	ItemID *string `protobuf:"bytes,1,opt,def=" json:"ItemID,omitempty"`
	// * 数量1
	ItemNum          *uint32 `protobuf:"varint,2,opt,def=0" json:"ItemNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GVGPOINTGIFT_LootRule) Reset()         { *m = GVGPOINTGIFT_LootRule{} }
func (m *GVGPOINTGIFT_LootRule) String() string { return proto.CompactTextString(m) }
func (*GVGPOINTGIFT_LootRule) ProtoMessage()    {}

const Default_GVGPOINTGIFT_LootRule_ItemNum uint32 = 0

func (m *GVGPOINTGIFT_LootRule) GetItemID() string {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return ""
}

func (m *GVGPOINTGIFT_LootRule) GetItemNum() uint32 {
	if m != nil && m.ItemNum != nil {
		return *m.ItemNum
	}
	return Default_GVGPOINTGIFT_LootRule_ItemNum
}

type GVGPOINTGIFT_ARRAY struct {
	Items            []*GVGPOINTGIFT `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *GVGPOINTGIFT_ARRAY) Reset()         { *m = GVGPOINTGIFT_ARRAY{} }
func (m *GVGPOINTGIFT_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GVGPOINTGIFT_ARRAY) ProtoMessage()    {}

func (m *GVGPOINTGIFT_ARRAY) GetItems() []*GVGPOINTGIFT {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
