// Code generated by protoc-gen-go.
// source: ProtobufGen_gemodel.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GEMODEL struct {
	// * 玩家等级
	PlayLevel *string `protobuf:"bytes,1,req,def=" json:"PlayLevel,omitempty"`
	// * 标准生命值
	HitPoint *uint32 `protobuf:"varint,2,opt,def=0" json:"HitPoint,omitempty"`
	// * 标准伤害
	PhysicalDamage *uint32 `protobuf:"varint,3,opt,def=0" json:"PhysicalDamage,omitempty"`
	// * 标准防御
	PhysicalResist   *uint32 `protobuf:"varint,4,opt,def=0" json:"PhysicalResist,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GEMODEL) Reset()         { *m = GEMODEL{} }
func (m *GEMODEL) String() string { return proto.CompactTextString(m) }
func (*GEMODEL) ProtoMessage()    {}

const Default_GEMODEL_HitPoint uint32 = 0
const Default_GEMODEL_PhysicalDamage uint32 = 0
const Default_GEMODEL_PhysicalResist uint32 = 0

func (m *GEMODEL) GetPlayLevel() string {
	if m != nil && m.PlayLevel != nil {
		return *m.PlayLevel
	}
	return ""
}

func (m *GEMODEL) GetHitPoint() uint32 {
	if m != nil && m.HitPoint != nil {
		return *m.HitPoint
	}
	return Default_GEMODEL_HitPoint
}

func (m *GEMODEL) GetPhysicalDamage() uint32 {
	if m != nil && m.PhysicalDamage != nil {
		return *m.PhysicalDamage
	}
	return Default_GEMODEL_PhysicalDamage
}

func (m *GEMODEL) GetPhysicalResist() uint32 {
	if m != nil && m.PhysicalResist != nil {
		return *m.PhysicalResist
	}
	return Default_GEMODEL_PhysicalResist
}

type GEMODEL_ARRAY struct {
	Items            []*GEMODEL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GEMODEL_ARRAY) Reset()         { *m = GEMODEL_ARRAY{} }
func (m *GEMODEL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GEMODEL_ARRAY) ProtoMessage()    {}

func (m *GEMODEL_ARRAY) GetItems() []*GEMODEL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
