// Code generated by protoc-gen-go.
// source: ProtobufGen_loadingtip.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LOADINGTIP struct {
	// * 主键key
	TipsID *int32 `protobuf:"varint,4,req,def=0" json:"TipsID,omitempty"`
	// * 解锁等级
	UnlockLv *int32 `protobuf:"varint,1,req,def=0" json:"UnlockLv,omitempty"`
	// * 权值
	Weight *int32 `protobuf:"varint,2,req,def=0" json:"Weight,omitempty"`
	// * 文本IDS
	IDS              *string `protobuf:"bytes,3,opt,def=" json:"IDS,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LOADINGTIP) Reset()         { *m = LOADINGTIP{} }
func (m *LOADINGTIP) String() string { return proto.CompactTextString(m) }
func (*LOADINGTIP) ProtoMessage()    {}

const Default_LOADINGTIP_TipsID int32 = 0
const Default_LOADINGTIP_UnlockLv int32 = 0
const Default_LOADINGTIP_Weight int32 = 0

func (m *LOADINGTIP) GetTipsID() int32 {
	if m != nil && m.TipsID != nil {
		return *m.TipsID
	}
	return Default_LOADINGTIP_TipsID
}

func (m *LOADINGTIP) GetUnlockLv() int32 {
	if m != nil && m.UnlockLv != nil {
		return *m.UnlockLv
	}
	return Default_LOADINGTIP_UnlockLv
}

func (m *LOADINGTIP) GetWeight() int32 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return Default_LOADINGTIP_Weight
}

func (m *LOADINGTIP) GetIDS() string {
	if m != nil && m.IDS != nil {
		return *m.IDS
	}
	return ""
}

type LOADINGTIP_ARRAY struct {
	Items            []*LOADINGTIP `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *LOADINGTIP_ARRAY) Reset()         { *m = LOADINGTIP_ARRAY{} }
func (m *LOADINGTIP_ARRAY) String() string { return proto.CompactTextString(m) }
func (*LOADINGTIP_ARRAY) ProtoMessage()    {}

func (m *LOADINGTIP_ARRAY) GetItems() []*LOADINGTIP {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
