// Code generated by protoc-gen-go.
// source: ProtobufGen_ftedialogue.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FTEDIALOGUE struct {
	// * 对话的位置
	ID *string `protobuf:"bytes,1,req,def=" json:"ID,omitempty"`
	// * 对话的内容
	Content *string `protobuf:"bytes,2,opt,def=" json:"Content,omitempty"`
	// * 是否弹解锁动画
	Unlock *string `protobuf:"bytes,3,opt,def=" json:"Unlock,omitempty"`
	// * 是否屏蔽解锁步骤
	IgnoreSteps      *string `protobuf:"bytes,4,opt,def=" json:"IgnoreSteps,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FTEDIALOGUE) Reset()         { *m = FTEDIALOGUE{} }
func (m *FTEDIALOGUE) String() string { return proto.CompactTextString(m) }
func (*FTEDIALOGUE) ProtoMessage()    {}

func (m *FTEDIALOGUE) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *FTEDIALOGUE) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *FTEDIALOGUE) GetUnlock() string {
	if m != nil && m.Unlock != nil {
		return *m.Unlock
	}
	return ""
}

func (m *FTEDIALOGUE) GetIgnoreSteps() string {
	if m != nil && m.IgnoreSteps != nil {
		return *m.IgnoreSteps
	}
	return ""
}

type FTEDIALOGUE_ARRAY struct {
	Items            []*FTEDIALOGUE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *FTEDIALOGUE_ARRAY) Reset()         { *m = FTEDIALOGUE_ARRAY{} }
func (m *FTEDIALOGUE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*FTEDIALOGUE_ARRAY) ProtoMessage()    {}

func (m *FTEDIALOGUE_ARRAY) GetItems() []*FTEDIALOGUE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
