// Code generated by protoc-gen-go.
// source: ProtobufGen_skillratio.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SKILLRATIO struct {
	// * 角色等级
	SkillLevel *uint32 `protobuf:"varint,1,req,def=0" json:"SkillLevel,omitempty"`
	// * 技能伤害倍率
	DamageScale *float32 `protobuf:"fixed32,2,opt,def=0" json:"DamageScale,omitempty"`
	// * 技能附加伤害
	ExtraDamage      *uint32 `protobuf:"varint,3,opt,def=0" json:"ExtraDamage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SKILLRATIO) Reset()         { *m = SKILLRATIO{} }
func (m *SKILLRATIO) String() string { return proto.CompactTextString(m) }
func (*SKILLRATIO) ProtoMessage()    {}

const Default_SKILLRATIO_SkillLevel uint32 = 0
const Default_SKILLRATIO_DamageScale float32 = 0
const Default_SKILLRATIO_ExtraDamage uint32 = 0

func (m *SKILLRATIO) GetSkillLevel() uint32 {
	if m != nil && m.SkillLevel != nil {
		return *m.SkillLevel
	}
	return Default_SKILLRATIO_SkillLevel
}

func (m *SKILLRATIO) GetDamageScale() float32 {
	if m != nil && m.DamageScale != nil {
		return *m.DamageScale
	}
	return Default_SKILLRATIO_DamageScale
}

func (m *SKILLRATIO) GetExtraDamage() uint32 {
	if m != nil && m.ExtraDamage != nil {
		return *m.ExtraDamage
	}
	return Default_SKILLRATIO_ExtraDamage
}

type SKILLRATIO_ARRAY struct {
	Items            []*SKILLRATIO `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SKILLRATIO_ARRAY) Reset()         { *m = SKILLRATIO_ARRAY{} }
func (m *SKILLRATIO_ARRAY) String() string { return proto.CompactTextString(m) }
func (*SKILLRATIO_ARRAY) ProtoMessage()    {}

func (m *SKILLRATIO_ARRAY) GetItems() []*SKILLRATIO {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
