// Code generated by protoc-gen-go.
// source: ProtobufGen_herowingtable.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HEROWINGTABLE struct {
	// * 翅膀ID
	HWID *uint32 `protobuf:"varint,1,req,def=0" json:"HWID,omitempty"`
	// * 特效ID
	HWEffects *string `protobuf:"bytes,2,opt,def=" json:"HWEffects,omitempty"`
	// * 翅膀图标
	HWIcon *string `protobuf:"bytes,7,opt,def=" json:"HWIcon,omitempty"`
	// * 翅膀品质
	HWRare *uint32 `protobuf:"varint,8,opt,def=0" json:"HWRare,omitempty"`
	// * 解锁类型
	HWUnlockType *uint32 `protobuf:"varint,3,opt,def=0" json:"HWUnlockType,omitempty"`
	// * 解锁星级限制
	HWUnlockStar *uint32 `protobuf:"varint,4,opt,def=0" json:"HWUnlockStar,omitempty"`
	// * 解锁所需的材料
	HWUnlockMaterial *string `protobuf:"bytes,5,opt,def=" json:"HWUnlockMaterial,omitempty"`
	// * 解锁所需的材料数量
	HWUnlockCount    *uint32 `protobuf:"varint,6,opt,def=1" json:"HWUnlockCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HEROWINGTABLE) Reset()         { *m = HEROWINGTABLE{} }
func (m *HEROWINGTABLE) String() string { return proto.CompactTextString(m) }
func (*HEROWINGTABLE) ProtoMessage()    {}

const Default_HEROWINGTABLE_HWID uint32 = 0
const Default_HEROWINGTABLE_HWRare uint32 = 0
const Default_HEROWINGTABLE_HWUnlockType uint32 = 0
const Default_HEROWINGTABLE_HWUnlockStar uint32 = 0
const Default_HEROWINGTABLE_HWUnlockCount uint32 = 1

func (m *HEROWINGTABLE) GetHWID() uint32 {
	if m != nil && m.HWID != nil {
		return *m.HWID
	}
	return Default_HEROWINGTABLE_HWID
}

func (m *HEROWINGTABLE) GetHWEffects() string {
	if m != nil && m.HWEffects != nil {
		return *m.HWEffects
	}
	return ""
}

func (m *HEROWINGTABLE) GetHWIcon() string {
	if m != nil && m.HWIcon != nil {
		return *m.HWIcon
	}
	return ""
}

func (m *HEROWINGTABLE) GetHWRare() uint32 {
	if m != nil && m.HWRare != nil {
		return *m.HWRare
	}
	return Default_HEROWINGTABLE_HWRare
}

func (m *HEROWINGTABLE) GetHWUnlockType() uint32 {
	if m != nil && m.HWUnlockType != nil {
		return *m.HWUnlockType
	}
	return Default_HEROWINGTABLE_HWUnlockType
}

func (m *HEROWINGTABLE) GetHWUnlockStar() uint32 {
	if m != nil && m.HWUnlockStar != nil {
		return *m.HWUnlockStar
	}
	return Default_HEROWINGTABLE_HWUnlockStar
}

func (m *HEROWINGTABLE) GetHWUnlockMaterial() string {
	if m != nil && m.HWUnlockMaterial != nil {
		return *m.HWUnlockMaterial
	}
	return ""
}

func (m *HEROWINGTABLE) GetHWUnlockCount() uint32 {
	if m != nil && m.HWUnlockCount != nil {
		return *m.HWUnlockCount
	}
	return Default_HEROWINGTABLE_HWUnlockCount
}

type HEROWINGTABLE_ARRAY struct {
	Items            []*HEROWINGTABLE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *HEROWINGTABLE_ARRAY) Reset()         { *m = HEROWINGTABLE_ARRAY{} }
func (m *HEROWINGTABLE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*HEROWINGTABLE_ARRAY) ProtoMessage()    {}

func (m *HEROWINGTABLE_ARRAY) GetItems() []*HEROWINGTABLE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
