// Code generated by protoc-gen-go.
// source: ProtobufGen_cdtgifttimingone.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CDTGIFTTIMINGONE struct {
	// * 表索引
	Index *uint32 `protobuf:"varint,1,req,def=0" json:"Index,omitempty"`
	// * 活动ID
	ActivityID *uint32 `protobuf:"varint,2,req,def=0" json:"ActivityID,omitempty"`
	// * 完成条件类型
	FCType *uint32 `protobuf:"varint,3,opt,def=0" json:"FCType,omitempty"`
	// * 完成条件数值参数
	FCValue *uint32 `protobuf:"varint,4,opt,def=1" json:"FCValue,omitempty"`
	// * 条目描述
	Desc               *string                       `protobuf:"bytes,5,opt,def=" json:"Desc,omitempty"`
	GoalAward_Template []*CDTGIFTTIMINGONE_GoalAward `protobuf:"bytes,6,rep" json:"GoalAward_Template,omitempty"`
	XXX_unrecognized   []byte                        `json:"-"`
}

func (m *CDTGIFTTIMINGONE) Reset()         { *m = CDTGIFTTIMINGONE{} }
func (m *CDTGIFTTIMINGONE) String() string { return proto.CompactTextString(m) }
func (*CDTGIFTTIMINGONE) ProtoMessage()    {}

const Default_CDTGIFTTIMINGONE_Index uint32 = 0
const Default_CDTGIFTTIMINGONE_ActivityID uint32 = 0
const Default_CDTGIFTTIMINGONE_FCType uint32 = 0
const Default_CDTGIFTTIMINGONE_FCValue uint32 = 1

func (m *CDTGIFTTIMINGONE) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_CDTGIFTTIMINGONE_Index
}

func (m *CDTGIFTTIMINGONE) GetActivityID() uint32 {
	if m != nil && m.ActivityID != nil {
		return *m.ActivityID
	}
	return Default_CDTGIFTTIMINGONE_ActivityID
}

func (m *CDTGIFTTIMINGONE) GetFCType() uint32 {
	if m != nil && m.FCType != nil {
		return *m.FCType
	}
	return Default_CDTGIFTTIMINGONE_FCType
}

func (m *CDTGIFTTIMINGONE) GetFCValue() uint32 {
	if m != nil && m.FCValue != nil {
		return *m.FCValue
	}
	return Default_CDTGIFTTIMINGONE_FCValue
}

func (m *CDTGIFTTIMINGONE) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *CDTGIFTTIMINGONE) GetGoalAward_Template() []*CDTGIFTTIMINGONE_GoalAward {
	if m != nil {
		return m.GoalAward_Template
	}
	return nil
}

type CDTGIFTTIMINGONE_GoalAward struct {
	// * 奖励ID
	Reward *string `protobuf:"bytes,1,opt,def=" json:"Reward,omitempty"`
	// * 奖励数目
	Count            *uint32 `protobuf:"varint,2,opt,def=0" json:"Count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDTGIFTTIMINGONE_GoalAward) Reset()         { *m = CDTGIFTTIMINGONE_GoalAward{} }
func (m *CDTGIFTTIMINGONE_GoalAward) String() string { return proto.CompactTextString(m) }
func (*CDTGIFTTIMINGONE_GoalAward) ProtoMessage()    {}

const Default_CDTGIFTTIMINGONE_GoalAward_Count uint32 = 0

func (m *CDTGIFTTIMINGONE_GoalAward) GetReward() string {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return ""
}

func (m *CDTGIFTTIMINGONE_GoalAward) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_CDTGIFTTIMINGONE_GoalAward_Count
}

type CDTGIFTTIMINGONE_ARRAY struct {
	Items            []*CDTGIFTTIMINGONE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *CDTGIFTTIMINGONE_ARRAY) Reset()         { *m = CDTGIFTTIMINGONE_ARRAY{} }
func (m *CDTGIFTTIMINGONE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*CDTGIFTTIMINGONE_ARRAY) ProtoMessage()    {}

func (m *CDTGIFTTIMINGONE_ARRAY) GetItems() []*CDTGIFTTIMINGONE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
