// Code generated by protoc-gen-go.
// source: ProtobufGen_noncompulsoryfte.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type NONCOMPULSORYFTE struct {
	// * 引导的ID
	ID *string `protobuf:"bytes,1,req,def=" json:"ID,omitempty"`
	// * 引导的条件
	Conditions *string `protobuf:"bytes,2,opt,def=" json:"Conditions,omitempty"`
	// * 引导条件的参数
	ConditionParameters *string `protobuf:"bytes,3,opt,def=" json:"ConditionParameters,omitempty"`
	// * 引导的按钮
	PushButton *string `protobuf:"bytes,4,opt,def=" json:"PushButton,omitempty"`
	// * 解释的文字
	Explain *string `protobuf:"bytes,5,opt,def=" json:"Explain,omitempty"`
	// * 解释文字框的位置
	Position *string `protobuf:"bytes,6,opt,def=" json:"Position,omitempty"`
	// * 引导后的行为
	Actions *string `protobuf:"bytes,7,opt,def=" json:"Actions,omitempty"`
	// * 引导后行为的参数
	ActionParameters *string `protobuf:"bytes,8,opt,def=" json:"ActionParameters,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NONCOMPULSORYFTE) Reset()         { *m = NONCOMPULSORYFTE{} }
func (m *NONCOMPULSORYFTE) String() string { return proto.CompactTextString(m) }
func (*NONCOMPULSORYFTE) ProtoMessage()    {}

func (m *NONCOMPULSORYFTE) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetConditions() string {
	if m != nil && m.Conditions != nil {
		return *m.Conditions
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetConditionParameters() string {
	if m != nil && m.ConditionParameters != nil {
		return *m.ConditionParameters
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetPushButton() string {
	if m != nil && m.PushButton != nil {
		return *m.PushButton
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetExplain() string {
	if m != nil && m.Explain != nil {
		return *m.Explain
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetPosition() string {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetActions() string {
	if m != nil && m.Actions != nil {
		return *m.Actions
	}
	return ""
}

func (m *NONCOMPULSORYFTE) GetActionParameters() string {
	if m != nil && m.ActionParameters != nil {
		return *m.ActionParameters
	}
	return ""
}

type NONCOMPULSORYFTE_ARRAY struct {
	Items            []*NONCOMPULSORYFTE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *NONCOMPULSORYFTE_ARRAY) Reset()         { *m = NONCOMPULSORYFTE_ARRAY{} }
func (m *NONCOMPULSORYFTE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*NONCOMPULSORYFTE_ARRAY) ProtoMessage()    {}

func (m *NONCOMPULSORYFTE_ARRAY) GetItems() []*NONCOMPULSORYFTE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
