// Code generated by protoc-gen-go.
// source: ProtobufGen_equipresolve.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type EQUIPRESOLVE struct {
	// * Tier_Rare
	EResolveIndex *string `protobuf:"bytes,1,req,def=" json:"EResolveIndex,omitempty"`
	// * 精铁值
	FineIron *uint32 `protobuf:"varint,2,opt,def=0" json:"FineIron,omitempty"`
	// * 额外材料
	ExtraMaterial *string `protobuf:"bytes,3,opt,def=" json:"ExtraMaterial,omitempty"`
	// * 材料数量
	Count            *uint32 `protobuf:"varint,4,opt,def=1" json:"Count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EQUIPRESOLVE) Reset()         { *m = EQUIPRESOLVE{} }
func (m *EQUIPRESOLVE) String() string { return proto.CompactTextString(m) }
func (*EQUIPRESOLVE) ProtoMessage()    {}

const Default_EQUIPRESOLVE_FineIron uint32 = 0
const Default_EQUIPRESOLVE_Count uint32 = 1

func (m *EQUIPRESOLVE) GetEResolveIndex() string {
	if m != nil && m.EResolveIndex != nil {
		return *m.EResolveIndex
	}
	return ""
}

func (m *EQUIPRESOLVE) GetFineIron() uint32 {
	if m != nil && m.FineIron != nil {
		return *m.FineIron
	}
	return Default_EQUIPRESOLVE_FineIron
}

func (m *EQUIPRESOLVE) GetExtraMaterial() string {
	if m != nil && m.ExtraMaterial != nil {
		return *m.ExtraMaterial
	}
	return ""
}

func (m *EQUIPRESOLVE) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_EQUIPRESOLVE_Count
}

type EQUIPRESOLVE_ARRAY struct {
	Items            []*EQUIPRESOLVE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *EQUIPRESOLVE_ARRAY) Reset()         { *m = EQUIPRESOLVE_ARRAY{} }
func (m *EQUIPRESOLVE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*EQUIPRESOLVE_ARRAY) ProtoMessage()    {}

func (m *EQUIPRESOLVE_ARRAY) GetItems() []*EQUIPRESOLVE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
