// Code generated by protoc-gen-go.
// source: ProtobufGen_mainnpc.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MAINNPC struct {
	// * 主角NPC排序ID
	MainNPC *uint32 `protobuf:"varint,1,req,def=0" json:"MainNPC,omitempty"`
	// * 出现条件
	ConditionType *uint32 `protobuf:"varint,2,req,def=0" json:"ConditionType,omitempty"`
	// * 参数1
	ConditionValue *string `protobuf:"bytes,3,opt,def=" json:"ConditionValue,omitempty"`
	// * 参数2
	ConditionValue2 *uint32 `protobuf:"varint,4,opt,def=0" json:"ConditionValue2,omitempty"`
	// * npc子件名
	HeroID *string `protobuf:"bytes,5,opt,def=" json:"HeroID,omitempty"`
	// * 解锁提示条件
	ConditionIDS     *string `protobuf:"bytes,6,opt,def=" json:"ConditionIDS,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MAINNPC) Reset()         { *m = MAINNPC{} }
func (m *MAINNPC) String() string { return proto.CompactTextString(m) }
func (*MAINNPC) ProtoMessage()    {}

const Default_MAINNPC_MainNPC uint32 = 0
const Default_MAINNPC_ConditionType uint32 = 0
const Default_MAINNPC_ConditionValue2 uint32 = 0

func (m *MAINNPC) GetMainNPC() uint32 {
	if m != nil && m.MainNPC != nil {
		return *m.MainNPC
	}
	return Default_MAINNPC_MainNPC
}

func (m *MAINNPC) GetConditionType() uint32 {
	if m != nil && m.ConditionType != nil {
		return *m.ConditionType
	}
	return Default_MAINNPC_ConditionType
}

func (m *MAINNPC) GetConditionValue() string {
	if m != nil && m.ConditionValue != nil {
		return *m.ConditionValue
	}
	return ""
}

func (m *MAINNPC) GetConditionValue2() uint32 {
	if m != nil && m.ConditionValue2 != nil {
		return *m.ConditionValue2
	}
	return Default_MAINNPC_ConditionValue2
}

func (m *MAINNPC) GetHeroID() string {
	if m != nil && m.HeroID != nil {
		return *m.HeroID
	}
	return ""
}

func (m *MAINNPC) GetConditionIDS() string {
	if m != nil && m.ConditionIDS != nil {
		return *m.ConditionIDS
	}
	return ""
}

type MAINNPC_ARRAY struct {
	Items            []*MAINNPC `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MAINNPC_ARRAY) Reset()         { *m = MAINNPC_ARRAY{} }
func (m *MAINNPC_ARRAY) String() string { return proto.CompactTextString(m) }
func (*MAINNPC_ARRAY) ProtoMessage()    {}

func (m *MAINNPC_ARRAY) GetItems() []*MAINNPC {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
