// Code generated by protoc-gen-go.
// source: ProtobufGen_eatbaozi.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type EATBAOZI struct {
	// * 玩法ID
	ModeID *uint32 `protobuf:"varint,1,req,def=0" json:"ModeID,omitempty"`
	// * 获得物品ID
	ItemID *string `protobuf:"bytes,2,opt,def=" json:"ItemID,omitempty"`
	// * 保底物品数量
	Number *uint32 `protobuf:"varint,3,opt,def=0" json:"Number,omitempty"`
	// * 奖励上限数量
	Total *uint32 `protobuf:"varint,4,opt,def=0" json:"Total,omitempty"`
	// * 开启一键扫等级
	LevelOpen        *uint32 `protobuf:"varint,5,opt,def=0" json:"LevelOpen,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EATBAOZI) Reset()         { *m = EATBAOZI{} }
func (m *EATBAOZI) String() string { return proto.CompactTextString(m) }
func (*EATBAOZI) ProtoMessage()    {}

const Default_EATBAOZI_ModeID uint32 = 0
const Default_EATBAOZI_Number uint32 = 0
const Default_EATBAOZI_Total uint32 = 0
const Default_EATBAOZI_LevelOpen uint32 = 0

func (m *EATBAOZI) GetModeID() uint32 {
	if m != nil && m.ModeID != nil {
		return *m.ModeID
	}
	return Default_EATBAOZI_ModeID
}

func (m *EATBAOZI) GetItemID() string {
	if m != nil && m.ItemID != nil {
		return *m.ItemID
	}
	return ""
}

func (m *EATBAOZI) GetNumber() uint32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return Default_EATBAOZI_Number
}

func (m *EATBAOZI) GetTotal() uint32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return Default_EATBAOZI_Total
}

func (m *EATBAOZI) GetLevelOpen() uint32 {
	if m != nil && m.LevelOpen != nil {
		return *m.LevelOpen
	}
	return Default_EATBAOZI_LevelOpen
}

type EATBAOZI_ARRAY struct {
	Items            []*EATBAOZI `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *EATBAOZI_ARRAY) Reset()         { *m = EATBAOZI_ARRAY{} }
func (m *EATBAOZI_ARRAY) String() string { return proto.CompactTextString(m) }
func (*EATBAOZI_ARRAY) ProtoMessage()    {}

func (m *EATBAOZI_ARRAY) GetItems() []*EATBAOZI {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
