// Code generated by protoc-gen-go.
// source: ProtobufGen_chapteraward.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type CHAPTERAWARD struct {
	// * 章节ID
	ChapterID *string `protobuf:"bytes,1,req,def=" json:"ChapterID,omitempty"`
	// * 章节星数总值
	TotalGoal *uint32 `protobuf:"varint,2,opt,def=0" json:"TotalGoal,omitempty"`
	// * 目标星级
	Goal               *uint32                   `protobuf:"varint,3,opt,def=0" json:"Goal,omitempty"`
	GoalAward_Template []*CHAPTERAWARD_GoalAward `protobuf:"bytes,4,rep" json:"GoalAward_Template,omitempty"`
	XXX_unrecognized   []byte                    `json:"-"`
}

func (m *CHAPTERAWARD) Reset()         { *m = CHAPTERAWARD{} }
func (m *CHAPTERAWARD) String() string { return proto.CompactTextString(m) }
func (*CHAPTERAWARD) ProtoMessage()    {}

const Default_CHAPTERAWARD_TotalGoal uint32 = 0
const Default_CHAPTERAWARD_Goal uint32 = 0

func (m *CHAPTERAWARD) GetChapterID() string {
	if m != nil && m.ChapterID != nil {
		return *m.ChapterID
	}
	return ""
}

func (m *CHAPTERAWARD) GetTotalGoal() uint32 {
	if m != nil && m.TotalGoal != nil {
		return *m.TotalGoal
	}
	return Default_CHAPTERAWARD_TotalGoal
}

func (m *CHAPTERAWARD) GetGoal() uint32 {
	if m != nil && m.Goal != nil {
		return *m.Goal
	}
	return Default_CHAPTERAWARD_Goal
}

func (m *CHAPTERAWARD) GetGoalAward_Template() []*CHAPTERAWARD_GoalAward {
	if m != nil {
		return m.GoalAward_Template
	}
	return nil
}

type CHAPTERAWARD_GoalAward struct {
	// * 奖励ID
	Reward *string `protobuf:"bytes,1,opt,def=" json:"Reward,omitempty"`
	// * 奖励数目
	Count            *uint32 `protobuf:"varint,2,opt,def=0" json:"Count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CHAPTERAWARD_GoalAward) Reset()         { *m = CHAPTERAWARD_GoalAward{} }
func (m *CHAPTERAWARD_GoalAward) String() string { return proto.CompactTextString(m) }
func (*CHAPTERAWARD_GoalAward) ProtoMessage()    {}

const Default_CHAPTERAWARD_GoalAward_Count uint32 = 0

func (m *CHAPTERAWARD_GoalAward) GetReward() string {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return ""
}

func (m *CHAPTERAWARD_GoalAward) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_CHAPTERAWARD_GoalAward_Count
}

type CHAPTERAWARD_ARRAY struct {
	Items            []*CHAPTERAWARD `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *CHAPTERAWARD_ARRAY) Reset()         { *m = CHAPTERAWARD_ARRAY{} }
func (m *CHAPTERAWARD_ARRAY) String() string { return proto.CompactTextString(m) }
func (*CHAPTERAWARD_ARRAY) ProtoMessage()    {}

func (m *CHAPTERAWARD_ARRAY) GetItems() []*CHAPTERAWARD {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
