// Code generated by protoc-gen-go.
// source: ProtobufGen_levelattributes.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type LEVELATTRIBUTES struct {
	// * 等级
	Level *int32 `protobuf:"varint,1,req,def=0" json:"Level,omitempty"`
	// * 经验
	XP *int32 `protobuf:"varint,2,opt,def=0" json:"XP,omitempty"`
	// * 攻击力
	Attack *int32 `protobuf:"varint,3,opt,def=0" json:"Attack,omitempty"`
	// * 防御力
	Defense *int32 `protobuf:"varint,4,opt,def=0" json:"Defense,omitempty"`
	// * 生命值
	HP               *int32 `protobuf:"varint,5,opt,def=0" json:"HP,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LEVELATTRIBUTES) Reset()         { *m = LEVELATTRIBUTES{} }
func (m *LEVELATTRIBUTES) String() string { return proto.CompactTextString(m) }
func (*LEVELATTRIBUTES) ProtoMessage()    {}

const Default_LEVELATTRIBUTES_Level int32 = 0
const Default_LEVELATTRIBUTES_XP int32 = 0
const Default_LEVELATTRIBUTES_Attack int32 = 0
const Default_LEVELATTRIBUTES_Defense int32 = 0
const Default_LEVELATTRIBUTES_HP int32 = 0

func (m *LEVELATTRIBUTES) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return Default_LEVELATTRIBUTES_Level
}

func (m *LEVELATTRIBUTES) GetXP() int32 {
	if m != nil && m.XP != nil {
		return *m.XP
	}
	return Default_LEVELATTRIBUTES_XP
}

func (m *LEVELATTRIBUTES) GetAttack() int32 {
	if m != nil && m.Attack != nil {
		return *m.Attack
	}
	return Default_LEVELATTRIBUTES_Attack
}

func (m *LEVELATTRIBUTES) GetDefense() int32 {
	if m != nil && m.Defense != nil {
		return *m.Defense
	}
	return Default_LEVELATTRIBUTES_Defense
}

func (m *LEVELATTRIBUTES) GetHP() int32 {
	if m != nil && m.HP != nil {
		return *m.HP
	}
	return Default_LEVELATTRIBUTES_HP
}

type LEVELATTRIBUTES_ARRAY struct {
	Items            []*LEVELATTRIBUTES `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *LEVELATTRIBUTES_ARRAY) Reset()         { *m = LEVELATTRIBUTES_ARRAY{} }
func (m *LEVELATTRIBUTES_ARRAY) String() string { return proto.CompactTextString(m) }
func (*LEVELATTRIBUTES_ARRAY) ProtoMessage()    {}

func (m *LEVELATTRIBUTES_ARRAY) GetItems() []*LEVELATTRIBUTES {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
