// Code generated by protoc-gen-go.
// source: ProtobufGen_newstarlvupstagecost.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type NEWSTARLVUPSTAGECOST struct {
	// * 钻石升星次数
	HCOperateTimes *uint32 `protobuf:"varint,1,req,def=0" json:"HCOperateTimes,omitempty"`
	// * 钻石消耗
	HCCost           *uint32 `protobuf:"varint,2,req,def=0" json:"HCCost,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NEWSTARLVUPSTAGECOST) Reset()         { *m = NEWSTARLVUPSTAGECOST{} }
func (m *NEWSTARLVUPSTAGECOST) String() string { return proto.CompactTextString(m) }
func (*NEWSTARLVUPSTAGECOST) ProtoMessage()    {}

const Default_NEWSTARLVUPSTAGECOST_HCOperateTimes uint32 = 0
const Default_NEWSTARLVUPSTAGECOST_HCCost uint32 = 0

func (m *NEWSTARLVUPSTAGECOST) GetHCOperateTimes() uint32 {
	if m != nil && m.HCOperateTimes != nil {
		return *m.HCOperateTimes
	}
	return Default_NEWSTARLVUPSTAGECOST_HCOperateTimes
}

func (m *NEWSTARLVUPSTAGECOST) GetHCCost() uint32 {
	if m != nil && m.HCCost != nil {
		return *m.HCCost
	}
	return Default_NEWSTARLVUPSTAGECOST_HCCost
}

type NEWSTARLVUPSTAGECOST_ARRAY struct {
	Items            []*NEWSTARLVUPSTAGECOST `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *NEWSTARLVUPSTAGECOST_ARRAY) Reset()         { *m = NEWSTARLVUPSTAGECOST_ARRAY{} }
func (m *NEWSTARLVUPSTAGECOST_ARRAY) String() string { return proto.CompactTextString(m) }
func (*NEWSTARLVUPSTAGECOST_ARRAY) ProtoMessage()    {}

func (m *NEWSTARLVUPSTAGECOST_ARRAY) GetItems() []*NEWSTARLVUPSTAGECOST {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
