// Code generated by protoc-gen-go.
// source: ProtobufGen_gstgbossfightbonus.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GSTGBOSSFIGHTBONUS struct {
	// * 科技id
	GSTid *uint32 `protobuf:"varint,1,req,def=0" json:"GSTid,omitempty"`
	// * 科技等级
	Level *uint32 `protobuf:"varint,2,req,def=0" json:"Level,omitempty"`
	// * 军团等级需求
	GuildLevelReq *uint32 `protobuf:"varint,3,req,def=0" json:"GuildLevelReq,omitempty"`
	// * 昆仑梦境军魂的加成
	GoldRewardBonus *float32 `protobuf:"fixed32,4,req,def=0" json:"GoldRewardBonus,omitempty"`
	// * 需要多少科技点升这一级
	GSP              *uint32 `protobuf:"varint,5,req,def=0" json:"GSP,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GSTGBOSSFIGHTBONUS) Reset()         { *m = GSTGBOSSFIGHTBONUS{} }
func (m *GSTGBOSSFIGHTBONUS) String() string { return proto.CompactTextString(m) }
func (*GSTGBOSSFIGHTBONUS) ProtoMessage()    {}

const Default_GSTGBOSSFIGHTBONUS_GSTid uint32 = 0
const Default_GSTGBOSSFIGHTBONUS_Level uint32 = 0
const Default_GSTGBOSSFIGHTBONUS_GuildLevelReq uint32 = 0
const Default_GSTGBOSSFIGHTBONUS_GoldRewardBonus float32 = 0
const Default_GSTGBOSSFIGHTBONUS_GSP uint32 = 0

func (m *GSTGBOSSFIGHTBONUS) GetGSTid() uint32 {
	if m != nil && m.GSTid != nil {
		return *m.GSTid
	}
	return Default_GSTGBOSSFIGHTBONUS_GSTid
}

func (m *GSTGBOSSFIGHTBONUS) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return Default_GSTGBOSSFIGHTBONUS_Level
}

func (m *GSTGBOSSFIGHTBONUS) GetGuildLevelReq() uint32 {
	if m != nil && m.GuildLevelReq != nil {
		return *m.GuildLevelReq
	}
	return Default_GSTGBOSSFIGHTBONUS_GuildLevelReq
}

func (m *GSTGBOSSFIGHTBONUS) GetGoldRewardBonus() float32 {
	if m != nil && m.GoldRewardBonus != nil {
		return *m.GoldRewardBonus
	}
	return Default_GSTGBOSSFIGHTBONUS_GoldRewardBonus
}

func (m *GSTGBOSSFIGHTBONUS) GetGSP() uint32 {
	if m != nil && m.GSP != nil {
		return *m.GSP
	}
	return Default_GSTGBOSSFIGHTBONUS_GSP
}

type GSTGBOSSFIGHTBONUS_ARRAY struct {
	Items            []*GSTGBOSSFIGHTBONUS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *GSTGBOSSFIGHTBONUS_ARRAY) Reset()         { *m = GSTGBOSSFIGHTBONUS_ARRAY{} }
func (m *GSTGBOSSFIGHTBONUS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GSTGBOSSFIGHTBONUS_ARRAY) ProtoMessage()    {}

func (m *GSTGBOSSFIGHTBONUS_ARRAY) GetItems() []*GSTGBOSSFIGHTBONUS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
