// Code generated by protoc-gen-go.
// source: ProtobufGen_scpurchase.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SCPURCHASE struct {
	// * SC购买次数
	SCPurchaseTime *uint32 `protobuf:"varint,1,req,def=0" json:"SCPurchaseTime,omitempty"`
	// * 点金手所需的HC
	SCPrice          *uint32 `protobuf:"varint,2,req,def=0" json:"SCPrice,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCPURCHASE) Reset()         { *m = SCPURCHASE{} }
func (m *SCPURCHASE) String() string { return proto.CompactTextString(m) }
func (*SCPURCHASE) ProtoMessage()    {}

const Default_SCPURCHASE_SCPurchaseTime uint32 = 0
const Default_SCPURCHASE_SCPrice uint32 = 0

func (m *SCPURCHASE) GetSCPurchaseTime() uint32 {
	if m != nil && m.SCPurchaseTime != nil {
		return *m.SCPurchaseTime
	}
	return Default_SCPURCHASE_SCPurchaseTime
}

func (m *SCPURCHASE) GetSCPrice() uint32 {
	if m != nil && m.SCPrice != nil {
		return *m.SCPrice
	}
	return Default_SCPURCHASE_SCPrice
}

type SCPURCHASE_ARRAY struct {
	Items            []*SCPURCHASE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SCPURCHASE_ARRAY) Reset()         { *m = SCPURCHASE_ARRAY{} }
func (m *SCPURCHASE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*SCPURCHASE_ARRAY) ProtoMessage()    {}

func (m *SCPURCHASE_ARRAY) GetItems() []*SCPURCHASE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
