// Code generated by protoc-gen-go.
// source: ProtobufGen_wbsscorelevel.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type WBSSCORELEVEL struct {
	// * 变强的类型
	WBSType *uint32 `protobuf:"varint,1,req,def=0" json:"WBSType,omitempty"`
	// * 角色等级
	Level *uint32 `protobuf:"varint,2,opt,def=0" json:"Level,omitempty"`
	// * 用于计算进度的设定评分
	StandardScore          *uint32                        `protobuf:"varint,3,opt,def=0" json:"StandardScore,omitempty"`
	SLevelDetails_Template []*WBSSCORELEVEL_SLevelDetails `protobuf:"bytes,4,rep" json:"SLevelDetails_Template,omitempty"`
	XXX_unrecognized       []byte                         `json:"-"`
}

func (m *WBSSCORELEVEL) Reset()         { *m = WBSSCORELEVEL{} }
func (m *WBSSCORELEVEL) String() string { return proto.CompactTextString(m) }
func (*WBSSCORELEVEL) ProtoMessage()    {}

const Default_WBSSCORELEVEL_WBSType uint32 = 0
const Default_WBSSCORELEVEL_Level uint32 = 0
const Default_WBSSCORELEVEL_StandardScore uint32 = 0

func (m *WBSSCORELEVEL) GetWBSType() uint32 {
	if m != nil && m.WBSType != nil {
		return *m.WBSType
	}
	return Default_WBSSCORELEVEL_WBSType
}

func (m *WBSSCORELEVEL) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return Default_WBSSCORELEVEL_Level
}

func (m *WBSSCORELEVEL) GetStandardScore() uint32 {
	if m != nil && m.StandardScore != nil {
		return *m.StandardScore
	}
	return Default_WBSSCORELEVEL_StandardScore
}

func (m *WBSSCORELEVEL) GetSLevelDetails_Template() []*WBSSCORELEVEL_SLevelDetails {
	if m != nil {
		return m.SLevelDetails_Template
	}
	return nil
}

type WBSSCORELEVEL_SLevelDetails struct {
	// * 评分等级
	ScoreLevel *uint32 `protobuf:"varint,1,opt,def=0" json:"ScoreLevel,omitempty"`
	// * 评分下限
	ScoreLowerLimit *uint32 `protobuf:"varint,2,opt,def=0" json:"ScoreLowerLimit,omitempty"`
	// * 评分上限
	ScoreUpperLimit  *uint32 `protobuf:"varint,3,opt,def=0" json:"ScoreUpperLimit,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WBSSCORELEVEL_SLevelDetails) Reset()         { *m = WBSSCORELEVEL_SLevelDetails{} }
func (m *WBSSCORELEVEL_SLevelDetails) String() string { return proto.CompactTextString(m) }
func (*WBSSCORELEVEL_SLevelDetails) ProtoMessage()    {}

const Default_WBSSCORELEVEL_SLevelDetails_ScoreLevel uint32 = 0
const Default_WBSSCORELEVEL_SLevelDetails_ScoreLowerLimit uint32 = 0
const Default_WBSSCORELEVEL_SLevelDetails_ScoreUpperLimit uint32 = 0

func (m *WBSSCORELEVEL_SLevelDetails) GetScoreLevel() uint32 {
	if m != nil && m.ScoreLevel != nil {
		return *m.ScoreLevel
	}
	return Default_WBSSCORELEVEL_SLevelDetails_ScoreLevel
}

func (m *WBSSCORELEVEL_SLevelDetails) GetScoreLowerLimit() uint32 {
	if m != nil && m.ScoreLowerLimit != nil {
		return *m.ScoreLowerLimit
	}
	return Default_WBSSCORELEVEL_SLevelDetails_ScoreLowerLimit
}

func (m *WBSSCORELEVEL_SLevelDetails) GetScoreUpperLimit() uint32 {
	if m != nil && m.ScoreUpperLimit != nil {
		return *m.ScoreUpperLimit
	}
	return Default_WBSSCORELEVEL_SLevelDetails_ScoreUpperLimit
}

type WBSSCORELEVEL_ARRAY struct {
	Items            []*WBSSCORELEVEL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *WBSSCORELEVEL_ARRAY) Reset()         { *m = WBSSCORELEVEL_ARRAY{} }
func (m *WBSSCORELEVEL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*WBSSCORELEVEL_ARRAY) ProtoMessage()    {}

func (m *WBSSCORELEVEL_ARRAY) GetItems() []*WBSSCORELEVEL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
