// Code generated by protoc-gen-go.
// source: ProtobufGen_betterequip.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BETTEREQUIP struct {
	// * 装备ID
	EquipID *string `protobuf:"bytes,1,opt,def=" json:"EquipID,omitempty"`
	// * 更好的装备
	BetterEquip1 *string `protobuf:"bytes,2,opt,def=" json:"BetterEquip1,omitempty"`
	// * 更好的装备
	BetterEquip2 *string `protobuf:"bytes,3,opt,def=" json:"BetterEquip2,omitempty"`
	// * 更好的装备
	BetterEquip3     *string `protobuf:"bytes,4,opt,def=" json:"BetterEquip3,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BETTEREQUIP) Reset()         { *m = BETTEREQUIP{} }
func (m *BETTEREQUIP) String() string { return proto.CompactTextString(m) }
func (*BETTEREQUIP) ProtoMessage()    {}

func (m *BETTEREQUIP) GetEquipID() string {
	if m != nil && m.EquipID != nil {
		return *m.EquipID
	}
	return ""
}

func (m *BETTEREQUIP) GetBetterEquip1() string {
	if m != nil && m.BetterEquip1 != nil {
		return *m.BetterEquip1
	}
	return ""
}

func (m *BETTEREQUIP) GetBetterEquip2() string {
	if m != nil && m.BetterEquip2 != nil {
		return *m.BetterEquip2
	}
	return ""
}

func (m *BETTEREQUIP) GetBetterEquip3() string {
	if m != nil && m.BetterEquip3 != nil {
		return *m.BetterEquip3
	}
	return ""
}

type BETTEREQUIP_ARRAY struct {
	Items            []*BETTEREQUIP `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *BETTEREQUIP_ARRAY) Reset()         { *m = BETTEREQUIP_ARRAY{} }
func (m *BETTEREQUIP_ARRAY) String() string { return proto.CompactTextString(m) }
func (*BETTEREQUIP_ARRAY) ProtoMessage()    {}

func (m *BETTEREQUIP_ARRAY) GetItems() []*BETTEREQUIP {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
