// Code generated by protoc-gen-go.
// source: ProtobufGen_boxsettings.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BOXSETTINGS struct {
	// * 活动ID
	ActivityID *uint32 `protobuf:"varint,1,opt,def=0" json:"ActivityID,omitempty"`
	// * 活动子ID
	ActivitySubID *uint32 `protobuf:"varint,2,opt,def=0" json:"ActivitySubID,omitempty"`
	// * 显示在界面上用于购买的物品，即买XX随机送某些东西
	GachaItem *string `protobuf:"bytes,16,opt,def=" json:"GachaItem,omitempty"`
	// * 货币道具ID
	GachaCoin1 *string `protobuf:"bytes,3,opt,def=" json:"GachaCoin1,omitempty"`
	// * 单次的价格
	APrice1 *uint32 `protobuf:"varint,4,opt,def=0" json:"APrice1,omitempty"`
	// * 10次的价格
	TenPrice1 *uint32 `protobuf:"varint,5,opt,def=0" json:"TenPrice1,omitempty"`
	// * 折扣
	Discount *uint32 `protobuf:"varint,15,opt,def=0" json:"Discount,omitempty"`
	// * 抽奖券ID
	GachaTicket *string `protobuf:"bytes,17,opt,def=" json:"GachaTicket,omitempty"`
	// * 单次抽奖券数量
	TAPrice *uint32 `protobuf:"varint,18,opt,def=1" json:"TAPrice,omitempty"`
	// * 10次抽奖券的数量
	TTenPrice *uint32 `protobuf:"varint,19,opt,def=0" json:"TTenPrice,omitempty"`
	// * 免费抽奖的重置时间
	ResetFreeTime *string `protobuf:"bytes,6,opt,def=" json:"ResetFreeTime,omitempty"`
	// * 常规组ID
	ItemGroupID *uint32 `protobuf:"varint,7,opt,def=0" json:"ItemGroupID,omitempty"`
	// * 每日抽奖次数上限
	DailyLimit *uint32 `protobuf:"varint,8,opt,def=0" json:"DailyLimit,omitempty"`
	// * 免费次数
	FreeTime *uint32 `protobuf:"varint,9,opt,def=0" json:"FreeTime,omitempty"`
	// * 宝箱名称IDS
	ActivitySubName *string `protobuf:"bytes,10,opt,def=" json:"ActivitySubName,omitempty"`
	// * 碎片品质（此品质之上的走跑马灯）
	MsgQuality *uint32 `protobuf:"varint,11,req,def=0" json:"MsgQuality,omitempty"`
	// * 跑马灯IDS
	MsgIDS *uint32 `protobuf:"varint,12,opt,def=0" json:"MsgIDS,omitempty"`
	// * 宝箱描述
	DescriptionIDS *string `protobuf:"bytes,13,opt,def=" json:"DescriptionIDS,omitempty"`
	// * 宝箱展示图
	Icon             *string `protobuf:"bytes,14,opt,def=" json:"Icon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BOXSETTINGS) Reset()         { *m = BOXSETTINGS{} }
func (m *BOXSETTINGS) String() string { return proto.CompactTextString(m) }
func (*BOXSETTINGS) ProtoMessage()    {}

const Default_BOXSETTINGS_ActivityID uint32 = 0
const Default_BOXSETTINGS_ActivitySubID uint32 = 0
const Default_BOXSETTINGS_APrice1 uint32 = 0
const Default_BOXSETTINGS_TenPrice1 uint32 = 0
const Default_BOXSETTINGS_Discount uint32 = 0
const Default_BOXSETTINGS_TAPrice uint32 = 1
const Default_BOXSETTINGS_TTenPrice uint32 = 0
const Default_BOXSETTINGS_ItemGroupID uint32 = 0
const Default_BOXSETTINGS_DailyLimit uint32 = 0
const Default_BOXSETTINGS_FreeTime uint32 = 0
const Default_BOXSETTINGS_MsgQuality uint32 = 0
const Default_BOXSETTINGS_MsgIDS uint32 = 0

func (m *BOXSETTINGS) GetActivityID() uint32 {
	if m != nil && m.ActivityID != nil {
		return *m.ActivityID
	}
	return Default_BOXSETTINGS_ActivityID
}

func (m *BOXSETTINGS) GetActivitySubID() uint32 {
	if m != nil && m.ActivitySubID != nil {
		return *m.ActivitySubID
	}
	return Default_BOXSETTINGS_ActivitySubID
}

func (m *BOXSETTINGS) GetGachaItem() string {
	if m != nil && m.GachaItem != nil {
		return *m.GachaItem
	}
	return ""
}

func (m *BOXSETTINGS) GetGachaCoin1() string {
	if m != nil && m.GachaCoin1 != nil {
		return *m.GachaCoin1
	}
	return ""
}

func (m *BOXSETTINGS) GetAPrice1() uint32 {
	if m != nil && m.APrice1 != nil {
		return *m.APrice1
	}
	return Default_BOXSETTINGS_APrice1
}

func (m *BOXSETTINGS) GetTenPrice1() uint32 {
	if m != nil && m.TenPrice1 != nil {
		return *m.TenPrice1
	}
	return Default_BOXSETTINGS_TenPrice1
}

func (m *BOXSETTINGS) GetDiscount() uint32 {
	if m != nil && m.Discount != nil {
		return *m.Discount
	}
	return Default_BOXSETTINGS_Discount
}

func (m *BOXSETTINGS) GetGachaTicket() string {
	if m != nil && m.GachaTicket != nil {
		return *m.GachaTicket
	}
	return ""
}

func (m *BOXSETTINGS) GetTAPrice() uint32 {
	if m != nil && m.TAPrice != nil {
		return *m.TAPrice
	}
	return Default_BOXSETTINGS_TAPrice
}

func (m *BOXSETTINGS) GetTTenPrice() uint32 {
	if m != nil && m.TTenPrice != nil {
		return *m.TTenPrice
	}
	return Default_BOXSETTINGS_TTenPrice
}

func (m *BOXSETTINGS) GetResetFreeTime() string {
	if m != nil && m.ResetFreeTime != nil {
		return *m.ResetFreeTime
	}
	return ""
}

func (m *BOXSETTINGS) GetItemGroupID() uint32 {
	if m != nil && m.ItemGroupID != nil {
		return *m.ItemGroupID
	}
	return Default_BOXSETTINGS_ItemGroupID
}

func (m *BOXSETTINGS) GetDailyLimit() uint32 {
	if m != nil && m.DailyLimit != nil {
		return *m.DailyLimit
	}
	return Default_BOXSETTINGS_DailyLimit
}

func (m *BOXSETTINGS) GetFreeTime() uint32 {
	if m != nil && m.FreeTime != nil {
		return *m.FreeTime
	}
	return Default_BOXSETTINGS_FreeTime
}

func (m *BOXSETTINGS) GetActivitySubName() string {
	if m != nil && m.ActivitySubName != nil {
		return *m.ActivitySubName
	}
	return ""
}

func (m *BOXSETTINGS) GetMsgQuality() uint32 {
	if m != nil && m.MsgQuality != nil {
		return *m.MsgQuality
	}
	return Default_BOXSETTINGS_MsgQuality
}

func (m *BOXSETTINGS) GetMsgIDS() uint32 {
	if m != nil && m.MsgIDS != nil {
		return *m.MsgIDS
	}
	return Default_BOXSETTINGS_MsgIDS
}

func (m *BOXSETTINGS) GetDescriptionIDS() string {
	if m != nil && m.DescriptionIDS != nil {
		return *m.DescriptionIDS
	}
	return ""
}

func (m *BOXSETTINGS) GetIcon() string {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return ""
}

type BOXSETTINGS_ARRAY struct {
	Items            []*BOXSETTINGS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *BOXSETTINGS_ARRAY) Reset()         { *m = BOXSETTINGS_ARRAY{} }
func (m *BOXSETTINGS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*BOXSETTINGS_ARRAY) ProtoMessage()    {}

func (m *BOXSETTINGS_ARRAY) GetItems() []*BOXSETTINGS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
