// Code generated by protoc-gen-go.
// source: ProtobufGen_eatbaozicost.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type EATBAOZICOST struct {
	// * 购买包子次数
	HTPointPurchaseTime *uint32 `protobuf:"varint,1,req,def=0" json:"HTPointPurchaseTime,omitempty"`
	// * 买包子价格
	HTPointPrice     *uint32 `protobuf:"varint,2,req,def=0" json:"HTPointPrice,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EATBAOZICOST) Reset()         { *m = EATBAOZICOST{} }
func (m *EATBAOZICOST) String() string { return proto.CompactTextString(m) }
func (*EATBAOZICOST) ProtoMessage()    {}

const Default_EATBAOZICOST_HTPointPurchaseTime uint32 = 0
const Default_EATBAOZICOST_HTPointPrice uint32 = 0

func (m *EATBAOZICOST) GetHTPointPurchaseTime() uint32 {
	if m != nil && m.HTPointPurchaseTime != nil {
		return *m.HTPointPurchaseTime
	}
	return Default_EATBAOZICOST_HTPointPurchaseTime
}

func (m *EATBAOZICOST) GetHTPointPrice() uint32 {
	if m != nil && m.HTPointPrice != nil {
		return *m.HTPointPrice
	}
	return Default_EATBAOZICOST_HTPointPrice
}

type EATBAOZICOST_ARRAY struct {
	Items            []*EATBAOZICOST `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *EATBAOZICOST_ARRAY) Reset()         { *m = EATBAOZICOST_ARRAY{} }
func (m *EATBAOZICOST_ARRAY) String() string { return proto.CompactTextString(m) }
func (*EATBAOZICOST_ARRAY) ProtoMessage()    {}

func (m *EATBAOZICOST_ARRAY) GetItems() []*EATBAOZICOST {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
