// Code generated by protoc-gen-go.
// source: ProtobufGen_coinorigin.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type COINORIGIN struct {
	// * 货币类型
	CoinType *string `protobuf:"bytes,1,opt,def=" json:"CoinType,omitempty"`
	// * 我要XX标题
	WannaCoinTitle          *string                      `protobuf:"bytes,3,opt,def=" json:"WannaCoinTitle,omitempty"`
	CoinOriginShow_Template []*COINORIGIN_CoinOriginShow `protobuf:"bytes,2,rep" json:"CoinOriginShow_Template,omitempty"`
	XXX_unrecognized        []byte                       `json:"-"`
}

func (m *COINORIGIN) Reset()         { *m = COINORIGIN{} }
func (m *COINORIGIN) String() string { return proto.CompactTextString(m) }
func (*COINORIGIN) ProtoMessage()    {}

func (m *COINORIGIN) GetCoinType() string {
	if m != nil && m.CoinType != nil {
		return *m.CoinType
	}
	return ""
}

func (m *COINORIGIN) GetWannaCoinTitle() string {
	if m != nil && m.WannaCoinTitle != nil {
		return *m.WannaCoinTitle
	}
	return ""
}

func (m *COINORIGIN) GetCoinOriginShow_Template() []*COINORIGIN_CoinOriginShow {
	if m != nil {
		return m.CoinOriginShow_Template
	}
	return nil
}

type COINORIGIN_CoinOriginShow struct {
	// * 来源ID
	OriginID         *uint32 `protobuf:"varint,1,opt,def=0" json:"OriginID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *COINORIGIN_CoinOriginShow) Reset()         { *m = COINORIGIN_CoinOriginShow{} }
func (m *COINORIGIN_CoinOriginShow) String() string { return proto.CompactTextString(m) }
func (*COINORIGIN_CoinOriginShow) ProtoMessage()    {}

const Default_COINORIGIN_CoinOriginShow_OriginID uint32 = 0

func (m *COINORIGIN_CoinOriginShow) GetOriginID() uint32 {
	if m != nil && m.OriginID != nil {
		return *m.OriginID
	}
	return Default_COINORIGIN_CoinOriginShow_OriginID
}

type COINORIGIN_ARRAY struct {
	Items            []*COINORIGIN `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *COINORIGIN_ARRAY) Reset()         { *m = COINORIGIN_ARRAY{} }
func (m *COINORIGIN_ARRAY) String() string { return proto.CompactTextString(m) }
func (*COINORIGIN_ARRAY) ProtoMessage()    {}

func (m *COINORIGIN_ARRAY) GetItems() []*COINORIGIN {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
