// Code generated by protoc-gen-go.
// source: ProtobufGen_firstpay.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FIRSTPAY struct {
	// * 活动ID
	FirstPayID *uint32 `protobuf:"varint,1,req,name=firstPayID,def=0" json:"firstPayID,omitempty"`
	// * 累计充值数（购买钻）
	HCBuyCount       *uint32           `protobuf:"varint,2,opt,def=0" json:"HCBuyCount,omitempty"`
	PayAward         []*FIRSTPAY_Award `protobuf:"bytes,3,rep" json:"PayAward,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *FIRSTPAY) Reset()         { *m = FIRSTPAY{} }
func (m *FIRSTPAY) String() string { return proto.CompactTextString(m) }
func (*FIRSTPAY) ProtoMessage()    {}

const Default_FIRSTPAY_FirstPayID uint32 = 0
const Default_FIRSTPAY_HCBuyCount uint32 = 0

func (m *FIRSTPAY) GetFirstPayID() uint32 {
	if m != nil && m.FirstPayID != nil {
		return *m.FirstPayID
	}
	return Default_FIRSTPAY_FirstPayID
}

func (m *FIRSTPAY) GetHCBuyCount() uint32 {
	if m != nil && m.HCBuyCount != nil {
		return *m.HCBuyCount
	}
	return Default_FIRSTPAY_HCBuyCount
}

func (m *FIRSTPAY) GetPayAward() []*FIRSTPAY_Award {
	if m != nil {
		return m.PayAward
	}
	return nil
}

type FIRSTPAY_Award struct {
	// * 奖励ID
	Reward *string `protobuf:"bytes,1,opt,def=" json:"Reward,omitempty"`
	// * 奖励数目
	Count            *uint32 `protobuf:"varint,2,opt,def=0" json:"Count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FIRSTPAY_Award) Reset()         { *m = FIRSTPAY_Award{} }
func (m *FIRSTPAY_Award) String() string { return proto.CompactTextString(m) }
func (*FIRSTPAY_Award) ProtoMessage()    {}

const Default_FIRSTPAY_Award_Count uint32 = 0

func (m *FIRSTPAY_Award) GetReward() string {
	if m != nil && m.Reward != nil {
		return *m.Reward
	}
	return ""
}

func (m *FIRSTPAY_Award) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return Default_FIRSTPAY_Award_Count
}

type FIRSTPAY_ARRAY struct {
	Items            []*FIRSTPAY `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FIRSTPAY_ARRAY) Reset()         { *m = FIRSTPAY_ARRAY{} }
func (m *FIRSTPAY_ARRAY) String() string { return proto.CompactTextString(m) }
func (*FIRSTPAY_ARRAY) ProtoMessage()    {}

func (m *FIRSTPAY_ARRAY) GetItems() []*FIRSTPAY {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
