// Code generated by protoc-gen-go.
// source: ProtobufGen_sgactivity.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SGACTIVITY struct {
	// * 跨服同组
	GroupID *uint32 `protobuf:"varint,1,opt,def=0" json:"GroupID,omitempty"`
	// * 活动表ID
	HotActivityID    []uint32 `protobuf:"varint,2,rep" json:"HotActivityID,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SGACTIVITY) Reset()         { *m = SGACTIVITY{} }
func (m *SGACTIVITY) String() string { return proto.CompactTextString(m) }
func (*SGACTIVITY) ProtoMessage()    {}

const Default_SGACTIVITY_GroupID uint32 = 0

func (m *SGACTIVITY) GetGroupID() uint32 {
	if m != nil && m.GroupID != nil {
		return *m.GroupID
	}
	return Default_SGACTIVITY_GroupID
}

func (m *SGACTIVITY) GetHotActivityID() []uint32 {
	if m != nil {
		return m.HotActivityID
	}
	return nil
}

type SGACTIVITY_ARRAY struct {
	Items            []*SGACTIVITY `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *SGACTIVITY_ARRAY) Reset()         { *m = SGACTIVITY_ARRAY{} }
func (m *SGACTIVITY_ARRAY) String() string { return proto.CompactTextString(m) }
func (*SGACTIVITY_ARRAY) ProtoMessage()    {}

func (m *SGACTIVITY_ARRAY) GetItems() []*SGACTIVITY {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
