// Code generated by protoc-gen-go.
// source: ProtobufGen_dialogueids.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DIALOGUEIDS struct {
	// * 对话ID
	DialogueID *uint32 `protobuf:"varint,1,req,def=0" json:"DialogueID,omitempty"`
	// * 对话所在状态
	DialogueState *uint32 `protobuf:"varint,2,opt,def=0" json:"DialogueState,omitempty"`
	// * 对话的IDS
	DialogueIDS      *string `protobuf:"bytes,3,opt,def=" json:"DialogueIDS,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DIALOGUEIDS) Reset()         { *m = DIALOGUEIDS{} }
func (m *DIALOGUEIDS) String() string { return proto.CompactTextString(m) }
func (*DIALOGUEIDS) ProtoMessage()    {}

const Default_DIALOGUEIDS_DialogueID uint32 = 0
const Default_DIALOGUEIDS_DialogueState uint32 = 0

func (m *DIALOGUEIDS) GetDialogueID() uint32 {
	if m != nil && m.DialogueID != nil {
		return *m.DialogueID
	}
	return Default_DIALOGUEIDS_DialogueID
}

func (m *DIALOGUEIDS) GetDialogueState() uint32 {
	if m != nil && m.DialogueState != nil {
		return *m.DialogueState
	}
	return Default_DIALOGUEIDS_DialogueState
}

func (m *DIALOGUEIDS) GetDialogueIDS() string {
	if m != nil && m.DialogueIDS != nil {
		return *m.DialogueIDS
	}
	return ""
}

type DIALOGUEIDS_ARRAY struct {
	Items            []*DIALOGUEIDS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *DIALOGUEIDS_ARRAY) Reset()         { *m = DIALOGUEIDS_ARRAY{} }
func (m *DIALOGUEIDS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*DIALOGUEIDS_ARRAY) ProtoMessage()    {}

func (m *DIALOGUEIDS_ARRAY) GetItems() []*DIALOGUEIDS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
