// Code generated by protoc-gen-go.
// source: ProtobufGen_tpvpmatch.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TPVPMATCH struct {
	// * 序号
	Index *uint32 `protobuf:"varint,1,req,def=0" json:"Index,omitempty"`
	// * 起始名次
	Start *uint32 `protobuf:"varint,2,opt,def=0" json:"Start,omitempty"`
	// * 截止名次
	End *uint32 `protobuf:"varint,3,opt,def=0" json:"End,omitempty"`
	// * 匹配上浮区间
	RandomRange *int32 `protobuf:"varint,4,opt,def=0" json:"RandomRange,omitempty"`
	// * 匹配下浮区间
	RandomRange2 *int32 `protobuf:"varint,8,opt,def=0" json:"RandomRange2,omitempty"`
	// * 对应机器人ID
	RobotID *int32 `protobuf:"varint,5,opt,def=0" json:"RobotID,omitempty"`
	// * 战力下浮区间
	GSRandRage_Lower *int32 `protobuf:"varint,6,opt,def=0" json:"GSRandRage_Lower,omitempty"`
	// * 战力上浮区间
	GSRandRage_Upper *int32 `protobuf:"varint,7,opt,def=0" json:"GSRandRage_Upper,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TPVPMATCH) Reset()         { *m = TPVPMATCH{} }
func (m *TPVPMATCH) String() string { return proto.CompactTextString(m) }
func (*TPVPMATCH) ProtoMessage()    {}

const Default_TPVPMATCH_Index uint32 = 0
const Default_TPVPMATCH_Start uint32 = 0
const Default_TPVPMATCH_End uint32 = 0
const Default_TPVPMATCH_RandomRange int32 = 0
const Default_TPVPMATCH_RandomRange2 int32 = 0
const Default_TPVPMATCH_RobotID int32 = 0
const Default_TPVPMATCH_GSRandRage_Lower int32 = 0
const Default_TPVPMATCH_GSRandRage_Upper int32 = 0

func (m *TPVPMATCH) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_TPVPMATCH_Index
}

func (m *TPVPMATCH) GetStart() uint32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return Default_TPVPMATCH_Start
}

func (m *TPVPMATCH) GetEnd() uint32 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return Default_TPVPMATCH_End
}

func (m *TPVPMATCH) GetRandomRange() int32 {
	if m != nil && m.RandomRange != nil {
		return *m.RandomRange
	}
	return Default_TPVPMATCH_RandomRange
}

func (m *TPVPMATCH) GetRandomRange2() int32 {
	if m != nil && m.RandomRange2 != nil {
		return *m.RandomRange2
	}
	return Default_TPVPMATCH_RandomRange2
}

func (m *TPVPMATCH) GetRobotID() int32 {
	if m != nil && m.RobotID != nil {
		return *m.RobotID
	}
	return Default_TPVPMATCH_RobotID
}

func (m *TPVPMATCH) GetGSRandRage_Lower() int32 {
	if m != nil && m.GSRandRage_Lower != nil {
		return *m.GSRandRage_Lower
	}
	return Default_TPVPMATCH_GSRandRage_Lower
}

func (m *TPVPMATCH) GetGSRandRage_Upper() int32 {
	if m != nil && m.GSRandRage_Upper != nil {
		return *m.GSRandRage_Upper
	}
	return Default_TPVPMATCH_GSRandRage_Upper
}

type TPVPMATCH_ARRAY struct {
	Items            []*TPVPMATCH `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *TPVPMATCH_ARRAY) Reset()         { *m = TPVPMATCH_ARRAY{} }
func (m *TPVPMATCH_ARRAY) String() string { return proto.CompactTextString(m) }
func (*TPVPMATCH_ARRAY) ProtoMessage()    {}

func (m *TPVPMATCH_ARRAY) GetItems() []*TPVPMATCH {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
