// Code generated by protoc-gen-go.
// source: ProtobufGen_tpvpfpass.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TPVPFPASS struct {
	// * 序号
	Index *uint32 `protobuf:"varint,1,req,def=0" json:"Index,omitempty"`
	// * 开始名次
	Start *uint32 `protobuf:"varint,2,opt,def=0" json:"Start,omitempty"`
	// * 截止名次
	End *uint32 `protobuf:"varint,3,opt,def=0" json:"End,omitempty"`
	// * 颜色类型
	ColorType        *uint32            `protobuf:"varint,4,opt,def=0" json:"ColorType,omitempty"`
	Fixed_Loot       []*TPVPFPASS_Loot1 `protobuf:"bytes,5,rep" json:"Fixed_Loot,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *TPVPFPASS) Reset()         { *m = TPVPFPASS{} }
func (m *TPVPFPASS) String() string { return proto.CompactTextString(m) }
func (*TPVPFPASS) ProtoMessage()    {}

const Default_TPVPFPASS_Index uint32 = 0
const Default_TPVPFPASS_Start uint32 = 0
const Default_TPVPFPASS_End uint32 = 0
const Default_TPVPFPASS_ColorType uint32 = 0

func (m *TPVPFPASS) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return Default_TPVPFPASS_Index
}

func (m *TPVPFPASS) GetStart() uint32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return Default_TPVPFPASS_Start
}

func (m *TPVPFPASS) GetEnd() uint32 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return Default_TPVPFPASS_End
}

func (m *TPVPFPASS) GetColorType() uint32 {
	if m != nil && m.ColorType != nil {
		return *m.ColorType
	}
	return Default_TPVPFPASS_ColorType
}

func (m *TPVPFPASS) GetFixed_Loot() []*TPVPFPASS_Loot1 {
	if m != nil {
		return m.Fixed_Loot
	}
	return nil
}

type TPVPFPASS_Loot1 struct {
	// * 首通奖励类型
	FixedLootID *string `protobuf:"bytes,1,opt,def=" json:"FixedLootID,omitempty"`
	// * 首通奖励数量
	FixedLootNumber  *uint32 `protobuf:"varint,2,opt,def=0" json:"FixedLootNumber,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TPVPFPASS_Loot1) Reset()         { *m = TPVPFPASS_Loot1{} }
func (m *TPVPFPASS_Loot1) String() string { return proto.CompactTextString(m) }
func (*TPVPFPASS_Loot1) ProtoMessage()    {}

const Default_TPVPFPASS_Loot1_FixedLootNumber uint32 = 0

func (m *TPVPFPASS_Loot1) GetFixedLootID() string {
	if m != nil && m.FixedLootID != nil {
		return *m.FixedLootID
	}
	return ""
}

func (m *TPVPFPASS_Loot1) GetFixedLootNumber() uint32 {
	if m != nil && m.FixedLootNumber != nil {
		return *m.FixedLootNumber
	}
	return Default_TPVPFPASS_Loot1_FixedLootNumber
}

type TPVPFPASS_ARRAY struct {
	Items            []*TPVPFPASS `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *TPVPFPASS_ARRAY) Reset()         { *m = TPVPFPASS_ARRAY{} }
func (m *TPVPFPASS_ARRAY) String() string { return proto.CompactTextString(m) }
func (*TPVPFPASS_ARRAY) ProtoMessage()    {}

func (m *TPVPFPASS_ARRAY) GetItems() []*TPVPFPASS {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
