// Code generated by protoc-gen-go.
// source: ProtobufGen_gvgcity.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type GVGCITY struct {
	// * ID
	CityID *uint32 `protobuf:"varint,1,req,def=0" json:"CityID,omitempty"`
	// * 城池类型
	CityType *uint32 `protobuf:"varint,2,opt,def=0" json:"CityType,omitempty"`
	// * 城池开关（0关，1开）
	CityOpening *uint32 `protobuf:"varint,7,opt,def=0" json:"CityOpening,omitempty"`
	// * 城池名称
	NAMEIDS *string `protobuf:"bytes,3,opt,def=" json:"NAMEIDS,omitempty"`
	// * 城池准备资源（cleanroom）
	CityReadyID *string `protobuf:"bytes,6,opt,def=" json:"CityReadyID,omitempty"`
	// * 战斗城池资源
	LevelinfoID *string `protobuf:"bytes,4,opt,def=" json:"LevelinfoID,omitempty"`
	// * 城池icon
	CityIcon         *string `protobuf:"bytes,5,opt,def=" json:"CityIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GVGCITY) Reset()         { *m = GVGCITY{} }
func (m *GVGCITY) String() string { return proto.CompactTextString(m) }
func (*GVGCITY) ProtoMessage()    {}

const Default_GVGCITY_CityID uint32 = 0
const Default_GVGCITY_CityType uint32 = 0
const Default_GVGCITY_CityOpening uint32 = 0

func (m *GVGCITY) GetCityID() uint32 {
	if m != nil && m.CityID != nil {
		return *m.CityID
	}
	return Default_GVGCITY_CityID
}

func (m *GVGCITY) GetCityType() uint32 {
	if m != nil && m.CityType != nil {
		return *m.CityType
	}
	return Default_GVGCITY_CityType
}

func (m *GVGCITY) GetCityOpening() uint32 {
	if m != nil && m.CityOpening != nil {
		return *m.CityOpening
	}
	return Default_GVGCITY_CityOpening
}

func (m *GVGCITY) GetNAMEIDS() string {
	if m != nil && m.NAMEIDS != nil {
		return *m.NAMEIDS
	}
	return ""
}

func (m *GVGCITY) GetCityReadyID() string {
	if m != nil && m.CityReadyID != nil {
		return *m.CityReadyID
	}
	return ""
}

func (m *GVGCITY) GetLevelinfoID() string {
	if m != nil && m.LevelinfoID != nil {
		return *m.LevelinfoID
	}
	return ""
}

func (m *GVGCITY) GetCityIcon() string {
	if m != nil && m.CityIcon != nil {
		return *m.CityIcon
	}
	return ""
}

type GVGCITY_ARRAY struct {
	Items            []*GVGCITY `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *GVGCITY_ARRAY) Reset()         { *m = GVGCITY_ARRAY{} }
func (m *GVGCITY_ARRAY) String() string { return proto.CompactTextString(m) }
func (*GVGCITY_ARRAY) ProtoMessage()    {}

func (m *GVGCITY_ARRAY) GetItems() []*GVGCITY {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
