// Code generated by protoc-gen-go.
// source: ProtobufGen_stagelimitreward.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type STAGELIMITREWARD struct {
	// * 关卡ID
	ID *string `protobuf:"bytes,1,req,def=" json:"ID,omitempty"`
	// * 战队经验
	CorpXP *uint32 `protobuf:"varint,2,opt,def=0" json:"CorpXP,omitempty"`
	// * 经验
	XP *uint32 `protobuf:"varint,3,opt,def=0" json:"XP,omitempty"`
	// * 金钱
	SC *uint32 `protobuf:"varint,4,opt,def=0" json:"SC,omitempty"`
	// * 手动经验
	ManualXP *uint32 `protobuf:"varint,5,opt,def=0" json:"ManualXP,omitempty"`
	// * 扫荡奖励
	SweepItem *string `protobuf:"bytes,6,opt,def=" json:"SweepItem,omitempty"`
	// * 扫荡奖励数量
	SweepCount *uint32 `protobuf:"varint,7,opt,def=0" json:"SweepCount,omitempty"`
	// * 初次通关掉落
	FirstLootItem *string `protobuf:"bytes,8,opt,def=" json:"FirstLootItem,omitempty"`
	// * 初次通关掉落数量
	FirstLootCount     *uint32                          `protobuf:"varint,9,opt,def=1" json:"FirstLootCount,omitempty"`
	SRewardLimit_Table []*STAGELIMITREWARD_SRewardLimit `protobuf:"bytes,10,rep" json:"SRewardLimit_Table,omitempty"`
	XXX_unrecognized   []byte                           `json:"-"`
}

func (m *STAGELIMITREWARD) Reset()         { *m = STAGELIMITREWARD{} }
func (m *STAGELIMITREWARD) String() string { return proto.CompactTextString(m) }
func (*STAGELIMITREWARD) ProtoMessage()    {}

const Default_STAGELIMITREWARD_CorpXP uint32 = 0
const Default_STAGELIMITREWARD_XP uint32 = 0
const Default_STAGELIMITREWARD_SC uint32 = 0
const Default_STAGELIMITREWARD_ManualXP uint32 = 0
const Default_STAGELIMITREWARD_SweepCount uint32 = 0
const Default_STAGELIMITREWARD_FirstLootCount uint32 = 1

func (m *STAGELIMITREWARD) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *STAGELIMITREWARD) GetCorpXP() uint32 {
	if m != nil && m.CorpXP != nil {
		return *m.CorpXP
	}
	return Default_STAGELIMITREWARD_CorpXP
}

func (m *STAGELIMITREWARD) GetXP() uint32 {
	if m != nil && m.XP != nil {
		return *m.XP
	}
	return Default_STAGELIMITREWARD_XP
}

func (m *STAGELIMITREWARD) GetSC() uint32 {
	if m != nil && m.SC != nil {
		return *m.SC
	}
	return Default_STAGELIMITREWARD_SC
}

func (m *STAGELIMITREWARD) GetManualXP() uint32 {
	if m != nil && m.ManualXP != nil {
		return *m.ManualXP
	}
	return Default_STAGELIMITREWARD_ManualXP
}

func (m *STAGELIMITREWARD) GetSweepItem() string {
	if m != nil && m.SweepItem != nil {
		return *m.SweepItem
	}
	return ""
}

func (m *STAGELIMITREWARD) GetSweepCount() uint32 {
	if m != nil && m.SweepCount != nil {
		return *m.SweepCount
	}
	return Default_STAGELIMITREWARD_SweepCount
}

func (m *STAGELIMITREWARD) GetFirstLootItem() string {
	if m != nil && m.FirstLootItem != nil {
		return *m.FirstLootItem
	}
	return ""
}

func (m *STAGELIMITREWARD) GetFirstLootCount() uint32 {
	if m != nil && m.FirstLootCount != nil {
		return *m.FirstLootCount
	}
	return Default_STAGELIMITREWARD_FirstLootCount
}

func (m *STAGELIMITREWARD) GetSRewardLimit_Table() []*STAGELIMITREWARD_SRewardLimit {
	if m != nil {
		return m.SRewardLimit_Table
	}
	return nil
}

type STAGELIMITREWARD_SRewardLimit struct {
	// * 物品组ID
	ItemGroupID *string `protobuf:"bytes,1,opt,def=" json:"ItemGroupID,omitempty"`
	// * （数量控制）掉落次数
	LootNum *int32 `protobuf:"varint,2,opt,def=1" json:"LootNum,omitempty"`
	// * （数量控制）随机区间
	LootSpace *int32 `protobuf:"varint,3,opt,def=0" json:"LootSpace,omitempty"`
	// * （数量控制）区间偏移量
	Offset *int32 `protobuf:"varint,4,opt,def=0" json:"Offset,omitempty"`
	// * 补偿物品组ID
	MItemGroupID     *string `protobuf:"bytes,5,opt,def=" json:"MItemGroupID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STAGELIMITREWARD_SRewardLimit) Reset()         { *m = STAGELIMITREWARD_SRewardLimit{} }
func (m *STAGELIMITREWARD_SRewardLimit) String() string { return proto.CompactTextString(m) }
func (*STAGELIMITREWARD_SRewardLimit) ProtoMessage()    {}

const Default_STAGELIMITREWARD_SRewardLimit_LootNum int32 = 1
const Default_STAGELIMITREWARD_SRewardLimit_LootSpace int32 = 0
const Default_STAGELIMITREWARD_SRewardLimit_Offset int32 = 0

func (m *STAGELIMITREWARD_SRewardLimit) GetItemGroupID() string {
	if m != nil && m.ItemGroupID != nil {
		return *m.ItemGroupID
	}
	return ""
}

func (m *STAGELIMITREWARD_SRewardLimit) GetLootNum() int32 {
	if m != nil && m.LootNum != nil {
		return *m.LootNum
	}
	return Default_STAGELIMITREWARD_SRewardLimit_LootNum
}

func (m *STAGELIMITREWARD_SRewardLimit) GetLootSpace() int32 {
	if m != nil && m.LootSpace != nil {
		return *m.LootSpace
	}
	return Default_STAGELIMITREWARD_SRewardLimit_LootSpace
}

func (m *STAGELIMITREWARD_SRewardLimit) GetOffset() int32 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return Default_STAGELIMITREWARD_SRewardLimit_Offset
}

func (m *STAGELIMITREWARD_SRewardLimit) GetMItemGroupID() string {
	if m != nil && m.MItemGroupID != nil {
		return *m.MItemGroupID
	}
	return ""
}

type STAGELIMITREWARD_ARRAY struct {
	Items            []*STAGELIMITREWARD `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *STAGELIMITREWARD_ARRAY) Reset()         { *m = STAGELIMITREWARD_ARRAY{} }
func (m *STAGELIMITREWARD_ARRAY) String() string { return proto.CompactTextString(m) }
func (*STAGELIMITREWARD_ARRAY) ProtoMessage()    {}

func (m *STAGELIMITREWARD_ARRAY) GetItems() []*STAGELIMITREWARD {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
