// Code generated by protoc-gen-go.
// source: ProtobufGen_htpointpurchase.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type HTPOINTPURCHASE struct {
	// * 主将技能点购买价格
	HTPointPurchaseTime *uint32 `protobuf:"varint,1,req,def=0" json:"HTPointPurchaseTime,omitempty"`
	// * 技能点所需的HC
	HTPointPrice     *uint32 `protobuf:"varint,2,req,def=0" json:"HTPointPrice,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HTPOINTPURCHASE) Reset()         { *m = HTPOINTPURCHASE{} }
func (m *HTPOINTPURCHASE) String() string { return proto.CompactTextString(m) }
func (*HTPOINTPURCHASE) ProtoMessage()    {}

const Default_HTPOINTPURCHASE_HTPointPurchaseTime uint32 = 0
const Default_HTPOINTPURCHASE_HTPointPrice uint32 = 0

func (m *HTPOINTPURCHASE) GetHTPointPurchaseTime() uint32 {
	if m != nil && m.HTPointPurchaseTime != nil {
		return *m.HTPointPurchaseTime
	}
	return Default_HTPOINTPURCHASE_HTPointPurchaseTime
}

func (m *HTPOINTPURCHASE) GetHTPointPrice() uint32 {
	if m != nil && m.HTPointPrice != nil {
		return *m.HTPointPrice
	}
	return Default_HTPOINTPURCHASE_HTPointPrice
}

type HTPOINTPURCHASE_ARRAY struct {
	Items            []*HTPOINTPURCHASE `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *HTPOINTPURCHASE_ARRAY) Reset()         { *m = HTPOINTPURCHASE_ARRAY{} }
func (m *HTPOINTPURCHASE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*HTPOINTPURCHASE_ARRAY) ProtoMessage()    {}

func (m *HTPOINTPURCHASE_ARRAY) GetItems() []*HTPOINTPURCHASE {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
