// Code generated by protoc-gen-go.
// source: ProtobufGen_wspvptime.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type WSPVPTIME struct {
	// * 挑战次数购买数量
	WsPvPTime *uint32 `protobuf:"varint,1,req,def=0" json:"WsPvPTime,omitempty"`
	// * HC消耗
	WsPvPPrice       *uint32 `protobuf:"varint,2,req,def=0" json:"WsPvPPrice,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WSPVPTIME) Reset()         { *m = WSPVPTIME{} }
func (m *WSPVPTIME) String() string { return proto.CompactTextString(m) }
func (*WSPVPTIME) ProtoMessage()    {}

const Default_WSPVPTIME_WsPvPTime uint32 = 0
const Default_WSPVPTIME_WsPvPPrice uint32 = 0

func (m *WSPVPTIME) GetWsPvPTime() uint32 {
	if m != nil && m.WsPvPTime != nil {
		return *m.WsPvPTime
	}
	return Default_WSPVPTIME_WsPvPTime
}

func (m *WSPVPTIME) GetWsPvPPrice() uint32 {
	if m != nil && m.WsPvPPrice != nil {
		return *m.WsPvPPrice
	}
	return Default_WSPVPTIME_WsPvPPrice
}

type WSPVPTIME_ARRAY struct {
	Items            []*WSPVPTIME `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *WSPVPTIME_ARRAY) Reset()         { *m = WSPVPTIME_ARRAY{} }
func (m *WSPVPTIME_ARRAY) String() string { return proto.CompactTextString(m) }
func (*WSPVPTIME_ARRAY) ProtoMessage()    {}

func (m *WSPVPTIME_ARRAY) GetItems() []*WSPVPTIME {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
