// Code generated by protoc-gen-go.
// source: ProtobufGen_modecontrol.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MODECONTROL struct {
	// * 玩法ID
	ModeID *uint32 `protobuf:"varint,1,req,def=0" json:"ModeID,omitempty"`
	// * 是否显示入口图标
	IsVisible *uint32 `protobuf:"varint,16,opt,def=0" json:"IsVisible,omitempty"`
	// * 开启等级
	OpenLevel *uint32 `protobuf:"varint,2,opt,def=0" json:"OpenLevel,omitempty"`
	// * 获取次数类型
	GetTicketType *uint32 `protobuf:"varint,3,opt,def=0" json:"GetTicketType,omitempty"`
	// * 在周几获得参与次数
	GetTicketDay *string `protobuf:"bytes,4,opt,def=" json:"GetTicketDay,omitempty"`
	// * 多长时间获取一次次数（MIN）
	GetTicketCD *uint32 `protobuf:"varint,5,opt,def=0" json:"GetTicketCD,omitempty"`
	// * 获取时钟
	GetTicketTime *string `protobuf:"bytes,6,opt,def=" json:"GetTicketTime,omitempty"`
	// * 获取次数
	GetTicketNumber *uint32 `protobuf:"varint,7,opt,def=0" json:"GetTicketNumber,omitempty"`
	// * 获取次数
	DailyQuestDemandNum *uint32 `protobuf:"varint,8,opt,def=0" json:"DailyQuestDemandNum,omitempty"`
	// * 获取方式特殊参数
	GetTicketValue1 *uint32 `protobuf:"varint,9,opt,def=0" json:"GetTicketValue1,omitempty"`
	// * 进入冷却时间（分）
	TicketCDM *uint32 `protobuf:"varint,10,opt,def=0" json:"TicketCDM,omitempty"`
	// * 消除冷却时间消耗（HC）
	CostTicketCD *uint32 `protobuf:"varint,11,opt,def=0" json:"CostTicketCD,omitempty"`
	// * 总共扫荡消耗
	CostOperation *uint32 `protobuf:"varint,12,opt,def=0" json:"CostOperation,omitempty"`
	// * 玩法名
	ModeName *string `protobuf:"bytes,13,opt,def=" json:"ModeName,omitempty"`
	// * 玩法描述
	ModeDes *string `protobuf:"bytes,14,opt,def=" json:"ModeDes,omitempty"`
	// * 功能解锁的的枚举
	ConditionID      *uint32 `protobuf:"varint,15,opt,def=0" json:"ConditionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MODECONTROL) Reset()         { *m = MODECONTROL{} }
func (m *MODECONTROL) String() string { return proto.CompactTextString(m) }
func (*MODECONTROL) ProtoMessage()    {}

const Default_MODECONTROL_ModeID uint32 = 0
const Default_MODECONTROL_IsVisible uint32 = 0
const Default_MODECONTROL_OpenLevel uint32 = 0
const Default_MODECONTROL_GetTicketType uint32 = 0
const Default_MODECONTROL_GetTicketCD uint32 = 0
const Default_MODECONTROL_GetTicketNumber uint32 = 0
const Default_MODECONTROL_DailyQuestDemandNum uint32 = 0
const Default_MODECONTROL_GetTicketValue1 uint32 = 0
const Default_MODECONTROL_TicketCDM uint32 = 0
const Default_MODECONTROL_CostTicketCD uint32 = 0
const Default_MODECONTROL_CostOperation uint32 = 0
const Default_MODECONTROL_ConditionID uint32 = 0

func (m *MODECONTROL) GetModeID() uint32 {
	if m != nil && m.ModeID != nil {
		return *m.ModeID
	}
	return Default_MODECONTROL_ModeID
}

func (m *MODECONTROL) GetIsVisible() uint32 {
	if m != nil && m.IsVisible != nil {
		return *m.IsVisible
	}
	return Default_MODECONTROL_IsVisible
}

func (m *MODECONTROL) GetOpenLevel() uint32 {
	if m != nil && m.OpenLevel != nil {
		return *m.OpenLevel
	}
	return Default_MODECONTROL_OpenLevel
}

func (m *MODECONTROL) GetGetTicketType() uint32 {
	if m != nil && m.GetTicketType != nil {
		return *m.GetTicketType
	}
	return Default_MODECONTROL_GetTicketType
}

func (m *MODECONTROL) GetGetTicketDay() string {
	if m != nil && m.GetTicketDay != nil {
		return *m.GetTicketDay
	}
	return ""
}

func (m *MODECONTROL) GetGetTicketCD() uint32 {
	if m != nil && m.GetTicketCD != nil {
		return *m.GetTicketCD
	}
	return Default_MODECONTROL_GetTicketCD
}

func (m *MODECONTROL) GetGetTicketTime() string {
	if m != nil && m.GetTicketTime != nil {
		return *m.GetTicketTime
	}
	return ""
}

func (m *MODECONTROL) GetGetTicketNumber() uint32 {
	if m != nil && m.GetTicketNumber != nil {
		return *m.GetTicketNumber
	}
	return Default_MODECONTROL_GetTicketNumber
}

func (m *MODECONTROL) GetDailyQuestDemandNum() uint32 {
	if m != nil && m.DailyQuestDemandNum != nil {
		return *m.DailyQuestDemandNum
	}
	return Default_MODECONTROL_DailyQuestDemandNum
}

func (m *MODECONTROL) GetGetTicketValue1() uint32 {
	if m != nil && m.GetTicketValue1 != nil {
		return *m.GetTicketValue1
	}
	return Default_MODECONTROL_GetTicketValue1
}

func (m *MODECONTROL) GetTicketCDM() uint32 {
	if m != nil && m.TicketCDM != nil {
		return *m.TicketCDM
	}
	return Default_MODECONTROL_TicketCDM
}

func (m *MODECONTROL) GetCostTicketCD() uint32 {
	if m != nil && m.CostTicketCD != nil {
		return *m.CostTicketCD
	}
	return Default_MODECONTROL_CostTicketCD
}

func (m *MODECONTROL) GetCostOperation() uint32 {
	if m != nil && m.CostOperation != nil {
		return *m.CostOperation
	}
	return Default_MODECONTROL_CostOperation
}

func (m *MODECONTROL) GetModeName() string {
	if m != nil && m.ModeName != nil {
		return *m.ModeName
	}
	return ""
}

func (m *MODECONTROL) GetModeDes() string {
	if m != nil && m.ModeDes != nil {
		return *m.ModeDes
	}
	return ""
}

func (m *MODECONTROL) GetConditionID() uint32 {
	if m != nil && m.ConditionID != nil {
		return *m.ConditionID
	}
	return Default_MODECONTROL_ConditionID
}

type MODECONTROL_ARRAY struct {
	Items            []*MODECONTROL `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MODECONTROL_ARRAY) Reset()         { *m = MODECONTROL_ARRAY{} }
func (m *MODECONTROL_ARRAY) String() string { return proto.CompactTextString(m) }
func (*MODECONTROL_ARRAY) ProtoMessage()    {}

func (m *MODECONTROL_ARRAY) GetItems() []*MODECONTROL {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
