// Code generated by protoc-gen-go.
// source: ProtobufGen_renamecost.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type RENAMECOST struct {
	// * 改名次数
	ReNameTime *uint32 `protobuf:"varint,1,req,def=0" json:"ReNameTime,omitempty"`
	// * 所需HC
	ReNamePrice      *uint32 `protobuf:"varint,2,req,def=0" json:"ReNamePrice,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RENAMECOST) Reset()         { *m = RENAMECOST{} }
func (m *RENAMECOST) String() string { return proto.CompactTextString(m) }
func (*RENAMECOST) ProtoMessage()    {}

const Default_RENAMECOST_ReNameTime uint32 = 0
const Default_RENAMECOST_ReNamePrice uint32 = 0

func (m *RENAMECOST) GetReNameTime() uint32 {
	if m != nil && m.ReNameTime != nil {
		return *m.ReNameTime
	}
	return Default_RENAMECOST_ReNameTime
}

func (m *RENAMECOST) GetReNamePrice() uint32 {
	if m != nil && m.ReNamePrice != nil {
		return *m.ReNamePrice
	}
	return Default_RENAMECOST_ReNamePrice
}

type RENAMECOST_ARRAY struct {
	Items            []*RENAMECOST `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *RENAMECOST_ARRAY) Reset()         { *m = RENAMECOST_ARRAY{} }
func (m *RENAMECOST_ARRAY) String() string { return proto.CompactTextString(m) }
func (*RENAMECOST_ARRAY) ProtoMessage()    {}

func (m *RENAMECOST_ARRAY) GetItems() []*RENAMECOST {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
