// Code generated by protoc-gen-go.
// source: ProtobufGen_tbossdungeon.proto
// DO NOT EDIT!

package ProtobufGen

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type TBOSSDUNGEON struct {
	// * 阵容组合ID
	TeamTypeID *uint32 `protobuf:"varint,1,req,def=0" json:"TeamTypeID,omitempty"`
	// * 组合的IDS
	TeamTypeIDS *string `protobuf:"bytes,5,req,def=" json:"TeamTypeIDS,omitempty"`
	// * 主将A限制类型
	HeroAType *uint32 `protobuf:"varint,2,req,def=0" json:"HeroAType,omitempty"`
	// * 主将B限制类型
	HeroBType        *uint32                    `protobuf:"varint,3,req,def=0" json:"HeroBType,omitempty"`
	Choose_Table     []*TBOSSDUNGEON_ChooseRule `protobuf:"bytes,4,rep" json:"Choose_Table,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *TBOSSDUNGEON) Reset()         { *m = TBOSSDUNGEON{} }
func (m *TBOSSDUNGEON) String() string { return proto.CompactTextString(m) }
func (*TBOSSDUNGEON) ProtoMessage()    {}

const Default_TBOSSDUNGEON_TeamTypeID uint32 = 0
const Default_TBOSSDUNGEON_HeroAType uint32 = 0
const Default_TBOSSDUNGEON_HeroBType uint32 = 0

func (m *TBOSSDUNGEON) GetTeamTypeID() uint32 {
	if m != nil && m.TeamTypeID != nil {
		return *m.TeamTypeID
	}
	return Default_TBOSSDUNGEON_TeamTypeID
}

func (m *TBOSSDUNGEON) GetTeamTypeIDS() string {
	if m != nil && m.TeamTypeIDS != nil {
		return *m.TeamTypeIDS
	}
	return ""
}

func (m *TBOSSDUNGEON) GetHeroAType() uint32 {
	if m != nil && m.HeroAType != nil {
		return *m.HeroAType
	}
	return Default_TBOSSDUNGEON_HeroAType
}

func (m *TBOSSDUNGEON) GetHeroBType() uint32 {
	if m != nil && m.HeroBType != nil {
		return *m.HeroBType
	}
	return Default_TBOSSDUNGEON_HeroBType
}

func (m *TBOSSDUNGEON) GetChoose_Table() []*TBOSSDUNGEON_ChooseRule {
	if m != nil {
		return m.Choose_Table
	}
	return nil
}

type TBOSSDUNGEON_ChooseRule struct {
	// * 战斗的boss
	WbossID *string `protobuf:"bytes,1,opt,def=" json:"WbossID,omitempty"`
	// * 战斗的场景
	LevelInfoID *string `protobuf:"bytes,2,opt,def=" json:"LevelInfoID,omitempty"`
	// * 随机权重
	ChooseChance     *uint32 `protobuf:"varint,3,opt,def=0" json:"ChooseChance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TBOSSDUNGEON_ChooseRule) Reset()         { *m = TBOSSDUNGEON_ChooseRule{} }
func (m *TBOSSDUNGEON_ChooseRule) String() string { return proto.CompactTextString(m) }
func (*TBOSSDUNGEON_ChooseRule) ProtoMessage()    {}

const Default_TBOSSDUNGEON_ChooseRule_ChooseChance uint32 = 0

func (m *TBOSSDUNGEON_ChooseRule) GetWbossID() string {
	if m != nil && m.WbossID != nil {
		return *m.WbossID
	}
	return ""
}

func (m *TBOSSDUNGEON_ChooseRule) GetLevelInfoID() string {
	if m != nil && m.LevelInfoID != nil {
		return *m.LevelInfoID
	}
	return ""
}

func (m *TBOSSDUNGEON_ChooseRule) GetChooseChance() uint32 {
	if m != nil && m.ChooseChance != nil {
		return *m.ChooseChance
	}
	return Default_TBOSSDUNGEON_ChooseRule_ChooseChance
}

type TBOSSDUNGEON_ARRAY struct {
	Items            []*TBOSSDUNGEON `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *TBOSSDUNGEON_ARRAY) Reset()         { *m = TBOSSDUNGEON_ARRAY{} }
func (m *TBOSSDUNGEON_ARRAY) String() string { return proto.CompactTextString(m) }
func (*TBOSSDUNGEON_ARRAY) ProtoMessage()    {}

func (m *TBOSSDUNGEON_ARRAY) GetItems() []*TBOSSDUNGEON {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
}
