// automatically generated by the FlatBuffers compiler, do not modify

package multiplayMsg

const (
	DatasNONE = 0
	DatasEnterMultiplayGameReq = 1
	DatasEnterMultiplayGameRsp = 2
	DatasGetGameStateReq = 3
	DatasGetGameStateRsp = 4
	DatasGetGameDatasReq = 5
	DatasGetGameDatasRsp = 6
	DatasHPNotify = 7
	DatasLeaveMultiplayGameNotify = 8
	DatasOnAccountEnterMultiplayGamePush = 9
	DatasStatePush = 10
	DatasReadyMultiplayGameNotify = 11
	DatasPing = 12
	DatasPong = 13
	DatasGetGameRewardsReq = 14
	DatasGetGameRewardsRsp = 15
	DatasBossData = 16
	DatasBossSimpleData = 17
	DatasPlayerData = 18
	DatasPlayerSimpleData = 19
	DatasEnemyHP = 20
	DatasSceneActivity = 21
	DatasChangeAvatar = 22
)

var EnumNamesDatas = map[int]string{
	DatasNONE:"NONE",
	DatasEnterMultiplayGameReq:"EnterMultiplayGameReq",
	DatasEnterMultiplayGameRsp:"EnterMultiplayGameRsp",
	DatasGetGameStateReq:"GetGameStateReq",
	DatasGetGameStateRsp:"GetGameStateRsp",
	DatasGetGameDatasReq:"GetGameDatasReq",
	DatasGetGameDatasRsp:"GetGameDatasRsp",
	DatasHPNotify:"HPNotify",
	DatasLeaveMultiplayGameNotify:"LeaveMultiplayGameNotify",
	DatasOnAccountEnterMultiplayGamePush:"OnAccountEnterMultiplayGamePush",
	DatasStatePush:"StatePush",
	DatasReadyMultiplayGameNotify:"ReadyMultiplayGameNotify",
	DatasPing:"Ping",
	DatasPong:"Pong",
	DatasGetGameRewardsReq:"GetGameRewardsReq",
	DatasGetGameRewardsRsp:"GetGameRewardsRsp",
	DatasBossData:"BossData",
	DatasBossSimpleData:"BossSimpleData",
	DatasPlayerData:"PlayerData",
	DatasPlayerSimpleData:"PlayerSimpleData",
	DatasEnemyHP:"EnemyHP",
	DatasSceneActivity:"SceneActivity",
	DatasChangeAvatar:"ChangeAvatar",
}

