// automatically generated by the FlatBuffers compiler, do not modify

package multiplayMsg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// [RPC]获取奖励
type GetGameRewardsReq struct {
	_tab flatbuffers.Table
}

func GetRootAsGetGameRewardsReq(buf []byte, offset flatbuffers.UOffsetT) *GetGameRewardsReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetGameRewardsReq{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetGameRewardsReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

///玩家账号ID
func (rcv *GetGameRewardsReq) AccountId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

///玩家账号ID
///请求房间ID
func (rcv *GetGameRewardsReq) RoomID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

///请求房间ID
func GetGameRewardsReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GetGameRewardsReqAddAccountId(builder *flatbuffers.Builder, accountId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(accountId), 0)
}
func GetGameRewardsReqAddRoomID(builder *flatbuffers.Builder, roomID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(roomID), 0)
}
func GetGameRewardsReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
