// automatically generated by the FlatBuffers compiler, do not modify

package multiplayMsg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

///Boss状态(数组中以Boss数据中的idx为索引)
type StateParam struct {
	_tab flatbuffers.Table
}

func GetRootAsStateParam(buf []byte, offset flatbuffers.UOffsetT) *StateParam {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StateParam{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StateParam) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StateParam) AccountID() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StateParam) Param() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StateParamStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StateParamAddAccountID(builder *flatbuffers.Builder, AccountID flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(AccountID), 0)
}
func StateParamAddParam(builder *flatbuffers.Builder, Param flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Param), 0)
}
func StateParamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
