// automatically generated by the FlatBuffers compiler, do not modify

namespace multiplayMsg
{

using System;
using FlatBuffers;

///[RPC]获取当前战斗状态
/// client -> multi 申请进入房间
public sealed class GetGameStateReq : Table {
  public static GetGameStateReq GetRootAsGetGameStateReq(ByteBuffer _bb) { return GetRootAsGetGameStateReq(_bb, new GetGameStateReq()); }
  public static GetGameStateReq GetRootAsGetGameStateReq(ByteBuffer _bb, GetGameStateReq obj) { return (obj.__init(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public GetGameStateReq __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  ///玩家账号ID
  public string AccountId { get { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetAccountIdBytes() { return __vector_as_arraysegment(4); }
  ///请求进入房间ID
  public string RoomID { get { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; } }
  public ArraySegment<byte>? GetRoomIDBytes() { return __vector_as_arraysegment(6); }

  public static Offset<GetGameStateReq> CreateGetGameStateReq(FlatBufferBuilder builder,
      StringOffset accountIdOffset = default(StringOffset),
      StringOffset roomIDOffset = default(StringOffset)) {
    builder.StartObject(2);
    GetGameStateReq.AddRoomID(builder, roomIDOffset);
    GetGameStateReq.AddAccountId(builder, accountIdOffset);
    return GetGameStateReq.EndGetGameStateReq(builder);
  }

  public static void StartGetGameStateReq(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAccountId(FlatBufferBuilder builder, StringOffset accountIdOffset) { builder.AddOffset(0, accountIdOffset.Value, 0); }
  public static void AddRoomID(FlatBufferBuilder builder, StringOffset roomIDOffset) { builder.AddOffset(1, roomIDOffset.Value, 0); }
  public static Offset<GetGameStateReq> EndGetGameStateReq(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetGameStateReq>(o);
  }
  public static void FinishGetGameStateReqBuffer(FlatBufferBuilder builder, Offset<GetGameStateReq> offset) { builder.Finish(offset.Value); }
};


}
